### ISSUE TITLE
Widget opens wrong section on app

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1000]
> Hey, not too sure when you guys added habitica widgets but I’m super happy you did! Unfortunately, it’s bugged out. I’m on iOS btw. So when I add a widget like the add task, make it different to my preferred opening screen in the app like todo, it opens to my specified page. It’s hard to explain so I’ll give an example. If I choose dailies to be the page that opens when I open Habitica, and press the todo widget, it opens in dailies.
> 
> Hope you can fix it and thanks for your hard work!
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 14.4.2
> Device: iPhone SE (2nd generation)
> App Version: 3.2.2 (577)
> User ID: f2df4013-8132-45c2-997b-40a1a1a492ac
> Level: 60
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0

The user replied to add that this seems to be due to the app not already being open in the background. If it is, the problem doesn't occur. That said, it might prove confusing to users so I thought it was worth opening the issue, at least.

**Comment by phillipthelen** [comment]
This is probably the widget clashing with the setting for a custom launch screen. When launching the app needs to check if it was launched to a specific URL and only open the custom launch screen if it wasn't
