### ISSUE TITLE
Seasonal shop appearing and disappearing

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1003]
> My Seasonal Shop keeps disappearing from my list of Shops.  If I quit the app and restart it, the Seasonal Shop reappears.
> 
> This misbehavior seems to have started since the recent update that added timers to time-limited items.  But I’m not entirely sure; it might be that since that update I’m just paying more attention to the list of Shops.
> 
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 14.4.2
> Device: iPhone X
> App Version: 3.2.3 (587)
> User ID: 809b7bbc-a562-4818-84ec-5e839426bf01
> Level: 26
> Class: warrior
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 7

**Comment by saraolson** [comment]
the seasonal shop is supposed to be gone when its not open now, however it shouldnt be reappearing when they open the app
