### ISSUE TITLE
Customise Avatar doesn't allow changing glasses

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1006]
Clearing cache did not help this user:

> I noticed an issue over the weekend (not sure how long it has been an issue but I noticed it then)—under customize avatar, I can change everything except glasses. When I try to tap other options in the glasses menu, it stays on the current selection. This is the only customization field I’m having this problem with. I’m on iOS app, have restarted multiple times. Is there something else I am missing? 
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 14.4.2
> Device: iPhone 8
> App Version: 3.2.3 (587)
> User ID: 88292252-ba75-4920-9e9d-7a9a9ec535d3
> Level: 173
> Class: mage
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0

**Comment by saraolson** [comment]
i wasnt able to reproduce this
