### ISSUE TITLE
Menu > Party causing crash

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1010]
> German Version of this App-> Main Menu-> click on groups-> app closes every time.
> Best regards^^
> 
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 14.3
> Device: iPhone 11 Pro
> App Version: 3.2.3 (587)
> User ID: a1ae1bf2-2545-44cf-af5b-7a721e4463cf
> Level: 65
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0

**Comment by phillipthelen** [comment]
It crashes for this one user in line 111 of MemberListView.swift. Can't reproduce it and no idea why it is happening.

**Comment by shanaqui** [comment]
There's another user reporting this as well, but I haven't got their userID yet... working on it!

**Comment by shanaqui** [comment]
> iOS Version: 14.4.2
> Device: iPhone 7
> App Version: 3.2.3 (587)
> User ID: 26b10618-e0d3-4442-9da0-4c86e4b9d099
> Level: 84
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 3

**Comment by shanaqui** [comment]
And another:

> iOS Version: 14.5
> Device: iPhone 11 Pro Max
> App Version: 3.3 (595)
> User ID: 62eb49cc-d1ca-4ed7-8929-f3536fcdb4ec
> Level: 6
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0

**Comment by shanaqui** [comment]
User 26b10618-e0d3-4442-9da0-4c86e4b9d099 reports that they *used* to be able to get to their party via a notification, even with this bug... but now that also crashes the app.

They're now on 3.3 (595).
