### ISSUE TITLE
Markdown images do not have a max width or height

### ISSUE THREAD

**Issue by lil5** [HabitRPG/habitrpg-ios#1012]
**Describe the bug**
If I add an image using markdown images are shown cropped at the width keeping its original height. 

**To Reproduce**
- Enter a chat
- Insert: `![](https://d33wubrfki0l68.cloudfront.net/eab45e25bb79970178fab7a2d10cba0209372a59/94d9e/assets/images/philly-magic-garden.jpg)`
- Send massage

**Expected behavior**
An image shown in the chat history fully visible in one window. 

**Screenshots**
![image](https://user-images.githubusercontent.com/17646836/118410261-d3cd7200-b68e-11eb-8e10-90ff280de2f9.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS14.5.1
 - App Version: 3.2.3
 - Habitica Username: lucy_bubbles

**Additional context**

**Comment by rolisanchez** [comment]
Created PR #1109 to fix this :)
