### ISSUE TITLE
Animal ears/tails inconsistent with web? (ears can't be bought as set, tails don't exist)

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1013]
> Hi Habitica,
> 
> For purchase in the iOS app: the standard animal ears are available for purchase under Customize Avatar | Head, but are missing the option to buy the set for 5 gems.  I can’t find the standard animal tails for sale anywhere in the iOS app.
> 
> (I went ahead and purchased the ears and tails on the website instead of the app, but wanted to let you know about this oddity in the app.)
> 
> Sincerely,
> —Sharon (@gyrfalcon17)
> 
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 14.5.1
> Device: iPhone X
> App Version: 3.2.3 (587)
> User ID: 809b7bbc-a562-4818-84ec-5e839426bf01
> Level: 52
> Class: warrior
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 7

**Comment by saraolson** [comment]
we were going to put this off until we could do some reorganizing of avatar customization/equipment but with the way things are now, im not sure when web would have the time to implement those changes. 

will take another look and see if we can just slap a bandaid on and get them visible without the overhaul.
