### ISSUE TITLE
Add task widget doesn't properly launch into task create when app isn't running

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1015]
"I have just realized this issue with habitica shortcut. To be more precise, it is the 4 add-new-tasks-to-Habitica. If the app is not running in the background, I tap on any of those shortcuts and it would lead me to the habits page only. But while the app is running, the shortcuts work perfectly.

I can attach a video for you to easily understand the situation."

https://user-images.githubusercontent.com/8144640/119332146-1b9c5c80-bc80-11eb-9acd-3c6b2b9435fc.mp4

> iOS Version: 14.5
> Device: iPhone XR
> App Version: 3.2.3 (587)
> User ID: b62ca3f1-9406-428c-a906-a69b6956d32c
> Level: 2
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0

**Comment by phillipthelen** [comment]
Fixed in 3.3

**Comment by saraolson** [comment]
this is fixed in 3.3
