### ISSUE TITLE
Remove 'Guild Challenges' button until we have that feature implemented

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1018]
On iOS, you can tap on a button called "guild challenges" from the details of a guild. A user is reporting that nothing loads at all for any guild they try. Clearing cache, pulling down to force sync, etc, nothing works.

I wondered if it was due to the pagination of loading challenges which has confused people sometimes in the past when they filtered without loading multiple "pages" by scrolling down a bunch first. If so, it still *seems* broken to a user who has no idea about that.

> iOS Version: 14.4.2
> Device: iPhone 11 Pro
> App Version: 3.2.3 (587)
> User ID: 09fbf562-1eff-4b22-8502-3372b0b85fa7
> Level: 25
> Class: mage
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0

**Comment by saraolson** [comment]
this is probably part of the mobile apps kinda patchy implementation of challenges, where designs are only half implemented. guild challenges should just be shown in the guild details screen, the only button should be a create challenge button for ppl that are allowed to do that.
