### ISSUE TITLE
Error with Space Penguin theme

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1023]
"Hi Habitica,

There is a problem with the “spacePenguineTheme” sound theme. 

Please see the screenshot below!

https://snipboard.io/n2LWGK.jpg

Thank you,
K"

> iOS Version: 14.4.2
> Device: iPhone 7 Plus
> App Version: 2.9 (469)
> User ID: b809fd43-3aee-44fc-b09b-c9b641ef988e
> Level: 52
> Class: healer
> Is in Inn: false
> Uses Costume: true

**Comment by Alys** [comment]
It's a spelling mistake on this line:
https://github.com/HabitRPG/habitica-ios/blob/d509b5b80b6ae8f36e6352be96ac755e61e972ed/HabitRPG/Utilities/SoundManager.swift#L55
The "ui" in Penguin is written as "iu" on both sides of the = sign.
