### ISSUE TITLE
Class selection issue led to lost gems

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1024]
> Just had a weird bug where at level 10 I had 20 allocated skill points. I had chosen Mage and put 8 points in Intelligence and 2 in Perception, but I still had 10 in Strength.
> 
> I closed the browser and opened my phone and I couldn't even look at the stats on ios, it told me I had to enable stats in the settings, did that. It told me to choose my class. I chose Mage. It told me to choose my class again. Again I chose Mage. I was then able to reallocate my stats and the 10 in Strength went away. Problem solved. But... I lost 3 gems doing all that.
> 
> Is there a way to get the 3 gems back?
>
> 
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 14.6
> Device: iPhone 8
> App Version: 3.3 (595)
> User ID: 58b202ed-c4f1-43a3-906e-d07903730253
> Level: 12
> Class: mage
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0

**Comment by saraolson** [comment]
so it sounds like there was a sync issue that would have been helped by them potentially pulling to reefresh, or force closing the app before continuing? will try to test this scenario out and see what happens

**Comment by saraolson** [comment]
This issues seems to be resolved as we haven't heard about it in awhile in reports. We also plan to improve the change class flow in the future to match android, which will hopefully catch any stray cases that may come up.
