### ISSUE TITLE
Widget doesn't honour Custom Day Start

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1025]
"Starting at midnight, the daily widget only says "start a new day" instead of showing the current remaining dailies. The rest of the app correctly honours the custom day start at 6am. (See attached screenshot.)

Expected outcome: The widget shows the remaining dailies until the custom day start is reached / cron will trigger.

Actual outcome: The widget is effectively useless in the window between midnight and custom day start, because it wants you to start a new day even though cron won't trigger yet."

![image0](https://user-images.githubusercontent.com/8144640/123439636-d7c3ac80-d5c9-11eb-9388-1d96f35bc984.jpeg)

> iOS Version: 14.6
> Device: iPhone SE
> App Version: 3.3.1 (600)
> User ID: 7d27d14b-c48e-46c8-be0e-04fce3d03158
> Level: 54
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 6

**Comment by saraolson** [comment]
need to talk w phillip to see about what we can do here. widgets will have more limitations than the actual app, but will if there are reasonable improvements we can make in this regard.
