### ISSUE TITLE
Beginner objectives appears to be deleteable if you slide, but isn't

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1026]
User report:

"I have another question now, sorry. How can I delete This 

![IMG_9382](https://user-images.githubusercontent.com/8144640/125086937-fc3c8000-e0c3-11eb-953d-7b8f7e21c673.PNG)

It has delete as a slide option, but won’t delete."

In their last report (which was some time ago), here are their details:

> iOS Version: 14.6
> Device: iPhone XR
> App Version: 3.3 (595)
> User ID: 4bc7110a-b981-4bff-8aff-dd1c09377b73
> Level: 136
> Class: healer
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 1

**Comment by saraolson** [comment]
They can only get rid of it by completing the objectives (should be possible within seconds tbh, as long as they complete 3 tasks they will have everything they need to finish it).

So the change would be to not allow it to swipe and appear deletable
