### ISSUE TITLE
Display issues with stats and avatar in version 3.3.1 (due to text size?)

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1028]
> Just some minor stuff:
> 1. The tails seem to go out of frame in the app avatar icon
> 2. The sand sculpture panda has a weird 2D overlap!
> 3. The level number doesn’t show up when a large font is used
> 4. Some text overlaps or gets cut off when a large font is used (see above picture).
> 
> Thank you so much and have a great weekend!
> Anna
> 
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 14.5.1
> Device: iPhone XS Max
> App Version: 3.3.1 (600)
> User ID: e5732225-de4f-41d5-b0b9-db155889c013
> Level: 98
> Class: mage
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 5

**Comment by saraolson** [comment]
@shanaqui could you share the images they included?

**Comment by shanaqui** [comment]
@saraolson Here you go!

![image0(1)](https://user-images.githubusercontent.com/8144640/127853888-aec307bd-2bdc-4059-ada5-5068e8355c44.jpeg)
