### ISSUE TITLE
Seasonal Shop not appearing

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1029]
![image](https://user-images.githubusercontent.com/8144640/125299606-35bdf700-e321-11eb-937e-70f0eed07371.png)

> iOS Version: 14.6
> Device: iPhone 7
> App Version: 3.3.1 (600)
> User ID: 5c103b76-7e6c-4cac-902b-cd1f1224c129
> Level: 105
> Class: healer
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 8

According to the user, this happened with the most recent update.

**Comment by shanaqui** [comment]
"Also i want to add details: today seasonal shop appeared in ios, i even took sea foam, but then I cleared cache and renewed data and shop disappeared again. Don’t know what’s wrong with it…"

**Comment by saraolson** [comment]
@shanaqui if this happens, ask them to force close the app (swipe it away, don't just minimize) and reopen it. the shop should appear again. will have to take a closer look as to why this is continuing to happen, as this update was supposed to show the shop more reliably.
