### ISSUE TITLE
User with CDS sees dailies for the wrong day in RYA

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1030]
The user has a CDS of 10pm, and has set up their tasks accordingly (the tasks they want to appear on Monday are set as tasks for Sundays). Things work as expected on the web version, but on mobile:

"when I check in after cron (Monday 10:05pm), it asks me to complete the undone activities from Saturday, not from Sunday."

> iOS Version: 13.3.1
> Device: iPhone SE
> App Version: 3.2.1 (572)
> User ID: 282c9c8c-fbbf-49c6-adec-64c3486404ff
> Level: 92
> Class: warrior
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 22

**Comment by saraolson** [comment]
this may have been fixed. going to close until its reported again.
