### ISSUE TITLE
Markdown in a task's checklist is not rendered (works fine on Web)

### ISSUE THREAD

**Issue by JamesValero** [HabitRPG/habitrpg-ios#1031]
**Describe the bug**
Markdown in a task's checklist is rendered on the web but not in iOS

**To Reproduce**
1. Create a task
2. Add a checklist item with markdown such as ** bold ** or > indent

**Expected behavior**
The bold, italic, indent, etc markdown would be displayed the same as the Web version of Habitica.

**Screenshots**
*Web*
![image](https://user-images.githubusercontent.com/10291196/125572654-e07d63b9-9bad-4190-b907-5911ed910164.png)

*iOS*
![image](https://user-images.githubusercontent.com/10291196/125572763-02a396cf-90db-49ff-8979-01343af96b1d.png)

**Smartphone (please complete the following information):**
 - Device: iPad 12.9 (2021) and iPhone X
 - OS: iPadOS 14.6 / iOS 14.6
 - App Version: 3.3.1
 - Habitica Username: MrLinux

**Additional context**
I would think the experience is supposed to be the same across the board on both Web and iOS.

**Comment by rolisanchez** [comment]
iOS 15 now supports markdown string ([source](https://developer.apple.com/documentation/foundation/attributedstring)).

I guess for users using earlier versions of iOS something like [SwiftyMarkdown](https://github.com/SimonFairbairn/SwiftyMarkdown) could be used?

I could try to tackle this :)

**Comment by rolisanchez** [comment]
I could try to tackle this :)

iOS 15 now supports markdown strings ([source](https://developer.apple.com/documentation/foundation/attributedstring)). So for the future there could be a rewrite to use iOS 15's AttributedString when available, and fallback on using Down for pre iOS 15 devices. It is used in many files though, and iOS 15 is quite new yet.

**Comment by rolisanchez** [comment]
Managed to fix the markdown strings on checklist. Block quotes seem to be a problem with Down though, even using their switching HabiticaStyler to use their default DownStyler, which implements styling for block quotes. 

It is indented though.

![after](https://user-images.githubusercontent.com/7276421/137639589-13571974-5161-4a87-acf3-3b41a427b654.png)
![before](https://user-images.githubusercontent.com/7276421/137639591-9a39be8f-fb27-4c66-a45f-b24526acdfdd.png)

**Comment by saraolson** [comment]
@rolisanchez thanks for looking into this! i'll mark this issue as in progress for you if you'd like to submit a PR. Looking at your screenshots, I think that's definitely a 'good enough' fix as markdown support has always been a 'we'll do our best' feature on the apps.

**Comment by rolisanchez** [comment]
@saraolson submitted PR #1099 :)
