### ISSUE TITLE
Connecting with Facebook causes crash

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1032]
Several users are reporting this, but so far I only got one version number response -- this person is on version 3.3.1:

>  I am writing with regard to a problem related to my Habitica app. Indeed, I try to connect with Facebook, but as soon as I press the necessary button, the app crash. Can you help me to fix the problem ? It’s an iPhone 12 with iOS 14.7. The problem was the same in iOS 14.6.

**Comment by creaturebytes** [comment]
I have another user who has reported crash + log-in issues via the Facebook login method. 

><BR> <BR>        User ID: 74c846da-e652-4f70-b913-da65d4565de9 <BR>        Level: 6 <BR>        Class: warrior <BR>        Dailies Paused: true <BR>        Uses Costume: undefined <BR>        Custom Day Start: 0 <BR>        Timezone Offset: -540 <BR>        Not Subscribed
>
>Hello! I am recently getting back into Habitica after a long hiatus. I downloaded the iOS app through the Japan App Store and  tried to log in through Facebook, but the app crashes as soon as I click on the Facebook icon. I tried uninstalling and reinstalling the app, uninstalling and restarting my phone, etc. but the problem persists. I can’t even log in to report the 
 problem from the app itself, which is why I’m reporting it from the website. Could someone please look into this? I’m using an iPhone 11 on the newest iOS version.
