### ISSUE TITLE
Butterfly mounts labelled as caterpillars

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1034]
Not sure if this is an iOS issue or a more general problem. In English, the pets are Caterpillars and the mounts are Butterflies.

> Hello,
> 
> I just noticed that the mounts in the app are named like the pets (in German). Is that a translation issue or is there a wrong variable in the code that puts in the pet’s string instead of the mount’s string?
> 
> It was irritating to choose a “Raupe” and get a butterfly for my Avatar.
> 
> Thanks for checking! Keep up the great work!
> 
> 
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 14.6
> Device: iPhone13,2
> App Version: 3.3.1 (600)
> User ID: 9ae04082-7868-4042-b073-33b7a32cd573
> Level: 47
> Class: mage
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0

**Comment by mnotti** [comment]
seems like more of a feature than a bug *no pun intended
caterpillars => butterflies is a natural progression ... close this one?

**Comment by saraolson** [comment]
On web they are labeled as 'Caterpillar' for pets and 'Butterfly' for mounts, so the inconsistency between web and iOS is the 'bug' rather than just a request for a change (iOS called them both caterpillars). Since we do call them Butterflies on another platform, we'd like it to be consistent.

**Comment by saraolson** [comment]
will be fixed in 3.10.1
