### ISSUE TITLE
User leaving party with active quest causes issues in viewing the party

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1036]
User report:

>  I’m not sure if this is a big, but I’m also not sure how to get help with this. It gives me an error when I click on party to try to joint my son. I’d love some help with this issue. Thanks!

> The error says “User with ID . . . . Not found”. Unfortunately, I could not copy the error message, and there is no way I can remember the number/letter sequence. As soon as I try to get into the party, it gives me the error code and boots me out.

When I checked, they were a member of the party. When Alys took a look, there was a quest in the invitation stage, owned by a player who had deleted their account. Their ID was the one showing as an error.

Alys deleted that quest data from the party, but it's unclear whether this has helped at this stage. I'm trying to persuade the user in question to try clearing their cache.

> iOS Version: 14.6
> Device: iPhone SE (2nd generation)
> App Version: 3.3.1 (600)
> User ID: 343835bd-5cca-492c-b61a-2d49b3fe7e6d
> Level: 68
> Class: healer
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0

**Comment by saraolson** [comment]
so the solution here would be to either better clear the invitation when a person deleted their account, or prevent deletion of account while they have an active quest they're inviting people to? (we already have error messages for active sub, so wouldn't be unheard of)

**Comment by saraolson** [comment]
After further discussion, we decided the solution to this would be a server change to resolve this across all platforms rather than a change on iOS in particular. Closing here.
