### ISSUE TITLE
Images added to challenge descriptions via Markdown are not resized to fit

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1038]
"Incorrect display of the image on the challenges page (example 'The language Learning Monster!' challenge)
How to achieve this:
- Go to the page with challenges;
- Open any selected challenge or select any one in the discover tab."

![image](https://user-images.githubusercontent.com/8144640/128011108-1b7ec3e3-d921-4c85-992d-97f66b7a0e7a.png)

iOS Version: 14.7.1
Device: iPhone 7 Plus
App Version: 3.3.1 (600)
User ID: 81918e09-14f3-450d-bc32-3f605b79b2ca
Level: 5
Class: warrior
Is in Inn: false
Uses Costume: true
Custom Day Start: 0

**Comment by saraolson** [comment]
this should be fixed by another pr that was submitted
