### ISSUE TITLE
Task layout goes wrong when you add a reminder

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1039]
I'm not actually sure how it's supposed to look, so I'm taking the user's word for this one.

"The page markup broke when choosing the reminder time
How to achieve this:
- Go to the page with habits/dailies/to do's;
- Create a new or open an existing record;
- Try to add a reminder time."

![image](https://user-images.githubusercontent.com/8144640/128011339-f94e5778-4ceb-4500-a8dc-7510cce6dcf7.png)

iOS Version: 14.7.1
Device: iPhone 7 Plus
App Version: 3.3.1 (600)
User ID: 81918e09-14f3-450d-bc32-3f605b79b2ca
Level: 5
Class: warrior
Is in Inn: false
Uses Costume: true
Custom Day Start: 0

**Comment by phillipthelen** [comment]
This is fixed with the task form redesign
