### ISSUE TITLE
"Wizard" displayed as initial label on Market drop-down list

### ISSUE THREAD

**Issue by vlvs** [HabitRPG/habitrpg-ios#1040]
**Describe the bug**
#944 is still happening: when a `Mage` enters the `Market`, the initial text shown on the drop-down class list says `"Wizard"` instead.

**To Reproduce**
- As a `Mage`, click the `Market` button in the `Shop` section.
- Check the label on the drop-down class list.

**Expected behavior**
The drop-down class list should display updated class name `"Mage"` label instead.

**Screenshots**
<img src="https://user-images.githubusercontent.com/39912609/128215762-6067d667-b3ce-42f7-8147-0370121f37ba.png" width="350" /> <img src="https://user-images.githubusercontent.com/39912609/128215754-a0050b35-2144-4483-bdba-8147178bd604.png" width="350" />

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.1
 - App Version: 3.3.1 (600)
 - Habitica Username: 1de07bdd-8336-406d-92a3-1dbb03e78cbe

**Comment by saraolson** [comment]
Thanks for your contribution! We'll review your PR soon and hopefully include it in the next version update, as we're working on iOS 3.4 right now.
