### ISSUE TITLE
Gifting gems to legit UUID throws user not found error

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitrpg-ios#1048]
I looked up the UUID this user is trying to gift to and the user definitely exists - Beth

User ID for my teammate is:

0b407a12-9571-4be0-9894-2094d418a373

Every time I try to send gems to my teammate I get this error. Nothing we do seems to fix it.

The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
iOS Version: 14.7.1
Device: iPhone 11
App Version: 3.3.1 (600)
User ID: f063bdad-4d96-4ea3-aac8-a3c78b016c33
Level: 109
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 7

![image0](https://user-images.githubusercontent.com/9218855/130284304-a8cec474-87de-499e-9482-00a67bf4a741.png)

**Comment by saraolson** [comment]
hm, i can't seem to replicate. they load for me, and if i 'accidentally' add a space, it doesnt even get past the 'enter a username' modal
