### ISSUE TITLE
ToastView overflowing bounds

### ISSUE THREAD

**Issue by vlvs** [HabitRPG/habitrpg-ios#1051]
**Describe the bug**
The `ToastView` displayed when a skill is cast has a subview whose white background overflow its bounds, resulting in a glitchy display on dark mode is used.

**To Reproduce**
Set `Theme Mode` to dark and cast a spell.

**Expected behavior**
All of `ToastView` subviews should be contained within its bounds, the background behind the rounded corners should be [clear](https://developer.apple.com/documentation/uikit/uicolor/1621945-clear).

**Screenshots**
<img src="https://user-images.githubusercontent.com/39912609/130337448-b758b524-fc31-4591-b6c2-db71eb439a1e.png" width="350" />

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.1
 - App Version: 3.3.1 (600)
 - Habitica Username: vlvs

**Comment by saraolson** [comment]
assigning the actual pr to the milestone instead of the issue just so less redundancy in the milestone list
