### ISSUE TITLE
Some dailies not appearing from previous day

### ISSUE THREAD

**Issue by rowandisco** [HabitRPG/habitrpg-ios#1054]
Dailies pop up the next day when previous day was not completed has seemingly random ones missed off the list and not able to be checked. Unsure if health is being taken for those not being checked but seems it might be.

**Comment by saraolson** [comment]
Hi @rowandisco, we already have an issue regarding Dailies not showing up in the record yesterday's activity modal correctly. could you leave a comment with your experiences in issue #1030 ? In particular, confirm if you use custom day start as well or not. thank you! I'll be closing this issue.
