### ISSUE TITLE
Gifted Gems went to user attempting to send rather than intended recipient

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitrpg-ios#1055]
We've gotten a couple reports of this now:

"I attempted to gift .99 worth of gems to @ButterflyWillow the purchase went through, but instead of her getting the gems, I did. :( She wants to change her class, so I'd really like it to go to her.

The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
iOS Version: 14.7.1
Device: iPhone 11 Pro Max
App Version: 3.3.3 (700)
User ID: da7490b6-a28a-442e-87b6-c5f3398cc9d0
Level: 74
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 0"

"
Gifted gems went to me not the recipients

The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
iOS Version: 14.7.1
Device: iPhone13,3
App Version: 3.3.3 (700)
User ID: 485d5410-45ae-494c-9539-7d4ff98d81c7
Level: 2
Class: warrior
Is in Inn: false
Uses Costume: false
Custom Day Start: 0"

**Comment by saraolson** [comment]
was able to test and confirm. if its easy we'll include in 3.4, if not we'll hotfix in 3.4.1
