### ISSUE TITLE
Update report violation UI

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#1056]
It exists in a modal right now, we want to change that to a full screen sheet that has an area for the reporter to add comments. design exists on zeplin for staff to implement 
<img width="198" alt="Screen Shot 2021-09-09 at 10 27 35 AM" src="https://user-images.githubusercontent.com/12453119/132704621-74dd0fa9-645e-4c5c-9d9a-3c13e32456a4.png">

**Comment by tjb** [comment]
This seems like a cool enhancement. @saraolson are you and the team open to someone trying to tackle this?

**Comment by saraolson** [comment]
@tjb we're probably going to save this for our team to handle as we can't share design specs externally, and this design will need a little updating as well.
