### ISSUE TITLE
Task reminders not being sent

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#1062]
few reports of people's task reminders just not coming through for them anymore

>  I am not getting reminder notifications on my Habitica app. I’m using an iPhone X with OS 14.7.1. Habitica is updated. I have tried:
 -clearing the cache
-reloading the content
-refreshing the app
-force-closing and restarting 
-updating the app & OS
-restarting the phone. 

> I have stopped receiving push notifications for Habitica on iOS. I have checked in my phone settings and confirmed that push notifications are enabled, and confirmed in Habitica has push notifications enabled. I have tried clearing the cache, reloading the app, logging out and logging back in, and deleting and reinstalling the app. Restarting my phone does not fix the problem. 

>  I tried removing the reminder on a daily task, saving it, readding it, and saving it again but it didn't change the notification problem. I've also tried making new to-do tasks with scheduled reminders with similar results. It seems like none of my reminders are sending. 

iOS Version: 14.7.1
Device: iPhone SE (2nd generation)
App Version: 3.3.3 (700)
User ID: d3711164-3375-4fce-8935-c7484c8a180e
Level: 16
Class: mage
Is in Inn: false
Uses Costume: false
Custom Day Start: 3

**Comment by stoiven** [comment]
Same issue here iOS 15

**Comment by saraolson** [comment]
@stoiven what version of the iOS app are you on now (can view from Menu > About) we had one person where this was fixed for them after updating to 3.4.1. if you're on 3.4.1, is it still happening?

**Comment by stoiven** [comment]
> @stoiven what version of the iOS app are you on now (can view from Menu > About) we had one person where this was fixed for them after updating to 3.4.1. if you're on 3.4.1, is it still happening?

On iOS 15.0. I updated to 3.4.1 and it's still happening. I've just been changing daily reminders to see if it would populate the notification but it's still not sending @saraolson

**Comment by creaturebytes** [comment]
Newer report with same issue on 3.4.4 
>iOS Version: 15.1
>Device: iPhone XR
>App Version: 3.4.4 (649)
>User ID: e98c753d-a806-4c68-868a-63a356f0ad5b
>Level: 9
>Class: warrior
>Is in Inn: true
>Uses Costume: false
>Custom Day Start: 6
>"Habitica doesn’t send push notifications at all but shows the badge count and nothing has been able to fix it."

**Comment by stoiven** [comment]
The weird thing is, that it works "sometimes"

**Comment by creaturebytes** [comment]
>Email | oliverjones615@gmail.com
>UUID | c1dc8ab4-c6c5-44ad-8aac-6e3706200354
>User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 >Safari/537.36
>Level | 5
>Class | rogue
>Dailies Paused | false
>Costume | false
>Custom Day Start | 5
>Description: "Hello, not sure if this qualifies but the push notifications don't work on my phone (iOS 14.3)"

**Comment by cvarrichio** [comment]
This issue still persists for me.  Daily reminder is on, notifications are enabled in IOS, but I do not receive a daily notification.

iOS Version: 15.5
Device: iPhone 12 Mini
App Version: 3.5.4

**Comment by RedsAnDev** [comment]
This issue still persists. None issue send to my list. 
iOsVersion: 16.2
Device: Iphone 12
