### ISSUE TITLE
Change due date display on tasks

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#1069]
Right now if i set due date to next week, it will show 'Due Sept 14, 2021'

Would like to implement new rules:
1. Don't show the word 'Due' just have the date following the calendar icon
2. If the due date is in the current calendar year then don't show the year, ex: Sept 14
3. If the due date is in another calendar year, show the date in this format: mm/dd/yy (and let this change for different locations that favor dd/mm/yy format)

**Comment by rolisanchez** [comment]
So given today's date, Oct. 13, would it be (ascending from past dates):

[calendar icon] 09/13/20 (1 year + 1 month ago, or 13/09/20 in Spanish locale)
[calendar icon] Sept. 13 (1 month ago)
[calendar icon] Oct. 12
[calendar icon] Today 
[calendar icon] Tomorrow
[calendar icon] In X days (if today - duedate < 7 days)
[calendar icon] Nov. 13 (in 1 month)
[calendar icon] 01/10/22 (or 10/01/22 in Spanish locale)

If these rules are ok, could I take this? :)

**Comment by saraolson** [comment]
@rolisanchez that looks about right! the only change would be no period after the abbreviated month names, so Sept 13, not Sept. 13

and just to confirm the 'in x days' logic, starting from the 14th it would look like:
14: Today
15: Tomorrow
16: In 2 days
17: In 3 days
18: In 4 days
19: In 5 days
20: In 6 days
21: Oct 21

ill mark this as in progress for ya, let us know if you need to drop the issue for any reason

**Comment by rolisanchez** [comment]
@saraolson Made a pull request #1096 :)

**Comment by saraolson** [comment]
@rolisanchez awesome! thank you, we'll take a look and assign it to an appropriate update milestone soon. We're jumping between iOS and android right now so may be a bit of a delay before actual release.
