### ISSUE TITLE
Auto focus checklist textbox after tapping 'New checklist item'

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#1070]

**Comment by rolisanchez** [comment]
Is this the desired behavior? 

I did this by getting the UUID of the latest created Item

https://user-images.githubusercontent.com/7276421/137784104-bab8aa8c-fa0f-4990-be04-89d337051c09.mp4

**Comment by rolisanchez** [comment]
Submitted PR #1100 with this fix :)

**Comment by saraolson** [comment]
@rolisanchez that looks like what we wanted :D Thank you again! Do you have a Habitica account youd like us to credit your PRs to?

**Comment by rolisanchez** [comment]
@saraolson Sure, my Habitica user id is ccf1ce82-1e91-4dd1-9b17-aa4fc4c4f2f2
