### ISSUE TITLE
Cannot rearrange sub-tasks

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitrpg-ios#1077]
I have been able to reproduce this issue - Beth

"Please describe the bug you encountered:

Thank you for fixing the bug that was plaguing me (and I assume other users).   However, since the update, I can now no longer rearrange sub tasks.  Is that on purpose?   Or will that feature come back?

The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
iOS Version: 14.8
Device: iPhone 12
App Version: 3.4.1 (624)
User ID: a001a907-6b2f-41ce-a5bd-b1cd3ba8cd7b
Level: 187
Class: mage
Is in Inn: false
Uses Costume: true
Custom Day Start: 2"

**Comment by saraolson** [comment]
these should have the lil grippy icon on the right side and be able to be dragged and dropped
<img width="396" alt="Screen Shot 2021-09-21 at 2 06 10 PM" src="https://user-images.githubusercontent.com/12453119/134224188-3d0bf013-941d-4f3a-8244-54720636c961.png">
