### ISSUE TITLE
Search on task screen takes over top bar with no way to dismiss it

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#1083]
Ideally there would be a 'Done' or 'x' button on the right side of the search that dismisses the bar and clears the search. Dismissing the kb shouldn't clear it, as you may have entered a search term then want to dismiss the kb to scroll the screen. User just expected dismissing the keyboard to clear it because there was no other apparent way.

User submitted a report with a video from their iPad. To recreate:

1. Open a task screen
2. Tap the search button
4. Search stays in the top bar and you can't create a task or access filters
5. Even switching task types, when you go back to the original type the search bar is still up

**Comment by juanj** [comment]
Note that this is only an issue when you dismiss the keyboard without typing anything in the search bar. When there is text in the search bar, an "x" button is shown to the right, and tapping it clears the field and opens the keyboard again, showing the "Cancel" button.

I think the solution here will be to hide the search bar when the keyboard is dismissed and the search text is empty.

**Comment by saraolson** [comment]
@juanj thanks for testing that! we'll test out your solution and see how it feels.

**Comment by saraolson** [comment]
@juanj alrighty so I was able to test this a bit more thoroughly. everything works as intended on iphone, but on iPad the search bar doesn't have a 'Cancel' button in the right corner and the empty search bar stays up when you press the button to dismiss the keyboard in the bottom corner. the behavior is better though, as the empty search bar will go away if you start scrolling now. would still prefer it dismiss itself along with the keyboard though. (my ipad is ios 14.7.1)
![image](https://user-images.githubusercontent.com/12453119/138753205-2e2451a7-3be0-4581-97f3-9cd33207ac83.png)

![Image from iOS (114)](https://user-images.githubusercontent.com/12453119/138753027-c56301ae-2bec-419d-a95f-d97248e15664.png)
