### ISSUE TITLE
Change 'next checkin' string to be more accurate

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#1086]
> The iOS app now reports checkins and checkin prizes, which I love.  But the checkin message seems wrong.  I’m at 323 checkins and the message says something like “you receive your next prize in 340 checkins”.  But it seems like it should either say “… at 340 checkins” or “… in 17 checkins.”  (I like “in 17 checkins” better.)

I would agree with them that doing the math and telling them how many checkins they need is the best option ie '..in 17 check ins' when then next prize is on checkin 340

**Comment by talpert022** [comment]
I can have a go at this issue!

**Comment by saraolson** [comment]
@talpert022 i'll mark this issue as in progress for you then!
