### ISSUE TITLE
Cannot add line breaks or press "return" in Notes field on tasks

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitrpg-ios#1089]
I was able to replicate- everything just displays as a single line, cursor is not visible, hitting "return" does nothing. - Beth

User report: 

"Hello! I noticed in the description box for tasks/habits line breaks don’t occur anymore. This has made reading and navigating many of my tasks very difficult. Would love to see this fixed, as everything was perfect before the update.
Thanks! :)

The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
iOS Version: 14.7.1
Device: iPhone 11
App Version: 3.4.2 (631)
User ID: 3d3dd865-5a98-4768-9306-ee60099a044f
Level: 67
Class: warrior
Is in Inn: false
Uses Costume: true
Custom Day Start: 0"

**Comment by phillipthelen** [comment]
See #1092
