### ISSUE TITLE
Top bar is white when creating a new task in iOS15

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#1094]
Whenever i try to create a new task the top bar is white. If i leave the app runnin in the background for a few minutes then unlock my phone and come back to it, the top bar shows as expected. But then if i dismiss that screen and tap the + again, the bar is white once more.

**Comment by rolisanchez** [comment]
Wasn't able to reproduce this error on iOS 15.0.2 on an iPhone 11 Pro (Tried both Light and Dark mode)

**Comment by saraolson** [comment]
@rolisanchez the one thing i can remember doing before encountering this issue was opening the filter screen and saving a filter, which uses a similar structure as the task creation screen but has a white bar. Thought if that was the issue though, would have righted itself with a force close. Maybe try that and see if you can reproduce?
