### ISSUE TITLE
Habits Indexing Issue

### ISSUE THREAD

**Issue by creaturebytes** [HabitRPG/habitrpg-ios#1103]
> Please describe the bug you encountered: "it seems like you guys might have a bit of an indexing issues when loading your “habits” view controller. I see an issue >frequently where the 0 index of the habits tab is missing. What I mean by this is I have 5 items in my list and it will only show >from 1 to the end of the list, instead of starting at 0. The fix is to force quit the app and it appropriately loads the data source."

>The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
>iOS Version: 15.0.2
>Device: iPhone 12 Pro
>App Version: 3.4.2 (631)
>User ID: db80b0f6-162a-4b1f-8fd2-0c3ebecd371d
>Level: 16
>Class: warrior
>Is in Inn: false
>Uses Costume: false
>Custom Day Start: 0

**Comment by saraolson** [comment]
think we fixed this when working on drag and drop improvements
