### ISSUE TITLE
Difficult to edit Daily repeat interval

### ISSUE THREAD

**Issue by creaturebytes** [HabitRPG/habitrpg-ios#1110]
>Hi,
>I can’t change the start date of my dailys and also not change if I want it every 4,5 or 6 day/months etc.

>The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
>iOS Version: 15.0.2
>Device: iPhone 12 mini
>App Version: 3.4.2 (631)
>User ID: 5985c426-72b1-4ded-9f91-8cabcce310a2
>Level: 49
>Class: mage
>Is in Inn: false
>Uses Costume: true
>Custom Day Start: 0

**Comment by saraolson** [comment]
i wasn't able to reproduce any issue in the current version of habitica or the beta that would prevent setting due date, but did have trouble editing the repeat interval

**Comment by saraolson** [comment]
the inability to edit start date was related to an accessibility feature that highlights button shapes. we've already fixed that in 3.4.3 so just need to fix the issue with editing the repeat interval number
