### ISSUE TITLE
Incorrect scaling in messages

### ISSUE THREAD

**Issue by vstkl** [HabitRPG/habitrpg-ios#1114]
When sending a new message, the scaling is incorrect and almost too small to read

Send message to other user who is not in your party

**Expected behavior**
Should use different factor for scaling

**Smartphone (please complete the following information):**
 - Device: iPhone8
 - OS: iOS15.1
 - App Version: [e.g. 2.2]
 - Habitica Username: negathiev

I might look into it, since I know a bit of Swift, I assume problem might be just wrong scaling parameter in css or it's derivative.

**Comment by saraolson** [comment]
@cxsmxx if you'd like to investigate this, you're welcome to! even if you discover the issue and don't have time to fix yourself, pointing out what needs to change is still helpful

**Comment by saraolson** [comment]
this seems to be fixed when we changed the flow for sending new messages through profile. gonna close it up unless someone encounters it again.
