### ISSUE TITLE
Quest Invite Notification Not Clearing

### ISSUE THREAD

**Issue by creaturebytes** [HabitRPG/habitrpg-ios#1118]
>The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
>iOS Version: 14.4.1
>Device: iPhone SE (2nd generation)
>App Version: 3.4.2 (631)
>User ID: 0d43113c-79f8-4e8a-8df3-2026282a748d
>Level: 131
>Class: healer
>Is in Inn: false
>Uses Costume: true
>Custom Day Start: 0
>Please describe the bug you encountered:
>Over the past few days, I have noticed a bug in which when I join a quest the notification still stays in my inbox inviting me to join. >So even after I accept and my name is on the quest roster, the notification remains.
> I have tried hitting accept (it says I missed the quest even though I did not), I’ve tried hitting decline (nothing happens) and I’ve >tried hitting clear all notifications (nothing happens). I also cleared my cache and everything as suggested on the Bug page.

**Comment by rilygreat** [comment]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 14.6
> Device: iPhone 7
> App Version: 3.5.4 (694)
> User ID: 983fedf2-405e-46f6-b608-c23ccc7ffd28
> Level: 29
> Class: healer
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> 
> Please describe the bug you encountered:
> Hi! I have two odd bugs to report. [...] The second bug I keep getting is a constant notification to join a quest for my party that already started. I’ve hit accept, decline, and dismiss a bunch of times but every time I clear it out it keeps popping back up. I even tried clearing my cache or restarting my phone but it still pops up.

**Comment by Alys** [comment]
These may be from server-side problems (rather than app bugs) where a set of database updates need to be made but not all of them succeed, with database transactions being a solution. For example https://github.com/HabitRPG/habitica/issues/10210 and also https://github.com/HabitRPG/habitica/issues/10275 (less relevant but similar).

**Comment by saraolson** [comment]
gonna close this due to the fact it is likely a server side issue
