### ISSUE TITLE
Distorted images in iOS 15 

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitrpg-ios#1120]
**Describe the bug**
User email:
"After installing your latest update, I found that every image I had painstakingly edited and sized for my dailies and habits was suddenly huge in the app  and distorted."

**Expected behavior**
Images will appear at a correct size and aspect ratio.

**Screenshots**
Distorted image:
![distorted-image](https://user-images.githubusercontent.com/78037386/145635674-90e09c48-026d-433e-b9e0-b8d56ab0b097.jpg)

Correct image:
![correct-image](https://user-images.githubusercontent.com/78037386/145635716-dedabad0-062d-43a6-8f18-2a501be72926.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: iOS15.1
 - App Version: 3.4.4 (649)

**Comment by saraolson** [comment]
> Hi, really love the app, but with the latest update, the pictures I put in markdown like ![](picture.png) always encompass a really large space, and before the update they were nice in size and could be configurable in the link. Now they always resort to filling in half the screen. 
<img width="663" alt="Screen Shot 2022-01-24 at 9 44 39 AM" src="https://user-images.githubusercontent.com/12453119/150804361-642da859-74f7-46b9-bdd8-4cce59ce92c8.png">
