### ISSUE TITLE
App crashing on iOS 13.6

### ISSUE THREAD

**Issue by creaturebytes** [HabitRPG/habitrpg-ios#1125]
>iOS Version: 13.7
>Device: iPhone 6s
>App Version: 3.4.4 (649)
>User ID: 8b19e1a8-ae33-43d3-9213-64a40182c951
>Level: 39
>Class: rogue
>Is in Inn: false
>Uses Costume: false
>Custom Day Start: 4
>Please describe the bug you encountered:
>
>"I cannot create new tasks for my categories - habits, dailies, to do’s. Anytime I try to make a new task the app force quits. This has been happening for some weeks now despite attempts to sync, quit, login/out, offload, uninstall, delete, etc."

**Comment by saraolson** [comment]
Report of app crashing when trying to add dailies or todo’s on ios version 13.6.1 iPhone SE too

**Comment by creaturebytes** [comment]
Recent user reporting same/similar issue:
>iOS Version: 13.7
>Device: iPhone 7
>App Version: 3.4.6 (656)
>User ID: d8d6b8f6-9f62-4ab9-8a5c-81d11142b14b
>Level: 2
>Class: warrior
>Is in Inn: false
>Uses Costume: false
>Custom Day Start: 0
>Details: "+ button at the upper right corner crashes the app all the time
iOS 13.7 (17H35)"

**Comment by saraolson** [comment]
had a report of this happening again, iOS 3.6. person just installed from the app store today
