### ISSUE TITLE
App Crashes on iOS 13.7

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitrpg-ios#1127]
**Describe the crash**
from user:
I cannot create new tasks for my categories - habits, dailies, to do’s. Anytime I try to make a new task the app force quits. This has been happening for some weeks now despite attempts to sync, quit, login/out, offload, uninstall, delete, etc. 

**Smartphone (please complete the following information):**
 - Device: iPhone 6s
 - OS: 13.7
 - App Version: 3.4.4 (649)
 - UUID: 8b19e1a8-ae33-43d3-9213-64a40182c951 

**Additional context**

**Comment by phillipthelen** [comment]
This is the same issue as #1125
