### ISSUE TITLE
Add 'Manually Start New Day' button in Settings if no cron in last 24h

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#1139]
This is a plan B solution to cron not running that we'd like to try out. The idea being someone that opens the app after their day resets, and cron doesn't run, will have the option of tapping this button to force it to run. The button should be by clear cache/reload content.

The cron script is complicated and despite our best efforts to make it as reliable as possible, still encounters issues that prevents the main use case of Habitica, completing tasks. Hopefully, this will offer a failsafe for people to use in those situations.

**Comment by aprilspace** [comment]
its almost 2024 and still no force new cron function available -_-

**Comment by aprilspace** [comment]
it’s so inconvenient when the start of a new day is already delayed, but one day you want to start things earlier because it’s necessary, but you can’t, because... the new day has not yet come and you are just sitting and don’t know what to do in the morning. That's just terrible
