### ISSUE TITLE
Tapping a Positive Habit Results in a Different Habit Reacting

### ISSUE THREAD

**Issue by creaturebytes** [HabitRPG/habitrpg-ios#1140]
>The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
>iOS Version: 15.1
>Device: iPhone 8 Plus
>App Version: 3.4.4 (649)
>User ID: 7c94e21b-8ff2-44a7-a5f1-cfdef807a5f5
>Level: 32
>Class: mage
>Is in Inn: false
>Uses Costume: true
>Custom Day Start: 0
>Please describe the bug you encountered:
>"When pressing “+” on a habit, the second habit up from it flashes instead of the habit i clicked. E.g. I have a list of habits that contains:
>+ 30min knitting
>+ ….
>+ drink water
>
> When I click the plus on drink water, 30min knitting flashes, but the counter etc seems to work correctly and increment for “drink water”

**Comment by aragos** [comment]
I see this too occasionally, with either the previous or next-previous item reacting. I have not yet found some pattern between when the reaction happens on the correct item or one of the others.

**Comment by rilygreat** [comment]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 15.4.1
> Device: iPhone SE (2nd generation)
> App Version: 3.5.4 (694)
> User ID: 3b20ac86-8b1c-4c06-8d04-de5bcf31b0e6
> Level: 11
> Class: rogue
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 5
> 
> Please describe the bug you encountered:
> 
> Hi my username is nick2929.
> 
> When I push the + button of habbit, another task are pushed at the same time and get a count.

**Comment by saraolson** [comment]
gonna close this as i believe its the same issue as #1192, but that one has some more info included
