### ISSUE TITLE
Text Wrap Issue in Checklists

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitrpg-ios#1147]
I use Habitica on desktop occasionally, but I primarily use the iOS app. My app is updated to the latest version, I tried clearing the cache and reloading content, and I have closed and reopened the app to try to resolve the issue.

When I make an entry on a To-Do task checklist, the text wrapping does not seem to work anymore. Meaning, if I type an entry that goes past the screen, it is still accepting the words I’m typing, but it does not wrap below to a new “line” in the text box so that I can see it. It stays this way even when I click to expand the checklist on the main to-do screen. See images below for examples:

Before this attempt, it was still just staying on one line even on the main To-Do screen - tis time, it did try to make two lines, but still cut off the rest of the sentence.

It is difficult to type on the checklist editing screen since I cannot see the rest of the line as I type.

I am able to use the arrow keys on a desktop computer to scroll over and see everything if needed, but I cannot do that on my phone when using the iOS app.

Is there a way to fix this so that it makes a new “line” in the same text entry box for that one checklist item and the texts auto-adjusts itself while I’m editing so that I can see it?

Thank you!

The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
iOS Version: 15.3.1
Device: iPhone X
App Version: 3.4.8 (701)
User ID: da4a7341-9631-4516-94e3-18df442c9941
Level: 98
Class: healer
Is in Inn: false
Uses Costume: false
Custom Day Start: 0

**Comment by rilygreat** [comment]
got another report related to this:

> Please describe the bug you encountered:
> 
> Can’t see checkboxes on checklists. Only have option to delete lines. See attached screenshot.
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 15.5
> Device: iPhone 12 mini
> App Version: 3.5.4 (694)
> User ID: df343c84-debd-41ec-82fd-c72096926923
> Level: 27
> Class: healer
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 1

![image0](https://user-images.githubusercontent.com/102926641/171773479-ed5bdfe1-7249-4f1a-a5ca-50e0b4b49d2a.png)

**Comment by rilygreat** [comment]
> Please describe the bug you encountered:
>
> When adding sub tasks to a ToDo, text didn’t wouldn’t recognize Return(Enter) button to make a new space. The result was a long line of text. 
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 15.5
> Device: iPhone XS
> App Version: 3.5.4 (694)
> User ID: 3c79327f-8241-4ef6-904c-5c2129bddd60
> Level: 39
> Class: healer
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0

![image0](https://user-images.githubusercontent.com/102926641/174126765-83254fd5-be8c-4a02-9713-44456b6b22ed.png)

**Comment by tjb** [comment]
I am no longer seeing this issue. @saraolson how do we reconfirm if this bug is still current or not? should you be tagged?

**Comment by saraolson** [comment]
this does seem to be fixed! will close unless we find a specific way to reproduce it again
