### ISSUE TITLE
Implement Custom Day Start confirmation toast

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#1154]
After changing CDS, show a confirmation toast that tells them the next time their cron will run: 

‘Next day reset: 03/01 @ 6:00 AM’
 
 This may stop some confusion when people change the time shortly after their day already reset. 
 
Web have a lengthier version of this, but I don't want to implement a full modal to confirm the change, just want a little green toast. Web's text: 'Are you sure you want to change your Custom Day Start time? Your Dailies will next reset the first time you use Habitica after 03/01/2022 @ 6:00 am. Make sure you have completed your Dailies before then!'

**Comment by mars-schmutz** [comment]
Would a UIAlertController item with only an "OK" option work, or should it be less intrusive like an Android-style toast?

**Comment by saraolson** [comment]
we would want the toast to mimic our toasts that are a green pill shape, like the ones you get when you complete a task
