### ISSUE TITLE
Widgets not working after iOS 15.4 update

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitrpg-ios#1160]
**Describe the bug**
The app works fine, but the Habitca widgets you can place on your Home Screen don’t appear to be working after the iOS 15.4 update. It still takes you to the app, but shows a somewhat blank screen. I tried to troubleshoot as much as possible. I restarted my phone. Deleted the app and redownloaded.

**To Reproduce**
I was not able to duplicate this.

**Expected behavior**
Widgets should take you to an active Habitica screen

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: 15.4
 - App Version: 3.5 (710)
 - Habitica UUID: 8749bf35-20be-48f2-966f-730df57ae96a

**Comment by saraolson** [comment]
already got this: https://github.com/HabitRPG/habitica-ios/issues/1156
