### ISSUE TITLE
Daily toast says "in N Check-Ins", should use "at" instead

### ISSUE THREAD

**Issue by aragos** [HabitRPG/habitrpg-ios#1161]
I noticed that the message for me stays the same day after day (until I reach a prize), but uses "in" rather than "at".

The current repeating message (for example `Next prize in 35 Check-Ins`) suggests that the prize will occur at today plus 35 days where it actually means to say, at the 35th total check in. It would be more accurate to say `Next prize at 35 Check-Ins`. 

I see that we already have [logic](https://github.com/HabitRPG/habitica-ios/blob/a919daf6f78c16c865103d5365c5cca2621d08f5/HabitRPG/Utilities/NotificationManager.swift#L174) and [messages](https://github.com/HabitRPG/habitica-ios/blob/a919daf6f78c16c865103d5365c5cca2621d08f5/HabitRPG/Strings/Base.lproj/Mainstrings.strings#L875) to deal with this but apparently there is a bug of some sort here.

**Comment by saraolson** [comment]
this should be fixed in the latest 3.5 build thats being released where it accurately does the math to count down the days.
