### ISSUE TITLE
Broken old seasonal gear unpurchasable

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1172]
> I died and lost the snowflake crown 2013-2014 limited healer gear. Unfortunately, it is not available for repurchase even though I am the correct class and have enough gold. 
> 
> Please see attached screenshot for detail:
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 15.4.1
> Device: iPhone 11 Pro Max
> App Version: 3.5.1 (674)
> User ID: 1fa736d9-f0cb-4dc5-b325-0126ba9309e6
> Level: 106
> Class: healer
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 2
![image0](https://user-images.githubusercontent.com/102926641/161450419-ead73b75-60a0-4797-bb92-09b4b97c4986.png)

**Comment by saraolson** [comment]
fixed in 3.10
