### ISSUE TITLE
filtering to a tag doesn't show tagged tasks

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1181]
> I tried to use the filters today to show only school related tasks, and even though I do have tasks with that tag, it made all of them disappear while the filter was enabled. The tasks reappeared when I cleared the filters. The filters did work the first time I used them, but no longer do. I have tried several times and also completely closed and restarted the app. This is not a huge deal to me but it is an inconvenience. 
> 
> My username is @etherealhavoc.

**Comment by saraolson** [comment]
user responded back that its working now, going to close until we hear more reports. may have just been a server issue or user error
