### ISSUE TITLE
Images sometimes overlay user avatars

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitrpg-ios#1188]
**Describe the bug**
From admin email:
> When I went to @redmyst’s profile a picture from the inspiration station guild started appearing randomly. I’ve seen this with other pictures and other profiles as well. I recorded the glitch, here’s the video. It’s not gamebreaking but I thought it was weird.

**To Reproduce**
1. Join [Inspiration Station Guild](https://habitica.com/groups/guild/d89db12b-5ec2-41f1-90d7-62bfbd8694b5)
2. Open iOS app and navigate to guild details page
3. Select @redmyst's profile
4. Observe image overlaying their avatar (it is specifically [this one](https://trello-attachments.s3.amazonaws.com/5fa959d6158dac31f68515e1/380x380/26853bd9f674c4b88b1837c174bb2d81/3_Resized.png)).

**Expected behavior**
Images used from guild details will not overlay user avatars.

**Screenshots**
https://user-images.githubusercontent.com/78037386/166715729-af3d15d9-6b16-4c64-b4d1-2f7f969c3049.mov

**Smartphone (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: 15.4.1
 - App Version: 3.5.2 (676)
 - Habitica UUID: 57a4d6cb-2f03-407b-80de-4e7a030c9691

**Comment by saraolson** [comment]
https://github.com/user-attachments/assets/7856c300-3768-4580-af5c-9da7669b51f0

**Comment by saraolson** [comment]
this may be related to the issue found in #1208 

we're going to close this issue in favor of that one, as that one focuses on parties.
