### ISSUE TITLE
typing @ and apostrophe in chat crashes app

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1189]
> iOS Version: 15.1.1
> Device: iPhone 12 mini
> User ID: bd2b73d4-79eb-4be3-839d-980e0d664edf

they originally reported issues with the emoji keyboard but after updating to 3.5.3 they reported while the emoji issue is fixed, now the app crashes when typing a message in chat.

asked for any additional info and they provided this:

> from testing a few things it seems to happen when I have typed @ and then later in the message type an apostrophe (either typing it myself or when autocorrect adds it to a contraction). I don't have to have @'d an actual user. If I type @ and then move the cursor before the @, I can type an apostrophe without it crashing.  
> 
> It only happens with apostrophes, other punctuation is fine. It seems to be the same in party chat, guild chat, and DMs, but doesn't happen when typing in a task name/notes.

**Comment by saraolson** [comment]
assigning to 3.5.4 to investigate, if its tricky we'll bump to 3.6
