### ISSUE TITLE
User input is lost when recovering internet connection

### ISSUE THREAD

**Issue by sofiaalvarezlopez** [HabitRPG/habitrpg-ios#1195]
**Describe the bug**
Habits/To do's/dailies created/checked without an internet connection are lost when the internet connection is recovered and the view is refreshed.

**To Reproduce**
1. Turn off the internet connection.
2. Create a habit/to do/daily.
3. Turn on the internet connection.
4. Refresh the view.
5. The previously created to do/habit/daily is lost.

**Expected behavior**
The app should persist the user's actions without an internet connection when recovering connectivity.

**Screenshots**
<img width="441" alt="Captura de Pantalla 2022-05-21 a la(s) 12 49 12 a m" src="https://user-images.githubusercontent.com/41558363/169637718-0add68cf-34fc-425e-9c6c-d678bf6fb3fc.png">

**Smartphone (please complete the following information):**
 - Device: iPhone11
 - OS: iOS15.4.1
 - App Version: 3.5.2
 - Habitica Username:  sofiaalvarezlopez

**Comment by EricMiddelhove** [comment]
I could reproduce it and will look into this :)
