### ISSUE TITLE
able to switch class without any gems

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1197]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 15.1
> Device: iPad (7th generation)
> App Version: 3.5.3 (683)
> User ID: ff6cdc19-69c5-4d15-9449-c8d91cdd5051
> Level: 15
> Class: mage
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> 
> I was goofing around and I tried to switch my class without any gems and it worked. I tried to switch back to my original class and I was able to without gems.

after testing on an account w/o any gems, the app will ask you if you'd like to change classes and ask for confirmation. then it will show the interface that allows you to pick a class even though you don't have any gems. there is an error that says 'not enough gems' and selecting a class seems to stall out but the interface shouldn't show if you don't have enough gems.

**Comment by EricMiddelhove** [comment]
I will look into this

**Comment by EricMiddelhove** [comment]
@saraolson I was able to reproduce this bug and I am able to fix this. I have one quick question: What should happen when a user has not enough gems to switch the class? Is displaying the same Popup but only displaying a cancel button ok?

**Comment by saraolson** [comment]
@EricMiddelhove we can show the confirmation pop-up, but then if they try to confirm we should show our usual 'you don't have enough gems' pop-up instead of letting them see the class selection screen.
