### ISSUE TITLE
challenge search bar obstructs app bar

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1198]
user reported they struggled to tap the back button bc the search bar was stuck in place. they mentioned it happens after viewing challenges. they included screenshots of it happening in multiple sections of the app including tavern and pets.

> It seems going to the Challenges tab and hitting Search was what triggered it. I just closed and restarted the app and that seems to be exactly what happened after doing those two things. Even after closing the search bar on challenges, the search tab remains for other sections like Party and Equipment and cannot be closed with Close. 

![IMG_0386](https://user-images.githubusercontent.com/102926641/171059715-e57837d3-8312-408e-b6d9-c2a78551e518.jpg)

**Comment by EricMiddelhove** [comment]
I was able to reproduce this issue and could look into fixing it if wanted :-)

**Comment by saraolson** [comment]
@EricMiddelhove thanks for your interest in this issue! we'll review your fix when we're working on the iOS update next. Right now, staff are busy on the latest android update so it may take some time. After reviewing and testing, we'll add this contribution to your Habitica profile!
