### ISSUE TITLE
mark a task complete from reminder (through force touch) not working

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1205]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 15.5
> Device: iPhone14,2
> App Version: 3.5.4 (694)
> User ID: 752def0c-84fa-4ec3-ab92-f39d8718f4a6
> Level: 27
> Class: rogue
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> 
> Using force touch on a notification to mark a task complete does not mark the task as complete in the app for me.

**Comment by saraolson** [comment]
i was able to complete a todo and daily with the longpress actions on the reminder, so this seems to have been resolved since the original report. Gonna close for now.
