### ISSUE TITLE
Class-locked seasonal gear should show a purple circle with a lock icon to signify both states

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitrpg-ios#1206]
I can confirm this is what I see as well, user report and screenshot below. -Beffymaroo

Please describe the bug you encountered:

Hi there,
I’m not able to buy seasonal items for gold despite having more than enough (screenshot included below).  Am I missing something, or is this a bug?

Thank you!
Jade
![image0](https://user-images.githubusercontent.com/9218855/177390702-e0971f8d-bc87-4c67-8f84-1bebe497bb9a.png)

The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
iOS Version: 15.5
Device: iPhone14,2
App Version: 3.5.4 (694)
User ID: 4e5edce7-f9c1-4878-a668-77ea210b783e
Level: 102
Class: warrior
Is in Inn: false
Uses Costume: true
Custom Day Start: 0

**Comment by saraolson** [comment]
this is likely because the time limited seasonal icon takes precedence over the lock, and they share the same space.

to fix this, we could create a purple lock icon for when it is both limited time seasonal and locked.
