### ISSUE TITLE
Daily reminder to remember your tasks is not being sent

### ISSUE THREAD

**Issue by cvarrichio** [HabitRPG/habitrpg-ios#1209]
This issue still persists for me.  Daily reminder is on, notifications are enabled in IOS, but I do not receive a daily notification.

iOS Version: 15.5
Device: iPhone 12 Mini
App Version: 3.5.4

_Originally posted by @cvarrichio in https://github.com/HabitRPG/habitica-ios/issues/1062#issuecomment-1186249131_

**Comment by saraolson** [comment]
@cvarrichio task reminders are a little different from the daily reminder that you can set in your Settings. Task reminders are set on each individual task in that task's edit screen. 

Which ones aren't going through for you? Or do both types of reminders not work?

**Comment by cvarrichio** [comment]
Task reminders work fine.  I have never received a daily reminder, however,
even though that is selected in the options.

**Comment by saraolson** [comment]
We haven't received any new reports of this, and my account has been receiving the daily reminders each day without issue. Going to assume that this was fixed then, and close this issue until more reports come in.
