### ISSUE TITLE
text bar moves up with each line of text when replying in guild chat

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1213]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 15.5
> Device: iPhone SE (2nd generation)
> App Version: 3.5.4 (694)
> User ID: 18dad166-88df-4739-bb5f-b65bf41c5836
> Level: 89
> Class: mage
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 2
> 
> Please describe the bug you encountered:
> 
> While trying to post in a guild forum, responding to someone, each time I typed another line of text, the whole typing area (with the “send” button) would shift upwards by about an extra half a line. Before I was done, I could no longer see what I was typing, the “send” button was out of view, and the whole page was blank. I had no way to post what I typed. I couldn’t scroll up, couldn’t highlight text, couldn’t do anything but hit the button at the top to view the guild information.

**Comment by saraolson** [comment]
seems like the text area is supposed to expand with each line, but what actually happens is the bar moves up without actually expanding

**Comment by CuriousMagpie** [comment]
> iOS Version: 15.6
> Device: iPhone SE (2nd generation)
> App Version: 3.6.3 (781)
> User ID: 267135db-e7f8-42d9-bed2-f84b4261b64e
> Level: 95
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 3
> 
> don’t know if you’re aware of this bug, but it’s been around for a long while now. There is this gap between the keyboard and the text box in guild/party chats and it’s quite distracting. Sometimes the text box jumps around a bit when scrolling

![image0](https://user-images.githubusercontent.com/78037386/203605239-ea22d9be-72fc-40e4-b4bc-ff131d72230a.jpeg)

**Comment by rilygreat** [comment]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 16.1.1
> Device: iPhone 8
> App Version: 3.6.4 (797)
> User ID: 68ce1251-d4a8-4ed6-ada4-f9ebea261d1e
> Level: 107
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 6
> 
> Please describe the bug you encountered:
> 
> When I try to post a long message in my party, it slowly moves off the screen as I type, until eventually all I see is a black screen. The “send” button scrolls off the screen as well, so I can’t send the message. I am not able to scroll up or down. This means that making posts of more than a couple sentences is impossible on the app.

**Comment by saraolson** [comment]
from my testing, typing long messages works well now. we replaced the chat message library so that may have fixed the problem. pasting long messages can still cause issues but we're tracking that in #1249
