### ISSUE TITLE
App constantly shows "the network connection was lost" message

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitrpg-ios#1218]
**Describe the bug**
>I keep getting an error stating that network connection was lost. I have tried clearing the cache and reloading the content. It doesn't help.  

**To Reproduce**
Do anything in the iOS app--it is a persistent issue and there doesn't seem to be a pattern to it.

**Screenshots**
![Image](https://user-images.githubusercontent.com/78037386/184396311-91412486-be81-476e-82a3-e929d8f13dac.jpeg)

**Smartphone (please complete the following information):**
iOS Version: 15.6
Device: iPhone XR
App Version: 3.5.4 (694)
User ID: b046b27d-1c59-4250-bf5a-2b3cc27fb2ac
Level: 154
Class: healer
Is in Inn: false
Uses Costume: true
Custom Day Start: 0

**Additional context**
I've been having this problem for quite some time as well. It doesn't seem to cause any problems with the operation of the app, but it is really annoying.

**Comment by rilygreat** [comment]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 16.2
> Device: iPhone 12
> App Version: 3.6.6 (816)
> User ID: 4ab0017f-06a7-463e-8927-7ee2ed7085e7
> Level: 89
> Class: healer
> Is in Inn: true
> Uses Costume: true
> Custom Day Start: 0
> 
> Please describe the bug you encountered:
> Items edited/created with mobile data not syncing. Internet connection using other apps eg Youtube is ok. [...] the issue is when creating todos/making edits while using mobile data, I keep on getting an error about there being no connection etc when I clearly have mobile data OK on my phone.
> 
> As such I can't create todos when I'm using my phone's mobile data as they do get "created" locally, but they don't sync even if I pull the page to refresh. In fact, the tasks "created" get "deleted" before they even sync.

they said it was a constant thing and added steps to replicate:

> 1. Turn on mobile data + turn off wifi
> 2. Create a todo in the Habitica app
> 3. Wait for it to refresh on its own/pull down the page to force a refresh
> 4. The todo gets deleted with a red pop up at the bottom area of the app that says "The network connection was lost."

**Comment by saraolson** [comment]
We've made some improvements to server stability that have vastly improved the reliability of server calls. Going to close this for now. If more reports come in, we can reopen.
