### ISSUE TITLE
Update sub benefit screen design

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#1222]
We have new designs to show the current sub benefits, including subscription credit and how to activate it, that looks like this:
<img width="388" alt="Screen Shot 2022-08-16 at 1 42 28 PM" src="https://user-images.githubusercontent.com/12453119/184981283-28946ae8-74d2-4f69-87cc-b1c1392bb665.png">
(needs ios specific design still)

**Comment by InsanelyHarsh** [comment]
I would like to take on this task.

**Comment by saraolson** [comment]
@InsanelyHarsh thanks for your interest, but our internal team is taking this on :) You can filter for issues we're looking for contributor help on by looking at the 'Help wanted' label
