### ISSUE TITLE
Share button when hatching a pet does nothing

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#1223]
The share button should bring up a menu that lets you select where you'd like to share to, whether that be discord, twitter, messenger, etc. The share should include an image of the pet and a pre-typed line (this should exist already).

> When hatching a new pet, clicking “share” doesn’t do anything (literally nothing happens, no menu prompts etc)
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 15.6
> Device: iPhone14,3
> App Version: 3.5.4 (694)
> User ID: ca50b64b-39e2-45a0-89d5-0475632453d4
> Level: 108
> Class: mage
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0

**Comment by dan-e-miller** [comment]
Hello!

I would like to work on this issue. My Habitica user is @Miller4147

Thanks

**Comment by dan-e-miller** [comment]
My guess is this is an issue of presenting a UIViewController while another is already presented. I would check the dismiss logic to ensure the hatching confirmation is completely dismissed before the share sheet is being presented.

**Comment by saraolson** [comment]
@dan-e-miller feel free to work on this! i'll mark is as in progress for you.
