### ISSUE TITLE
RYA Showed multiple times in one day, but only cronned once with no cron failed events

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitrpg-ios#1224]
User report **(additional information appended to email in admin)**

Please describe the bug you encountered:

My daily’s reset 3 times yesterday and I was confused so I skipped it the last time and lost all my streaks and half my health. I don’t really mind the streaks or health I’m just wondering if I messed up somehow or if it’s a game bug

The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
iOS Version: 16.0
Device: iPhone X
App Version: 3.5.4 (694)
User ID: 101e4183-a3d1-4b9c-8630-cde2740bc707
Level: 16
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 0

**Comment by saraolson** [comment]
looking at amplitude, they cronned at:
- Aug 17, 5:58 AM utc (Aug 16, 10:58 PM pdt their time): no hp loss
- Aug 17, 3:46 PM utc (Aug 17, 8:46 AM pdt their time): -9.92 hp loss
- Aug 18, 4:07 PM utc (Aug 18, 9:07 AM pdt): -1.64 hp loss

all of this seems normal with their day start. i don't see any cron failed events. my best guess is cron was failing, it kept showing them RYA, but not working?

**Comment by CuriousMagpie** [comment]
I've had the RYA pop up a few times on my phone when I'd checked everything off on my computer the evening before. Next time it happens and if I'm near a computer, I'll look up what happened in the db/amplitude. I haven't lost health, though!

**Comment by saraolson** [comment]
we made some changes to RYA that prevented it from stacking in 3.6, going to close this unless we hear the issue come up again
