### ISSUE TITLE
Leaving a Party/Guild will ask if you want to keep Challenge tasks even if you aren't part of any group Challenges

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#1235]
To reproduce:
1. Leave any Party or Guild
2. the app will ask about challenges even though you didn't interact with any

we should probably change the modal options to be clearer, need to do more testing to figure out the best way to do that

**Comment by tjb** [comment]
@saraolson Do we want the option to keep challenge if and only if we interacted with a challenge and if we did not interact with a challenge should we just make the popup be a confirmation that we are leaving the guild/party?

**Comment by saraolson** [comment]
after taking some time to review our options, for simplicity i think we're just going to warn them that they're in a challenge and instruct them where to go if they want to leave it. there's just too many options trying to handle leave party and leave challenge in the same modal (since you can leave challenge and keep tasks, leave challenge and delete tasks, or stay in the challenge).

this warning gives them a chance to back out and leave the challenge if they would like to before leaving the party/guild as well. 

for example, first modal is what you'd see if you're participating in a party challenge and attempt to leave the party, second modal is what you'd see if you aren't participating in any challenges and attempt to leave the party:

![Screen Shot 2023-04-20 at 9 49 48 AM](https://github.com/HabitRPG/habitica-ios/assets/12453119/a7a95faf-1bb6-4d6b-940d-ace5f0bc455d)

**Comment by saraolson** [comment]
after looking into this more, its a but more complicated than we'd like for now. in order to reduce the confusion caused by the current flow, we're going to opt to show one message to all people who attempt to leave a party. this message will mention the case of being in a party challenge so those that are participating get the info they need.

message will be:
**Are you sure you want to leave the Party?**
Leaving your Party will not remove you from any Party Challenges you are participating in.
[Leave Party]
[Cancel]
