### ISSUE TITLE
Smart App Banner incorrectly displaying for app user

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitrpg-ios#1238]
**Describe the bug**
When going to the About section, and clicking "News", a banner advertising the Habitica appears. This is called a [Smart App Banner](https://developer.apple.com/documentation/webkit/promoting_apps_with_smart_app_banners), and is intended for directing website visitors to the mobile version of an app. There are two versions that are intended to auto-detect; one if the app already is installed, and one if it isn't. I got the non-installed version, which is the incorrect one.

A bigger problem, though, is that this is not appropriate behavior. I'm already using the app, so I shouldn't be "redirected" again to it.

**To Reproduce**
- Select Settings > News
- The Smart App Banner appears at the top of the News post

**Expected behavior**
Users on the Habitica app shouldn't be redirected to this banner as they are already using the app.

I believe that this is likely because the app is embedding a web version of Bailey's news. A conditional, "mobile render" version should be added without the meta tag that triggers the Smart Banner, which looks something like 
```
<meta
 name="apple-itunes-app"
 content="app-id=myAppStoreID,
 app-argument=myURL">
```
**Screenshots**
![IMG_2727](https://user-images.githubusercontent.com/78037386/191057269-6de64e5d-5da0-4e64-ac9b-e51f29de9582.jpg)

**Smartphone (please complete the following information):**
iOS Version: 15.6
Device: iPad Air (3rd generation)
App Version: 3.5.5 (695)
User ID: 3886a1de-c1bb-487e-ac81-8f3565d0728b
Level: 75
Class: mage
Is in Inn: false
Uses Costume: true
Custom Day Start: 0

**Comment by saraolson** [comment]
we need to make this change on the web version, so closing here. i've recorded it on our internal issue tracking board.
