### ISSUE TITLE
Change button to 'Unblock' when you view actions of a user you've blocked

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#1244]
If you block a user from their profile then open the action menu again, the button is still labeled 'block'. it should become 'unblock'

**Comment by ghost** [comment]
I would like to try ? could you assign it to me

**Comment by saraolson** [comment]
@ankurwasnik sure! i've assigned it to you and marked the issue as in progress. just let us know if you have to drop it for any reason :)
