### ISSUE TITLE
tapping notification from utopify guild causes crash

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1250]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 15.6.1
> Device: iPhone 12 Pro Max
> App Version: 3.6 (744)
> User ID: 3fba9916-0c61-4f80-bde0-6d145aea68f0
> Level: 64
> Class: healer
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> 
> Please describe the bug you encountered:
> I have a notification from the guild “[utopify.org](http://utopify.org/)” - whenever I tap this notification the app consistently crashes. I can tap other notifications without any crashes/issues.

**Comment by saraolson** [comment]
fixed in 3.6.1, if issue persists after update can reopen
