### ISSUE TITLE
opening guilds from notif causes crash

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1251]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 15.6.1
> Device: iPhone14,4
> App Version: 3.6 (744)
> User ID: 0a69bb45-3c0c-42bf-9bc5-730a957783c9
> Level: 75
> Class: healer
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> 
> Please describe the bug you encountered:
> Having trouble with guilds. Habitica seems confused as to if I am in a guild or not, I am seeing the join guild button for guilds I am in, and sometimes opening the guilds will cause the game to crash

**Comment by rilygreat** [comment]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 16.0.2
> Device: iPhone 12 Pro
> App Version: 3.6.1 (746)
> User ID: aedcaec3-8d2e-408c-81f8-2e6418756a47
> Level: 101
> Class: mage
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 2
> 
> Please describe the bug you encountered:
> Hi! Over the last few weeks, my app has been crashing often when I attempt to check new posts in guilds. Sometimes i have to try 2 or 3 times before I can read them. I was hoping the update would fix the issue but it just happened again.

**Comment by rilygreat** [comment]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 16.1
> Device: iPhone 12
> App Version: 3.6.2 (752)
> User ID: 1dd3d826-53e5-4c78-89b0-03cb7ef54c9b
> Level: 10
> Class: rogue
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> 
> Please describe the bug you encountered:
> This has been happening consistently since I downloaded the app. When I go to my notifications and I click on any post that says “you have new messages in ____ guild”, the app crashes. However, then the next time it redirects me at least.

**Comment by CuriousMagpie** [comment]
> iOS Version: 16.0.3
> Device: iPhone 12 mini
> App Version: 3.6.2 (752)
> User ID: bd2b73d4-79eb-4be3-839d-980e0d664edf
> Level: 125
> Class: healer
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 2
> 
> The app frequently crashes when I click a notification from a guild. It usually works on the second try without crashing, but almost every time it crashes on the first try.
