### ISSUE TITLE
quest completion modal shows multiple times sometimes

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1257]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 16.0.3
> Device: iPhone 11
> App Version: 3.6.1 (746)
> User ID: 35c3fb6f-fb98-4bc3-b57a-ac01137d0847
> Level: 748
> Class: mage
> Is in Inn: true
> Uses Costume: true
> Custom Day Start: 6
> 
> Please describe the bug you encountered:
> 
> I just got the same quest completed notification 4 times in a span of ~20 minutes, while using Habitica on my phone. Including right in the middle of typing a message in one of my guilds.

**Comment by saraolson** [comment]
haven't been able to reproduce myself

**Comment by saraolson** [comment]
this was likely due to server issues not registering that the modal was seen+dismissed. we've made improvements to server reliability that likely resolved this.
