### ISSUE TITLE
Notifications remiders for dailies occur even when daily is complete.

### ISSUE THREAD

**Issue by BlakeTNC** [HabitRPG/habitrpg-ios#1258]
I just received a notification for a reminder alarm on a daily task, that I had already completed for the day. My intuition would be that if you complete a daily task before the time that is set in your reminder setting, then you should not receive a reminder notification. (I am using the IOS app.)

I don't know if this is expected behavior, so this issue is either a bug report, or a feature request. The feature would be the ability to "Skip reminders for completed dailies." This could either be a default behavior, or an optional app setting. This would be implemented by checking the completion status of the task at the time the reminder is triggered.

If a person has a lot of dailies, and relies on reminders, I can imagine that it would be very unproductive to receive unnecessary reminders for the dailies that you already completed that day.

**Comment by saraolson** [comment]
Unfortunately, we're unable to support this feature. We explored supporting it on Android and it was extremely unreliable and caused more problems than it solved. With the way we schedule reminders, this just isn't compatible.
