### ISSUE TITLE
Emojis in task name not rendering in widget

### ISSUE THREAD

**Issue by patriciatiffany** [HabitRPG/habitrpg-ios#1259]
Emojis used as part of task names don’t render in the widget. For example, in the widget, a daily would show up as “`:punch: Task Name`” instead of displaying the image of the emoji like in the app or on the website (“:punch: Task Name”).

(Using iPad OS15)

**Comment by tjb** [comment]
@saraolson tested on iPad Mini 6th running iOS15. Emoji shows!
![Screenshot 2023-05-25 at 10 15 17 PM](https://github.com/HabitRPG/habitica-ios/assets/3600122/395e0cd3-f13e-491a-9897-eda035f7001a)

**Comment by saraolson** [comment]
thanks for looking into this! i'll go ahead and close unless we can find a specific instance where it's still not working

**Comment by patriciatiffany** [comment]
This still does not work for me. @tjb , did you try other emojis other than the one in your screenshot, and did :punch: work for you?
