### ISSUE TITLE
Some users unable to complete the 'create a task' beginner objective

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#1263]
> unable to mark first beginners quest item done even tho i have created tasks. it crossed off the finish a task but not create even tho i’ve created several.
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 16.0
> Device: iPhone14,2
> App Version: 3.6.1 (746)
> User ID: f0a69821-e849-4828-8260-2ce6de66108a
> Level: 3
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0

two more accounts we've had this reported from:
6ad0968c-cf82-4dce-ba9d-4cd76794df59
91dbe2e4-839b-4508-acfb-e19a889cc452

i havent been able to reproduce yet

**Comment by saraolson** [comment]
another one:

> Hi,
> I can’t seem to complete my beginner objectives, as the create a task option never seems to finish regardless of what kind of tasks i’m making.
> 
> Thanks!
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 16.0.3
> Device: iPhone 11 Pro
> App Version: 3.6.2 (752)
> User ID: 80bd6acd-4178-4bf7-b4ee-ccba5c3eb9e7
> Level: 4
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0

**Comment by RichieYTL** [comment]
I just made this bug happen recently. There is a period of time at the very start where there are no prompts to do the objectives. I made a task immediately, my first action in the app. I got the achievement before the objectives came, locking me out of fulfilling the requirements.

**Comment by saraolson** [comment]
@RichieYTL thanks so much for those added details! that's very helpful to know.

**Comment by nateplusplus** [comment]
Hey! I am also having the same issue. I can’t recall if I experienced the same process as @RichieYTL but I did start adding habits right away.

Also, I deleted a habit early on, so that may be another variable to look into. Let me know if I can help any other way.

**Comment by saraolson** [comment]
this should be fixed in version 3.8
