### ISSUE TITLE
opening link from a challenge's to-do causes crash

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1267]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 15.7
> Device: iPhone14,4
> App Version: 3.6.2 (752)
> User ID: 97c8e106-12d0-4165-85f5-16897564f592
> Level: 4
> Class: warrior
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> 
> I joined a challenge (Lovecraftian Cleanup… I couldn’t resist), and one of the To Do’s has a link to join a party. I clicked it, and CRASH.

**Comment by CuriousMagpie** [comment]
The user has also reported that when tapping on checklist items in a task the app crashes.

**Comment by saraolson** [comment]
@CuriousMagpie opening a link in a challenge todo checklist? if its just tapping on a checklist, that crash should likely be a separate issue.

**Comment by juanj** [comment]
I would like to work on this issue

**Comment by saraolson** [comment]
@juanj thanks for taking this on! we'll review it when we're working on the next iOS update again :)
