### ISSUE TITLE
emojis not showing in guild description

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1272]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 16.1.1
> Device: iPhone 11
> App Version: 3.6.6 (816)
> User ID: 0ec77c8c-c260-4c46-9a17-a1bb402a9f16
> Level: 2
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> 
> Please describe the bug you encountered:
> Hi there! On the intro to the Life Hacks Guild, I noticed there’s text that looks like it’s code and there should be an image there instead? Not sure on the terminology but I’ve attached a screenshot!

![image0](https://user-images.githubusercontent.com/102926641/215865617-d6862aba-3eba-4cd4-9a0a-1d9d833f5485.png)

**Comment by tjb** [comment]
Fixed in #1290
