### ISSUE TITLE
unable to view "more details" on quest scrolls

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1273]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 16.3
> Device: iPhone14,4
> App Version: 3.6.6 (816)
> User ID: 007ef40c-db4b-47c6-bb28-842fe5eefe96
> Level: 80
> Class: mage
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 5
> 
> Please describe the bug you encountered:
> On mobile, when pressing the button for “More Details” on an owned quest scroll, it frequently does not respond and will not show the information and takes multiple presses over and over to actually show up.

**Comment by rilygreat** [comment]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 16.1.2
> Device: iPhone14,4
> App Version: 3.6.6 (816)
> User ID: 0a10befe-2ba0-4a4e-b798-76068521afad
> Level: 44
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> 
> Please describe the bug you encountered:
> The “show details” button under quests does not work. I click the button to get info and nothing ever happens :/ I have to access it on desktop to be able to see quest details. 
> 
> https://user-images.githubusercontent.com/102926641/217891644-464afd39-60c8-4e34-a73c-bf85d18d5ef6.mov

**Comment by tjb** [comment]
I have tested this issue on iOS 16 (simulator) with app version 3.7.1 and I am able to see the details of the quest. @rilygreat can you try updating to the latest app version and see if the issue persists?

**Comment by rilygreat** [comment]
looks like it's still an issue on version 3.7.2. tested it on an iPhone SE, iOS version 16.3. 

some quests have their descriptions cut off too, scrolling down further does nothing:
![IMG_1336](https://github.com/HabitRPG/habitica-ios/assets/102926641/56daa2a4-37a6-4936-bdc3-7dd698021758)
