### ISSUE TITLE
Accessing ‘Party’ creates crash

### ISSUE THREAD

**Issue by sundaresvani** [HabitRPG/habitrpg-ios#1275]
**Describe the crash**
What were you doing before the issue? Was there an error, did the app stall, or did it fully close?
trying to access ‘party’

**To Reproduce**
Can you reliably reproduce the crash? If so, list steps.
1- Open app, 
2- Navigate to ‘party’
[CRASH]
3- repeat as desired

**Screenshots/Video**

https://share.icloud.com/photos/0fa94iicrcfj9v3JAG2ygzGJA (this is a video of me holding my phone, opening habitica, navigating to party & it shutting down0

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] — both iphoneSE2nd Gen & IPad Air 4th gen
 - OS: [e.g. iOS8.1] 16.2 (iPhone) & 15.5 (iPad)
 - App Version: [e.g. 2.2]. 3.6.6(816) (iphone)  3.6.5(816) (iPad)
 - Habitica Username:  freeheart — note, also observed by party member @yoshilala

**Additional context**

**Comment by sundaresvani** [comment]
Checking in on this again in case I can support debuggig, it's still happening. I've tried uninstalling & reinstalling habitica as well as rebooting (of course).   I can successfully access "party" via browser, but not app.

**Comment by saraolson** [comment]
this should be fixed in the next update, the update just isnt released yet

**Comment by sundaresvani** [comment]
Ha! I was just about to ask… :-)

/|\
Śvani
 --
Śvani Grevemeyer
[SHVA-knee]
Pronoun: She
(510) 549-3733 x705
2124 Kittredge St. #54, (mailbox)
Berkeley CA 94704

**Comment by rilygreat** [comment]
this is still happening as of may 8th in version 3.7.2
