### ISSUE TITLE
unable to receive daily reminders when turning on mirroring notifications from iphone to apple watch

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1277]
user report:

> I’ve recently switched from an android phone to an Apple phone, and and now no matter what I do I can’t seem to get notifications to work for Habitica. I have all notifications turned on and I get notifications for everything else just fine. [...] It was for daily reminders. I found out more about the problem, it seems to be a bug related to my Apple Watch. If I turn off notification mirroring on my watch, I can get notifications on my phone. If I turn the notification mirroring back on, I stop getting notifications on both the watch and the phone.

**Comment by saraolson** [comment]
We aren't able to reproduce this, and we aren't really able to do much to control this.
