### ISSUE TITLE
unable to leave active quest, the leave button doesn't appear

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1278]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 16.3.1
> Device: iPad12,2
> App Version: 3.7 (850)
> User ID: 196603d4-4d79-4530-b686-bf4b2fe949f1
> Level: 14
> Class: healer
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 1
>
> Please describe the bug you encountered: 
> I am currently participating in Redicivate Part 2: Redicivate the Necromancer as a level 17 (now 14) healer and have repeatedly died to it, so I figured I would leave the quest to preserve my equipment and coins. However, there's one small issue. The "Leave" button does not work. When I click on it, it brings up both the prompt to force start the quest and then to leave the quest. Selecting yes on either results in the respective error messages "Not found." for leaving and "The quest has already started." for force starting. The quest was force started prior and several party members had not responded by the time it started. I am unable to leave the quest and my gameplay experience may suffer due to being stuck in a quest that is way above my caliber. 
> 
> https://user-images.githubusercontent.com/102926641/232581327-d58a4f38-5b34-4f31-b9ee-6f2a7540babf.mov

**Comment by saraolson** [comment]
![image](https://github.com/HabitRPG/habitica-ios/assets/12453119/bd4a27d9-85d8-4157-81bf-414fabb69958)
