### ISSUE TITLE
Pet detail view incorrect when equipped

### ISSUE THREAD

**Issue by toonswyzen** [HabitRPG/habitrpg-ios#1282]
**Describe the bug**
If the user has a pet equipped, the pet detail view incorrectly displays the "Unequip" action. The action remains "Equip" while the pet is already equipped.

**To Reproduce**
1. Open the app
2. Navigate to Inventory -> Pets & Mounts page via the hamburger menu
3. Select a pet to go to the details page of that pet
4. Press the pet to show the Equip button -> press the button to equip the pet
5. Press the pet again to show the Unequip button -> The button displays "Equip" while the pet is already equipped.

**Expected behavior**
If the pet is already equipped, the button should display "Unequip" (similar to mounts)

**Screenshots**
[Screenshot](https://imgur.com/a/aaVUEjy)

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS 16.4.1
 - App Version: 3.7.2 (869)
 - Habitica Username: tooz

**Comment by toonswyzen** [comment]
The issue seems to reside in: https://github.com/HabitRPG/habitica-ios/blob/e1e0fed05e164cde9e3d8e674328da2effdff587/HabitRPG/UI/Inventory/Stable/PetDetailViewController.swift#L60 

There are no checks if the pet was already equipped.

**Comment by toonswyzen** [comment]
(accidentally closed the issue)

The issue seems to reside in: https://github.com/HabitRPG/habitica-ios/blob/e1e0fed05e164cde9e3d8e674328da2effdff587/HabitRPG/UI/Inventory/Stable/PetDetailViewController.swift#L60

The app does not check if the pet is already equipped.

**Comment by saraolson** [comment]
Thanks for your report! Hopefully we can also get the little teal star marker on equipped pets soon to improve this experience even more.
