### ISSUE TITLE
empty state not showing when trying to hatch a pet from items w/o both potion & egg

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1285]
if you try to hatch an egg from your items, you'll see a blank screen. this seems like a bug, but it's actually bc you don't have any hatching potions to use on the egg

**Comment by saraolson** [comment]
we need to implement empty state illustrations that were just made to fix this

**Comment by saraolson** [comment]
empty states:
- when you're viewing your inventory and have no items
- when you select an egg / potion to use, but don't have any potion / eggs
- at the bottom of the inventory, where we have a generic link to Market

Special cases:
- for the 'Special' category, we have two different messages for if someone is subscribed or not.
