### ISSUE TITLE
Stuck progress notification when registering and logging in a user without an internet connection

### ISSUE THREAD

**Issue by ncarvajalc** [HabitRPG/habitrpg-ios#1288]
**Describe the bug**
The bug is present when trying to register or log in a user without internet connection. Once the internet connection is disabled and the register/log in button is pressed, a stuck progress indicator appears. Even when the connection is back on, the progress indicator keeps on spinning until the user taps the button again.

**To Reproduce**
1. In the initial page turn off the internet connection
1. Go to the register view
1. Enter the data required for registering
1. Tap the register button
1. Turn on the internet connection again
The progress spinner should still be present

**Expected behavior**
The progress indicator shouldn't appear if there is no internet connection.

**Screenshots**
![image](https://github.com/HabitRPG/habitica-ios/assets/66692533/3723a456-8b4c-44af-99bf-a97ca4a5abe0)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 16.4
 - App Version: 3.7.2
 - Habitica Username: nipets

**Comment by saraolson** [comment]
We've vastly improved server response time that should make it so this isn't encountered through normal use of the app much at all. Closing this issue, though if we receive player reports we can re-evaluate.
