### ISSUE TITLE
Stuck progress notification when buying a reward with no internet connection

### ISSUE THREAD

**Issue by drincon1** [HabitRPG/habitrpg-ios#1293]
**Describe the bug**
The bug is presented when trying to buy a new reward in the 'Rewards' section and the user has enough coins to buy the reward without internet connection. When there is no internet connection and the buy button is pressed, a stuck progress indicator appears. Even when the connection is recuperated, the progress indicator keeps on spinning until the user taps the button again.

**To Reproduce**
Steps to reproduce the behavior are:
1. Without any internet connection, enter to the Rewards tab.
2. Select any element available that costs less than the coin you have.
3. Press the 'Buy' button.
4. Connect to the internet.
Result: The progress spinner will continue.

**Expected behavior**
The progress indicator should not appear when there is no internet connection. 

**Screenshots**
![IMG_09C9E20424A9-1](https://github.com/HabitRPG/habitica-ios/assets/55472595/63242ef7-d25f-486d-acc9-148e06e22d28)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 16.4
 - App Version: 3.7.2
 - Habitica Username: hb-6o0wcnk3zxqq3u8

**Comment by saraolson** [comment]
We've vastly improved server response time that should make it so this isn't encountered through normal use of the app much at all. Closing this issue, though if we receive player reports we can re-evaluate.
