### ISSUE TITLE
Redirection to web browser without connectivity check in the 'About' section

### ISSUE THREAD

**Issue by JPRamirez17** [HabitRPG/habitrpg-ios#1296]
**Describe the bug**
When the user goes to the ‘About’ section and taps on any of the links for making reviews, sharing an opinion, knowing the source code, social media or going to the official website of the app, it is **redirected to the web browser without checking Internet connection**. This issue corresponds to the redirection without connectivity check (RWPC) Eventual Connectivity anti-pattern, in which the user never knows if there is an Internet connection and shows a blank web page. In this case, redirecting to the web browser without Internet connection might make the user think that simply there is no content in that section or even annoy the user because it loses some seconds in that useless action.

**To Reproduce**
1. Access the ‘About’ view and click any link without internet connection
2. User is redirected to the web browser without notifying that connectivity is not available

**Expected behavior**
Do not redirect the user to the web browser without internet connection. Instead, it should notify the user that redirection is not possible due to lack of connectivity.

**Screenshots**
<img width="195" alt="Screenshot 2023-05-17 alle 9 11 41 PM" src="https://github.com/HabitRPG/habitica-ios/assets/68709227/8c0c27e3-27b5-4613-85a9-18f96f41741e">

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 16.4
 - App Version: 3.7.2
 - Habitica Username: hb-9q4p52tk5x7xwgaq0

**Comment by saraolson** [comment]
We've vastly improved server response time that should make it so this isn't encountered through normal use of the app much at all. Closing this issue, though if we receive player reports we can re-evaluate.
