### ISSUE TITLE
notes section on rewards does not expand and gets cut off

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1301]
> iOS Version: 16.5
> Device: iPhone 13
> App Version: 3.7.2
> User ID: 14cb6b7c-5af9-4a5c-995a-2d45bdb60c76
>
>Please describe the bug you encountered:
> iOS mobile app only shows the first line of the reward descriptions. full descriptions show up on the mobile and desktop websites tho. 
> ![IMG_0575](https://github.com/HabitRPG/habitica-ios/assets/102926641/f24ddfe6-74cf-4d3d-8164-00d108454413)
> ![IMG_0576](https://github.com/HabitRPG/habitica-ios/assets/102926641/fa5ccefb-4d9a-4e4c-82b7-25674eb943b7)

**Comment by giovannapezzini** [comment]
hello, I would love to contribute to Habitica by working on this issue!

**Comment by saraolson** [comment]
@giovannapezzini awesomt! thanks for volunteering to pick this up. i've marked the issue as in progress for you. just let us know if you need to step away and we'll put it back up for grabs.

**Comment by giovannapezzini** [comment]
@saraolson Pull request created, let me know if you need anything, I'll be available, thanks!
