### ISSUE TITLE
stats not being recorded correctly

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1305]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 16.3.1
> Device: iPhone XR
> App Version: 3.7.3 (879)
> User ID: 2107b306-d669-4599-b6c6-ff2c8e1e8425
> Level: 143
> Class: mage
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> I noticed that after level 100, the intellect points that are added every 2nd level don't really work. This is easy to see by the fact that the maximum mana value does not increase and the damage against the boss does not increase, although I already have level 148 and I already got 24 points of intelligence after level 100, but these points are of no use.  

they attached the following image:
![image0](https://github.com/HabitRPG/habitica-ios/assets/102926641/d18d9cd1-0c5e-4f1a-abf3-1e727a804075)

this is their stats on web:
<img width="665" alt="Screenshot 2023-07-06 at 3 34 19 PM" src="https://github.com/HabitRPG/habitica-ios/assets/102926641/726f88bc-1a23-4eff-9849-61855c859fe9">

**Comment by saraolson** [comment]
its looking like the app is continuing to 'add' stats after level 100. the max level stat should be 50 (half of your level up until 100, when it doesnt increase anymore).

this seems to just be a display bug tho? as the web is displaying the correct stats

**Comment by saraolson** [comment]
will be included in v 3.10.1
