### ISSUE TITLE
unable to scroll through the discover challenge list due to the list "jumping"

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1307]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 16.5.1
> Device: iPhone14,4
> App Version: 3.7.3 (879)
> User ID: 0a69bb45-3c0c-42bf-9bc5-730a957783c9
> Level: 123
> Class: healer
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> 
> Please describe the bug you encountered:
> When scrolling through the discover challenges tab, it will keep glitching and moving you back up towards the top of the page. You can’t keep scrolling through as it will quite consistently do this, so you can only see the same 20-30 challenges as it will jump back up before you can get any further

**Comment by saraolson** [comment]
im guessing this is an issue with how we handle lazy load for the challenge list..?

**Comment by JBYoshi** [comment]
I think I've traced this down to a mismatch between the challenge sort order on the server (official challenges on top, then from newest to oldest) and the app (most members first). I submitted #1330 to fix this.

**Comment by saraolson** [comment]
Thanks for your help with this! We're working on a rather large release right now, but once that's out of the way we'll be back to reviewing and merging PRs.
