### ISSUE TITLE
Avatar shows too low in task list views when tails or other items on the tail template are equipped

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitrpg-ios#1308]
Avatar is positioned correctly in profile view but not when in task lists.

![IMG_5239](https://github.com/HabitRPG/habitica-ios/assets/9218855/4178b016-2237-4a59-8cd5-193012f23bd6)

![IMG_5240](https://github.com/HabitRPG/habitica-ios/assets/9218855/2845d8c4-a069-417a-817a-1bec3e0c969d)

**Smartphone (please complete the following information):**
 - Device: iphone X
 - OS: iOS 16.5.1
 - App Version: 3.8 (testflight)
 - Habitica Username: 

**Additional context**

**Comment by saraolson** [comment]
fixed in 3.10
