### ISSUE TITLE
Habitica iOS available for Apple Silicon macs

### ISSUE THREAD

**Issue by MessiasLima** [HabitRPG/habitrpg-ios#1313]
Considering that Apple Silicon apps can run iOS applications from the App Store. It would be very good if the Habitica iOS apps were available to download in Macs.

I don't know how much work would be necessary to do so, but we already have some iOS apps which do it

 
![Screenshot 2023-07-17 at 10 06 15](https://github.com/HabitRPG/habitica-ios/assets/10220064/6de3a4cb-dbfd-44f6-8611-647ca297a076)

Thank you for all your hard work! ❤️

**Comment by saraolson** [comment]
hi there! thanks for reaching out and sharing your excitement to support habitica on more devices :) we've looked into this a bit, but at the moment we're choosing to hold off as we evaluate the support resources necessary. we're a small team with one full time mobile developer for both iOS and android, so we have to be careful before making big decisions like these!

im going to close the issue for now, as we usually store feature and platform requests on our [feature request form.](https://docs.google.com/forms/d/e/1FAIpQLScPhrwq_7P1C6PTrI3lbvTsvqGyTNnGzp1ugi1Ml0PFee_p5g/viewform). Feel free to add your feedback there as well if you'd like!
