### ISSUE TITLE
Accepting a Quest on Party view doesn't immediately make the buttons go away

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#1314]
If you're viewing a quest invite in party and you tap 'accept' or 'reject' it looks like nothing happens. the buttons stay there. if you tap again it will give you an error that you're already joined etc. pulling to refresh properly updates the view

**Comment by tjb** [comment]
I cant take a look!

**Comment by tjb** [comment]
hey @saraolson on iOS 17 iPhone 15 Pro simulator when I accept the quest invite it gets accepted and disappears from the notification tab. 

what device were you using when you encountered this?

**Comment by saraolson** [comment]
@tjb this actually may have been fixed when we did a recent overhaul of the quest UI. unable to reproduce anymore, so gonna close unless it's reported again :)
