### ISSUE TITLE
checklist item emojis break after being checked off

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1315]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 16.5.1
> Device: iPhone XS
> App Version: 3.7.3 (879)
> User ID: b9340638-ee49-42f9-a2c9-f406187a3c05
> Level: 6
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> 
> Please describe the bug you encountered:
> I’m using checklists with emoji in one of my dailies and when crossed out, the emoji is broken. See attached screenshot
> ![image0](https://github.com/HabitRPG/habitica-ios/assets/102926641/4a65c2c6-e817-4b61-b019-6e34e49ed90b)

seems to only happen when the emoji is added after the text in a checklist item, not when added before the text.

**Comment by tjb** [comment]
I'll take a look!
