### ISSUE TITLE
mounts don’t show pixel art in the bottom sheet when you tap them

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1316]
![IMG_0844](https://github.com/HabitRPG/habitica-ios/assets/102926641/43173d1c-12aa-4389-8409-3dc2c7b513d9)

**Comment by tjb** [comment]
I dived into this a bit! Please assign to me @saraolson :) 

I am seeing the image container rendering at 70x70 using the inspector but the image is not showing as mentioned in the above ticket. So this lead me to believe this may be a fetching issue. 

Taking a deeper dive I looked at the URL being generated and see that we are storing images in S3. When I try to access the url for the image in the browser I get the following: 

```
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>MZNMXAW99XH84WEE</RequestId>
  <HostId>wexKvCj4uD2Rrq+LO3YzmH2zJKvgO6BOo3MIieGtPGDL1xwTFcAm2ezGZka7cZ+f0qbDalLGtNI=. 
  </HostId>
</Error>
```
The URL in question: `https://habitica-assets.s3.amazonaws.com/mobileApp/images/stable_Mount-Icon-Orca-Base.png`

I have also tested a public image and built it via `URL(string: "...")` and the image shows. Could this be an access issue to the S3 bucket? 

@saraolson is there someone from the web/infra team that could weigh in? cc: @phillipthelen

**Comment by phillipthelen** [comment]
No this would t be a permission error. S3 responds with access denied when the image at the path does not exist as well. So it might just be the app generating the wrong url. Looking at it I can't see anything obviously wrong. Is the url it uses to show the mount icon in the collection view cell a different one?

**Comment by tjb** [comment]
I didn't think to check there!

I can check later tonight as I am about to head out for the day -- good call @phillipthelen!

**Comment by saraolson** [comment]
@tjb assigned, thanks for taking a look into this!
