### ISSUE TITLE
display issue when selecting two-handed weapons

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1317]
![IMG_0843](https://github.com/HabitRPG/habitica-ios/assets/102926641/b41facfd-04e1-4462-8301-d112f74c62e7)
looks fine on other selected items.

**Comment by tjb** [comment]
@saraolson a pull request has been up for quite a while, can we get it merged in?

**Comment by saraolson** [comment]
@tjb we only have one developer for mobile and he's been working on android for awhile. we just shipped that update this week and are getting back to ios, so he'll likely be reviewing PRs soon.
