### ISSUE TITLE
tapping "open shop" in the items section doesn't redirect to the market

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1318]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 16.5.1
> Device: iPhone 11
> App Version: 3.8 (903)
> User ID: 77e52a7b-1fc4-4605-b66a-1a03c5f5ce0f
> Level: 4
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> Please describe the bug you encountered:
>
> No change when pressing “Open Shop” on the Items page. The button responds by changing color, but does not redirect to the Market.

**Comment by JHeisecke** [comment]
Hi! I'd like to work on this bug, please.

**Comment by saraolson** [comment]
our team is working on a rehaul of this messaging that we just implemented in the android app which will fix this issue
