### ISSUE TITLE
Absence of Ukrainian in list of available languages

### ISSUE THREAD

**Issue by nazarparuna** [HabitRPG/habitrpg-ios#1319]
**Describe the bug**
There is no Ukrainian in the list of available languages in Settings menu. Despite of that translations are present in https://translate.habitica.com/languages/uk/habitica-ios/

**To Reproduce**
Open Settings -> Open dropdown with languages

**Expected behavior**
See in the bottom of dropdown Ukrainian as available option.

**Screenshots**
![photo_2023-08-02_11-25-53](https://github.com/HabitRPG/habitica-ios/assets/9466262/77f0ef37-418a-446a-9dac-446d4a6120a0)

**Smartphone:**
- Device: IPhone XR
- OS: iOS16.5.1
- App Version: 3.8
- Habitica Username: @punk-rock

**Comment by saraolson** [comment]
this is because the main strings are only 25% translated. we try to add support for languages that have more complete translations. once it gets higher, we'll allow it to be selected in the app.
