### ISSUE TITLE
Choose to display To-do's in iOS widgets

### ISSUE THREAD

**Issue by catsseye** [HabitRPG/habitrpg-ios#1322]
I use dailies a lot, but it's harder to remember my one off to-dos than dailies sometimes. Having a widget display around just makes things so much easier to keep up with! Would love to see an option to show them in a medium or large list like the dailies that are available now.

**Comment by Dishant10** [comment]
I would like to work on this. It seems like a pretty genuine and impactful feature.

**Comment by saraolson** [comment]
@Dishant10 this issue is still up for internal discussion and would be left to our own developers once its decided on how we'd like to move forward. if you'd like to take on another issues in our repo, you can browse ones that have the help wanted label to see what's available

**Comment by OlliePugh** [comment]
Has there been any movement on this issue? This is a big blocker for me moving from _Things_ to _Habitica_

**Comment by saraolson** [comment]
@OlliePugh we have designs in place and it's in the queue. since we only have one developer for both the android and iOS apps, it takes some time to get through planned releases.

**Comment by OlliePugh** [comment]
Thats awesome, looking forward to it :)

**Comment by saraolson** [comment]
this will be available in the next version update, likely releasing in a week or so  🎉
