### ISSUE TITLE
dailies widget has black frame

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1325]
> Hi guys, Habitica’s iOS Widget is facing this problem on iOS 17.2.1 on iPhone 13. As the picture describes, a black square frames the widget.
> 
> This is happening since last updates.
> ![image0](https://github.com/HabitRPG/habitica-ios/assets/102926641/d96d53e0-5935-42c5-a887-4d3645b89c1a)

**Comment by saraolson** [comment]
will be fixed in 3.9.1
