### ISSUE TITLE
Party member experience required and max mana not showing up

### ISSUE THREAD

**Issue by Shadallark** [HabitRPG/habitrpg-ios#133]
As shown in the image below, when I view members of my party their experience shows up as some number over zero (##/0) as does their mana.  These stats show up correctly on the website.

![image](https://cloud.githubusercontent.com/assets/13031092/8920376/9ebd5fee-349e-11e5-84ba-5a352050b8b5.jpg)

**Comment by Shadallark** [comment]
I am working on this issue now.

**Comment by vIiRuS** [comment]
We briefly discussed how to fix this internally. The api does not return those values directly. Instead they would have to be calculated locally from the available data. The reference implementation would have to be looked up in the api code and then replicated locally.

**Comment by Shadallark** [comment]
Hmmmm, I was thinking that since it can pull this information for my character using my ID that I could tell it to pull the information for the party members by first grabbing their IDs from the available information and then making an explicit call using that ID rather than the party ID. I was planning to try that later this weekend.  Based on your comment above, I guess that will not work.

**Comment by crookedneighbor** [comment]
The api call for GET /user is special in that it adds those calculations in. It's not actually stored on the user object. See here:

https://github.com/HabitRPG/habitrpg/blob/develop/website/src/controllers/user.js#L203-L205

**Comment by Shadallark** [comment]
Hmmm I can look up the API code and replicate it locally.  This of course is not the best option as changes made to the reference code will not percolate through automatically.  Should we consider changing this in the API instead?

**Comment by Shadallark** [comment]
I found the equation to determine the experience required to get to the next level and have added that into the code.  

Looking through the website code it does not look like the maximum mana will be as easy to determine as it is affected by numerous things and is not a straight forward equation.

I think I am going to stop working on the maximum mana until I get more familiar with the API.
