### ISSUE TITLE
Widget content goes outside of widget border when using large text size settings

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitrpg-ios#1332]
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 16.1.1
> Device: iPhone X
> App Version: 3.9.2 (955)
> User ID: cf6bbee6-e15b-495f-bade-71c87d4507c4
> 
> Please describe the bug you encountered:
> Widgets are now out of frame on iPhoneX since the latest update (content goes outside of widget borders making it unreadable). 
![image0(1)](https://github.com/HabitRPG/habitica-ios/assets/102926641/de3d8d58-9345-42ca-971f-3ea6942be0d9)

tested it again with accessibility text on max and was able to reproduce the issue.

**Comment by saraolson** [comment]
Fixed in 3.11
