### ISSUE TITLE
App freezes after class change in settings (testflight)

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitrpg-ios#1342]
When in settings to change class: prior to the actual class selection screen, a modal pops up as if you've already chosen (screenshot included here - it just says "You're a!") 
![IMG_8634](https://github.com/user-attachments/assets/7f061c48-934b-4f4d-bd31-09f09c0201de). That modal disappears and you get to the normal selection screen. After selection you get the "You're a Healer (etc) modal but it flashes and disappears so quickly you can't tap "got it". ![IMG_8636](https://github.com/user-attachments/assets/1a8748e9-f467-4ba3-8cab-acb8fecac2c2) The screen freezes showing your chosen class (screenshot included). ![IMG_8635](https://github.com/user-attachments/assets/d3cd882b-3d29-48a6-af94-902da3b615ef) There is no way to exit this screen except hard closing the app and re-starting.

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: 16.7.10
 - App Version: 3.12
 - Habitica Username: 

**Additional context**

**Comment by saraolson** [comment]
fixed this
