### ISSUE TITLE
Don't allow saving tasks with nothing entered as a title

### ISSUE THREAD

**Issue by guswnsim** [HabitRPG/habitrpg-ios#1345]
When I try to add a new list through New Habit, I press the Create button without any input, and I have a bug that swipes to the left and doesn't delete it even though I try to delete it.

Turn on the application and press the + button to create NewHabit.
I created it by accidentally pressing the create button without entering anything.
I tried to delete it by swiping to the left and pressing the Delete button, but it won't be deleted with the phrase 'Task not found'.

I expected it to be deleted like deleting a normal list, but it wasn't.
I just wish the regular list would be erased as if it were.

 - Device: iPhone15
 - OS: iOS18.1
 - App Version: 3.11.3
 - Habitica Username: guswnsim
![image](https://github.com/user-attachments/assets/621d6d57-b95c-4c73-a8b0-9cd82a520771)
![image](https://github.com/user-attachments/assets/dd085d1d-dde2-498b-ab2f-2fe662a89dae)
![image](https://github.com/user-attachments/assets/70bc5bcf-842b-4107-a6b7-f1617660d6f5)
![image](https://github.com/user-attachments/assets/f2e2f34c-5770-4a35-b980-109a2f336d90)
![image](https://github.com/user-attachments/assets/a02eb163-ea5e-417e-b01f-48d694615862)

**Comment by saraolson** [comment]
it sounds like the issue here is that it looked as if a blank habit was added to your list, but it wasn't actually created? so when you went to delete it, the server didn't find anything to delete.

tasks shouldnt be able to be created without adding any title, so i'm gonna change this issue to reflect that with the idea that preventing this case will also prevent this bug.

**Comment by guswnsim** [comment]
> it sounds like the issue here is that it looked as if a blank habit was added to your list, but it wasn't actually created? so when you went to delete it, the server didn't find anything to delete.
> 
> tasks shouldnt be able to be created without adding any title, so i'm gonna change this issue to reflect that with the idea that preventing this case will also prevent this bug.

Where can I find a folder where I can modify the relevant code?

**Comment by saraolson** [comment]
our developer worked on fixing this already. the UX isn't perfect (we'd prefer the button to be disabled when no title exists) but after the next update it will no longer create a fake task when saving one without a title (3.12.1)
