### ISSUE TITLE
Upgrade Kingfisher 

### ISSUE THREAD

**Issue by tjb** [HabitRPG/habitrpg-ios#1346]
**Describe the bug**
When building the application the following error is given

> Initializer for conditional binding must have Optional type, not 'AnyView'

**To Reproduce**
Build the application on iOS 18

**Expected behavior**
A clean build occurs

**Screenshots**
![Screenshot 2024-11-15 at 6 23 19 PM](https://github.com/user-attachments/assets/1d12e918-2c88-4e7b-a769-e168e4fef58c)

**Smartphone (please complete the following information):**
 - App Version: [e.g. 2.2]
 - Habitica Username: e8160fe6-2e6d-494f-b7db-60befa34fe8a

**Comment by saraolson** [comment]
we've fixed this for the next update thats in testing now. shouldn't take long to release (3.12.1)
