### ISSUE TITLE
Removing the due date from a to-do doesn't remove the due date

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitrpg-ios#136]
clearing the due date in the form apparently leaves it on the todo object

**Comment by kyle-fox** [comment]
This seems to be related to a behavior in Restkit that has existed for a long time - referenced in https://github.com/RestKit/RestKit/issues/1311. Habitica's API expects to receive a null value when you want to clear out the existing value for `dueDate`, but when I change the code (23bb1bb8087b3f86621ca771d97c690cdde469ad) to modify the data as expected, Restkit sees the nil value and does not include it in the JSON for the PUT request. The suggested fix in https://github.com/RestKit/RestKit/issues/1311 definitely fixes the issue, but it requires modifying Restkit's code...so it's not a good choice.

I'll keep investigating, but I haven't been able to find another fix at the moment.

**Comment by crookedneighbor** [comment]
Alternatively we could adjust the API to accept a false value as well as a null value.

**Comment by jwhitmire** [comment]
This is still an issue.  It works fine via the web, but the IOS app doesn't allow clearing a due date on a todo.  Not sure it's any easier to fix, or worth fixing now, just leaving a note for others who come looking for this as I did.

**Comment by Alys** [comment]
For further information about this issue, see https://github.com/HabitRPG/habitica-ios/issues/292
