### ISSUE TITLE
Jack-O-Lantern Mount Listed

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#14]
There is a listing for a Jack-O-Lantern Mount in the Mounts section, although there is not (yet) such a mount.
![img_2845](https://cloud.githubusercontent.com/assets/3494081/7264952/38f25d16-e847-11e4-886a-3b5410c9880c.PNG)

**Comment by josephholsten** [comment]
I can't reproduce this. Is this still an issue?

**Comment by lemoness** [comment]
So, there IS now a Jack-O-Lantern mount, so it's a good idea for it to have a listing!
