### ISSUE TITLE
iPad Version

### ISSUE THREAD

**Issue by Shadallark** [HabitRPG/habitrpg-ios#140]
The 1.0.1 (65) version of the Habitica-iOS app is being built for the iPhone only.  Therefore it shows up big and clunky on the iPad (or only uses part of the screen when not zoomed).

I have copied the content from the iPhone storyboard to the iPad storyboard and adjusted the build settings to build for both devices.  This makes the app look much better on the iPad than it has previously.

I would be willing to undertake the task of ensuring that any changes made to the iPhone storyboard are copied over to the iPad storyboard to ensure the two versions remain synchronized going forward, if people agree that it makes sense to create the iPad ready version at this time.

Shadallark

**Comment by vIiRuS** [comment]
I would have to verify this, but i think it is possible to use the same storyboard for iPhone and iPad. This way it would not be necessary to copy each change. Because that solution would be sure to causr problems at some point. But if we can get them to use the same storyboard and verify that everything works on the iPad, i think it's a good solution for now. The reason i haven't done it yet, is that i haven't had the time to ensure everything still works yet.

**Comment by Shadallark** [comment]
Thanks @vIiRuS for the tip about using one storyboard for both iPhone and iPad.  I did some research and that is possible.  I will update my code to try this out and let you know how it works.

**Comment by kyle-fox** [comment]
Sorry to recommend you throw away so much work, but give this a try and let me know. Works well for me, if you want to keep the interface the same. In `Main_iPhone.storyboard` File Inspector, check the box for `Use Size Classes` under `Interface Builder Document` section. Then in project settings under `Deployment Info`, set the iPad's main interface to `Main_iPhone`. That should get you back to where you were with the separate iPad storyboard, and then you can tweak from there. If you're going to do that, might as well also delete `Main_iPad.storyboard` and just change the name of the iPhone storyboard to `Main.storyboard`, which is the default. This will definitely be the best way to go forward, especially with the upcoming resizable views in iOS 9 on iPad.

The only significant thing I see that need to be fixed after making those changes would be to reset the size of the `backgroundView` in `HRPGTopHeaderNavigationController` when the app rotates. You might want to wait on that change though, since there is a pending pull request where I make major changes to that class, and it would be a simpler fix with my changes, if they're being merged in.

**Comment by Shadallark** [comment]
Okay.  The following things do not work on the iPad when creating an iPad version using either the iPhone or iPad storyboard:
* changing my shirt, skin, hair colour, etc.;
* unequiping or changing my equipment;
* Hatching / selling eggs;
* starting quests;
* feeding / equipping / unequipping pets;
* equipping / unequipping pets;
* basically **any actions** that usually cause buttons to be overlayed at the bottom of the screen do not cause those buttons to be displayed; and
* the width of my Character's display area at the top of the screen:
   * on the iPhone storyboard this section is always set to width of 320 no matter the orientation or screen selected;
   * on the iPad storyboard this section is set to 320 for the Habits screen and set to 600 for the majority of the rest of the screens (so Habits looks correct in Portrait or upside down, while other screens look correct in rotated left or rotated right).

Things that do work:
* casting spells;
* adding Habits, Dailies, To-Dos and adding checklists;
* writing messages in the tavern and to my party;
* viewing party members;
* viewing news;
* settings;
* About screen; and
* rotating the screen:
   * although some of the screens should do a recalculation of row sizes after a rotation occurs to ensure the cell text still displays properly.

I will keep digging into this and see if I can figure out how to make the button overlay screens show up correctly on the iPad when using the iPhone storyboard.

Shadallark

**Comment by kyle-fox** [comment]
Nice - looks like you were way ahead of me 👍

**Comment by vIiRuS** [comment]
That doesn't sound too bad! Can you maxbe post s dcreenshot of what you mean with the characters display area? Not sure i can follow.

The button overlay is a uiactionsheet. Apparently those are handled differently on ipads. (Google search for "ipad uiactionsheet" should point you in the right direction)

Thanks for the work so far! :+1:

**Comment by Shadallark** [comment]
Thanks for the guidance @kyle-fox and @vIiRuS, I will see what I can find about the UIActionsheet.

Here is an image of my Habits screen on the iPad.  The section at the top with my character, health, experience, and mana does not go all the way across the screen when the iPad is rotated. This might be related to the size of the backgroundView that @kyle-fox mentioned above.  It is not a major issue though as it does not affect functionality, only asthetics.

![image](https://cloud.githubusercontent.com/assets/13031092/9027461/181108fa-392c-11e5-8ed3-347f58bea49c.jpg)

**Comment by vIiRuS** [comment]
aah! see the problem. We will need a check for the width of the view that checks if the device is in landscape or not. Currently it always uses the width of the device. But if the device is in landscape, it has to use the width

**Comment by Shadallark** [comment]
Hello again;

Okay.  We are currently using:

**[popup showInView:[UIApplication sharedApplication].keyWindow];**

to display the UIActionSheet.  For the UIActionSheet to be converted into a PopOver correctly for use on the iPad we need to be using:

**[popup showFromRect:rectIPad inView:self.view animated:YES];**

where *rectIPad* is defined as some rectangle on the screen for the iPad to use as a reference.  If we want this to popup at the bottom of the screen like it does for the iPhone we need to define a rectangle (rectIPad) that is located at the bottom of the screen in the middle, or we could have it show up relative to the piece of equipment that was touched, which requires a rectangle for that view.  Therefore, I have the following questions for you:

1) Do we want the interface to be the same as what is experienced by iPhone users or to be the more context based method showing the popover pointing to the item that was selected (refer to the picture)?

2) If we want it to be the same as the iPhone interface I was thinking of doing something like this:
    // Determine the orientation of the App
    **if(UIInterfaceOrientationIsPortrait(self.interfaceOrientation)) {**
            // app is Portrait
            //  therefore determine the height (How??) and width (How??) and create the appropriate rectangle
        **rectIPad = CGRectMake(20, height-20, width - 40, 300);
    } else if(UIInterfaceOrientationIsLandscape(self.interfaceOrientation)){**
            // app is Landscape
            // therefore determine the height (which is width) and width (which is height)
        **rectIPad = CGRectMake(20, height-20, width-40, 300);**
    }

3) If we want the more intuitive result where the PopOver shows up pointing at the item that was selected, how do we define a rectangle based on the item selected?  Using the attached photo as an example, how do we tell where the Lion Cub egg is on the screen if that is the item that was touched (note I just guessed when I was defining the rectangle so you could see the contextual style of the iPad PopOver)?

Note that the iPhone app is not affected by the choice of Rectangle, it always displays the UIActionSheet at the bottom of the screen.

Also note that the iPad version does not display the Cancel Button option.  This is because the PopOver is dismissed (ie. cancelled) as soon as the user touches somewhere outside of the PopOver menu.

![img_0344](https://cloud.githubusercontent.com/assets/13031092/9027883/be3d19e8-393c-11e5-85c7-b71f6b321b76.PNG)

**Comment by vIiRuS** [comment]
I'm not sure how the endresult will look with the tableview cells, but I'd prefer attaching the popover to the tapped item. The reason that it is done this way on the iPad is that it is much quicker for the user as they require less finger movement (the popover is close to the thing you tapped and not at the bottom of the screen which might be quite far away if you tap at the top) and I'd like to also have that.

As to where to attach it: each view in iOS has a frame that defines it's size. I would suggest we use the frame of the tableviewcell or collectionviewcell. As all actionsheets should be called through a didSelectRowAtIndexPath/didSelectItemAtIndexPath that should be the easiest.

**Comment by Shadallark** [comment]
For my own reference as I work through the locations using UIActionSheet.  I have updated the code allowing it to function on iPhone and iPad for the following areas:
* Equipment
* Items / Quests
* Pets
* Mounts (slightly less than perfect implementation here but acceptable for now)

Looking back at my original list it looks like I only need to fix the ability to change how I look and I should have a working iPad version of the App.

I will perform further testing once I fix this last issue.

**Comment by Shadallark** [comment]
As far as I can tell I am all done everything that is required to get the iPad version of the App functioning correctly.
