### ISSUE TITLE
Rare Pets have Growth Bar

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitrpg-ios#144]
Copied from https://github.com/HabitRPG/habitrpg/issues/5730

>On the Habitica app, clicking on your Veteran Wolf gives it a growth bar. When you click on it, it gives you the option to feed it, but if you try, it will give you a network error (Couldn't connect to the server. Check your network connection). This is incorrect because this error should be caused because Veteran Wolves cannot be fed. A growth bar does not exist for the wolf either so it should not be shown. I hope this makes sense, I am not a programmer :)

After some investigation, it looks like it's all rare pets that exhibit this behavior, not just the Veteran wolf. 

In addition, there's a placeholder for mount versions of some rare pets that do not exist (yet). IE, purple griffin and orca. The vice-versa is also true, any rare pet you have also has a rare mount version of it. 

+ [x] - remove feed bar from rare pets
+ [x] - remove non-existent rare pets
+ [x] - remove non-existent rare mounts

**Comment by vIiRuS** [comment]
the rare/special pets all should have the type " ". So the feed bar could be removed based on that.

**Comment by vIiRuS** [comment]
All fixed.

**Comment by corroded** [comment]
Hi,

I just saw this bug again. Am on iOS 11 if it helps. 

![img_f3b45aa57780-1](https://user-images.githubusercontent.com/46548/32113224-44aeb4dc-bb72-11e7-994a-a888a9b59328.jpeg)
