### ISSUE TITLE
Possible Spelling Issue in Food

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitrpg-ios#149]
Originally posted here: https://github.com/HabitRPG/habitrpg/issues/5744

When a food item is attained in the iOS app, I believe that the the json key is used instead of the name of the food, this results in a user getting a "potatoe" instead of a "potato". Yep. The json key is misspelled. 

@vIiRuS can you confirm whether or not what I said is accurate regarding using the json keys to display the item name? Thinking about it more, the user who reported it may have been talking about the phonegap app.

**Comment by Shadallark** [comment]
I noticed that food was coming up that way earlier today on the iOS app when I received *potatoe* instead of *a potatoe* and *strawberry* rather than *a strawberry*.

**Comment by vIiRuS** [comment]
@crookedneighbor absolute true. Is fixes now
