### ISSUE TITLE
iOS-Specific FAQ

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#157]
Right now, the FAQ link leads to the wiki, which is 1) confusing and overwhelming to new users, and 2) usually website specific. 

Here is the text for an iOS-specific FAQ to replace the wiki link. @vIiRuS had some ideas about how to implement it.

---

**Frequently Asked Questions**

**I’m confused. Where do I get an overview?**

First, you’ll set up tasks that you want to do in your everyday life. Then, as you complete the tasks in real life and check them off, you’ll earn experience and gold. Gold is used to buy equipment and some items, as well as custom rewards. Experience causes your character to level up and unlock content such as Pets, Skills, and Quests! You can customize your character under Menu > Customize Avatar.

Some basic ways to interact: click the (+) in the upper-right-hand corner to add a new task. Tap on an existing task to edit it, and swipe left on a task to delete it. You can sort tasks using Tags in the upper-left-hand corner, and expand and contract checklists by clicking on the checklist bubble.

**How do I set up my tasks?**

Good Habits (the ones with a +) are tasks that you can do many times a day, such as eating vegetables. Bad Habits (the ones with a -) are tasks that you should avoid, like biting nails. Habits with a + and a - have a good choice and a bad choice, like taking the stairs vs. taking the elevator. Good Habits award experience and gold. Bad Habits subtract health.

Dailies are tasks that you have to do every day, like brushing your teeth or checking your email. You can adjust the days that a Daily is due by tapping to edit it. If you skip a Daily that is due, your avatar will take damage overnight. Be careful not to add too many Dailies at once!

To-Dos are your To-Do list. Completing a To-Do earns you gold and experience. You never lose health from To-Dos. You can add a due date to a To-Do by tapping to edit.

**What are some sample tasks?**

The wiki has four lists of sample tasks to use as inspiration:
[Sample Habits](http://habitica.wikia.com/wiki/Sample_Habits)
[Sample Dailies](http://habitica.wikia.com/wiki/Sample_Dailies)
[Sample To-Dos](http://habitica.wikia.com/wiki/Sample_To-Dos)
[Sample Custom Rewards](http://habitica.wikia.com/wiki/Sample_Custom_Rewards)

**Why do my tasks change color?**

Your tasks change color based on how well you are currently accomplishing them! Each new task starts out as a neutral yellow. Perform Dailies or positive Habits more frequently and they move toward blue. Miss a Daily or give in to a bad Habit and the task moves toward red. The redder a task, the more rewards it will give you, but if it’s a Daily or bad Habit, the more it will hurt you! This helps motivate you to complete the tasks that are giving you trouble.

**Why did my avatar lose health, and how do I regain it?**

There are several things that can cause you to take damage. First, if you left Dailies incomplete overnight, they will damage you. Second, if you tap a bad Habit, it will damage you. Finally, if you are in a Boss Battle with your Party and one of your Party mates did not complete all their Dailies, the Boss will attack you.

The main way to heal is to gain a level, which restores all your health. You can also buy a Health Potion with gold from the Rewards column. Plus, at level 10 or above, you can choose to become a Healer, and then you will learn healing skills. If you are in a Party with a Healer, they can heal you as well. 

**How do I play Habitica with my friends?**

The best way is to invite them to a Party with you, via the [website](link)! We’ll add the ability to create a Party from this app soon, but in the meantime you can use the [website](). Parties can go on quests, battle monsters, and cast skills to support each other. On the website, you and your friends can also join Guilds, which are public chat rooms. Guilds will be added to the app in a future update!

**How do I get a Pet or Mount?**

At level 3, you will unlock the Drop System. Every time you complete a task, you'll have a random chance at receiving an egg, a hatching potion, or a piece of food. They will be stored in Menu > Items.

To hatch a Pet, you'll need an egg and a hatching potion. Tap on the egg to determine the species you want to hatch, and select "Hatch Egg." Then choose a hatching potion to determine its color! Go to Menu > Pets to equip your new Pet to your avatar by clicking on it. 

You can also grow your Pets into Mounts by feeding them under Menu > Pets. Tap on a Pet, and then select "Feed Pet"! You'll have to feed a pet many times before it becomes a Mount, but if you can figure out its favorite food, it will grow more quickly. Use trial and error, or [see the spoilers here](http://habitica.wikia.com/wiki/Food#Food_Preferences). Once you have a Mount, go to Menu > Mounts and tap on it to equip it to your avatar.

You can also get eggs for Quest Pets by completing certain Quests. (See below to learn more about Quests.)

###How do I become a Warrior, Mage, Rogue, or Healer?

At level 10, you can choose to become a Warrior, Mage, Rogue, or Healer. (All players start as Warriors by default.) Each Class has different equipment options, different Skills that they can cast after level 11, and different advantages. Warriors can easily damage Bosses, withstand more damage from their tasks, and help make their Party tougher. Mages can also easily damage Bosses, as well as level up quickly and restore Mana for their party. Rogues earn the most gold and find the most item drops, and they can help their Party do the same. Finally, Healers can heal themselves and their Party members.

If you don’t want to choose a Class immediately -- for example, if you are still working to buy all the gear of your current class -- you can click “Decide Later” and choose later under Menu > Choose Class.

###What is the blue stat bar that appears in the Header after level 10?

The blue bar that appeared when you hit level 10 and chose a Class is your Mana bar. As you continue to level up, you will unlock special Skills that cost Mana to use. Each Class has different Skills, which appear after level 11 under Menu > Use Skills. Unlike your health bar, your Mana bar does not reset when you gain a level. Instead, Mana is gained when you complete Good Habits, Dailies, and To-Dos, and lost when you indulge bad Habits. You’ll also regain some Mana overnight -- the more Dailies you completed, the more you will gain.

###How do I fight monsters and go on Quests?

First, you need to join or start a Party (see above). Although you can battle monsters alone, we recommend playing in a group, because this will make Quests much easier. Plus, having a friend to cheer you on as you accomplish your tasks is very motivating!

Next, you need a Quest Scroll, which are stored under Menu > Items. There are three ways to get a scroll:

- At level 15, you get a Quest-line, aka three linked quests. More Quest-lines unlock at levels 30, 40, and 60 respectively. 

- When you invite people to your Party on the [website](link), you’ll be rewarded with the Basi-List Scroll! (We will add this feature to the app in a future update.)

- You can buy Quests from the Quests Page on the [website](link) for gold and gems. (We will add this feature to the app in a future update.)

To battle the Boss or collect items for a Collection Quest, simply complete your tasks normally, and they will be tallied into damage overnight. (Reloading by pulling down on the screen may be required to see the Boss's health bar go down.) If you are fighting a Boss and you missed any Dailies, the Boss will damage your Party at the same time that you damage the Boss. 

After level 11 Mages and Warriors will gain Skills that allow them to deal additional damage to the Boss, so these are excellent classes to choose at level 10 if you want to be a heavy hitter.

###What are gems, and how do I get them?

Gems are [purchased with real money](link) by tapping on the gem icon in the header. When people buy gems, they are helping us to keep the site running. We’re very grateful for their support!
In addition to buying gems directly, there are three other ways players can gain gems:
1. Win a Challenge on the [website](link) that has been set up by another player under Social > Challenges. (We will be adding Challenges to the app in a future update!)
2. Subscribe on the [website](link) and unlock the ability to buy a certain number of gems per month.
3. Contribute your skills to the Habitica project. See this wiki page for more details: [Contributing to Habitica](http://habitica.wikia.com/wiki/Contributing_to_Habitica).
Keep in mind that items purchased with gems do not offer any statistical advantages, so players can still make use of the app without them!

###How do I report a bug or request a feature?

You can report a bug, request a feature, or send feedback under Menu > Report a Bug and Menu > Send Feedback! We’ll do everything we can to assist you.

###If you have a question that isn’t on this list, come ask in the Tavern chat under Menu > Tavern! We’re happy to help.

**Comment by lemoness** [comment]
Updated to add in the Pets and Mounts question. (@viirus, be sure to confirm that it is correct.)

**Comment by vIiRuS** [comment]
Eveything correct (could also mention that you can tap the hatching potion and then choose the egg, but that's not necessary)

**Comment by crookedneighbor** [comment]
Working on this now.

**Comment by lemoness** [comment]
This is in the most recent version! Can it be closed?

**Comment by lemoness** [comment]
We need to update some of the text to be accurate with the new features!
_________________
###How do I play Habitica with my friends?

The best way is to invite them to a Party with you! Parties can go on quests, battle monsters, and cast skills to support each other. Go to Menu > Party and click "Create New Party" if you don't already have a Party. Then tap on the Members list, and tap Invite in the upper right-hand corner to invite your friends by entering their User ID (a string of numbers and letters that they can find under Settings > Account Details on the app, and Settings > API on the website). On the website, you can also invite friends via email, which we will add to the app in a future update. 

On the website, you and your friends can also join Guilds, which are public chat rooms. Guilds will be added to the app in a future update!

###How do I fight monsters and go on Quests?

First, you need to join or start a Party (see above). Although you can battle monsters alone, we recommend playing in a group, because this will make Quests much easier. Plus, having a friend to cheer you on as you accomplish your tasks is very motivating!

Next, you need a Quest Scroll, which are stored under Menu > Items. There are three ways to get a scroll:

-At level 15, you get a Quest-line, aka three linked quests. More Quest-lines unlock at levels 30, 40, and 60 respectively.

-When you invite people to your Party, you’ll be rewarded with the Basi-List Scroll!

-You can buy Quests from the Quests Page on the website for gold and gems. (We will add this feature to the app in a future update.)

To battle the Boss or collect items for a Collection Quest, simply complete your tasks normally, and they will be tallied into damage overnight. (Reloading by pulling down on the screen may be required to see the Boss's health bar go down.) If you are fighting a Boss and you missed any Dailies, the Boss will damage your Party at the same time that you damage the Boss.

After level 11 Mages and Warriors will gain Skills that allow them to deal additional damage to the Boss, so these are excellent classes to choose at level 10 if you want to be a heavy hitter.
