### ISSUE TITLE
"Equipment & Skills" tab not showing

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitrpg-ios#160]
Originally reported here: https://github.com/HabitRPG/habitrpg/issues/5783

> Today I leveled up to level 10 on the Habitica app and no class-exclusive equipment showed up. The browser version is working correctly and showing the "Equipment & Skills" tab, but this is not shown on the Habitica app, even after I reloaded the content multiple times.

> **User ID:** ce3d1e2b-be53-4e5e-8101-273157548178
> **Operating System:** iOS 8.4

> *My Rewards column*
> ![habitrpg](https://cloud.githubusercontent.com/assets/12767408/9265844/d0370dde-41ed-11e5-8bf5-83b3007bb56f.png)

**Comment by Shadallark** [comment]
Thanks for reporting this issue @MrEikono . Can you tell me if you have selected your class?  I see from the image that your Mana is showing up correctly.

**Comment by MrEikono** [comment]
I have selected my class @Shadallark , I chose mage. Here's a new screenshot from this morning where I am wearing the class-exclusive equipment (bought on the browser version):

![habitrpg](https://cloud.githubusercontent.com/assets/12767408/9280019/572e5cf2-4270-11e5-89ee-93514e980fb2.png)

**Comment by SabreCat** [comment]
From the Newbies Guild:
![image](https://cloud.githubusercontent.com/assets/4501321/9669942/a6a324f4-524f-11e5-9ab6-8512bf8b1f20.png)
Related? Or separate issue?

**Comment by vIiRuS** [comment]
related issue. thanks for relaying

**Comment by MrEikono** [comment]
Quick question - Will I get a tier++ for reporting this once it's fixed, or do I need to do something more?

**Comment by crookedneighbor** [comment]
We don't award contributor tiers for reporting issues. You can read about how to gain contributor tiers here: http://habitica.wikia.com/wiki/Contributing_to_Habitica

**Comment by Indubitably1** [comment]
According to the Wikia: 
http://habitica.wikia.com/wiki/Mobile_App_for_iOS:_Habitica
Social > Party
(at the very bottom, above Guilds)

"Skills to use over your party can be accessed at the top of the Menu tab. "

In the app, go to the Menu button on the bottom right corner, and choose the first menu item: Use Skills

**Comment by rslee0** [comment]
I also stopped seeing any equipment in the iOS app once I hit level 10 and became a mage. I buy all equipment using the web app.

**Comment by vIiRuS** [comment]
This was an issue that existed for people with the mage class. It's fixed in the next update.
