### ISSUE TITLE
South African App Store

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitrpg-ios#161]
Copied from https://github.com/HabitRPG/habitrpg-mobile/issues/103

> Evidently there's a whole separate store for SA?? (see request at https://twitter.com/addamrosy/status/372442237403402240 ) What other countries is the case for?

> oi, we have to come up with a localized EULA to release to other countries http://gyazo.com/c23f28c2099495cfbf317780055b699a . may have to ping vicky soon

> see: http://t.co/rJe8O5r5rB

**Comment by vIiRuS** [comment]
As the original tweet with the request is gone, I'm not 100% sure what the original problem was.

But I checked iTunes connect and there is a checkmark next to "South africa" (and every other country available). So I guess this is done?
