### ISSUE TITLE
Collection quest status no longer showing up in most recent builds

### ISSUE THREAD

**Issue by Shadallark** [HabitRPG/habitrpg-ios#164]
At some point in the last nine days (since August 9th) a change made to the system causes the Party progress on Collection Quests to not show up.

If I view the party screen using an older build from the 9th or earlier the Collection Statuses show up, but if I use the most recent builds the rows for them show up but no information is displayed.

![img_0382](https://cloud.githubusercontent.com/assets/13031092/9355688/c6da88ac-4651-11e5-8d96-e3fe24ced612.PNG)
![img_0383](https://cloud.githubusercontent.com/assets/13031092/9355687/c6d9ba9e-4651-11e5-8416-db59ce8780cd.PNG)

**Comment by Shadallark** [comment]
For some reason the `UILabel *authorLabel = (UILabel *) [cell viewWithTag:1];`command sets authorLabel to `nil`as does the similar line `UILabel *textLabel = (UILabel *) [cell viewWithTag:2];`in the configure cell method.  Not sure why this is yet.

**Comment by Shadallark** [comment]
This is especially strange since the cell is showing that it has a label (text label) with a tag of 1 and a label (detail text label) with a tag of 2.
![cell_collectionquest_tag_1](https://cloud.githubusercontent.com/assets/13031092/9423743/5ce1ba0c-48a8-11e5-981d-e4d889fed5a5.png)
![cell_collectionquest_tag_2](https://cloud.githubusercontent.com/assets/13031092/9423744/5ce230c2-48a8-11e5-9f5d-f2d67158fa1c.png)
I am going to see what happens if I add new labels to the Storyboard and try to connect to them instead.

**Comment by vIiRuS** [comment]
Hey Shadallark,

I fixed this on the train yesterday and then forgot to push it. Will try to do that later today. The solution was that this is a "right drtail" cell and we can use the normal "textLabel" and "detailTextLabel" labels

**Comment by Shadallark** [comment]
Sounds good @vIiRuS .  I will go back to other things I am working on.

**Comment by Shadallark** [comment]
This has been resolved by commit 27af736 from @vIiRuS .
