### ISSUE TITLE
party sometimes doesn't load

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitrpg-ios#173]
Had a report in which the party view was empty for a user that is in a party.

**Comment by vIiRuS** [comment]
This issue seems to appear, when a user leaves their old party and joins a new one.

**Comment by rslee0** [comment]
I can't get the new party data to load at all. The Party option on the Menu screen shows the green "new content" dot but the Party screen just says "No party data". Problem persists after Clear Cache, Reload Content, kill/restart app, restart iPhone. Had to accept the party invitation and then a couple of days later a quest invitation via the web app.
