### ISSUE TITLE
Notifications for Due Tasks

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#174]
It would be nice to receive a notification about tasks (for example, when you have a To-Do that is due that day).

**Comment by Shadallark** [comment]
I have started working on this issue and will post my preliminary solution in the next few days.  My solution allows people to set reminders for To-Do items as well as the typical daily reminder.

**Comment by vIiRuS** [comment]
When I started doing some work on this a while ago, I had the problem that local notifications can not me scheduled every X days but only every hour/day/week/etc. Do you have a plan on solving that?

And as we eventually want to save the reminders in the website database to have them on all devices/on the website itself, it would be great if you could show us the core data entity for feedback (to ensure that it will be compatible with the future plans.

Thanks!

**Comment by MathWhiz** [comment]
If this is finished, can this be closed?
