### ISSUE TITLE
checking off item and scrolling away can cause item to appear somewhere else

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitrpg-ios#175]
When checking off a task or checklist item and scrolling away before the network request finished, it will then appear in the place of a different task. (Most likely due to reused cells) scrolling away and back to that task fixes the problem

**Comment by lemoness** [comment]
I believe I encountered this - does this screenshot seem to be an example? (T stretch belongs to a checked-off Daily called "stretches.") If it's separate, let me know and I will create a new ticket. 
![img_3673](https://cloud.githubusercontent.com/assets/3494081/10477655/bf6d6a4e-720c-11e5-83ca-0834982623ad.PNG)

**Comment by vIiRuS** [comment]
Probably the same issue

**Comment by lemoness** [comment]
Not encountering this any more - I will keep an eye out.
