### ISSUE TITLE
Support for markdown 

### ISSUE THREAD

**Issue by dmitryUX** [HabitRPG/habitrpg-ios#176]
See how ```**word**``` does not do anything on the iOS client (v.1.0.2 on iOS 8.4.1). 
Related to #85. 

![markdown in habitica - bug](https://cloud.githubusercontent.com/assets/916215/9560920/3461c586-4de4-11e5-90e7-86881d53496f.png)

**Comment by dmitryUX** [comment]
Interestingly enough, in the case of _Italics_, it works _sometimes_.
![markdown_in_habitica](https://cloud.githubusercontent.com/assets/916215/9598099/fe359b80-503c-11e5-94ec-4c7f5c7e2812.png)

**Comment by vIiRuS** [comment]
It seems that the problem is caused when the markdown sequence is followed by punctuation instead of whitespace. Will be fixed.
