### ISSUE TITLE
Quest Participants - statuses are not displayed

### ISSUE THREAD

**Issue by dmitryUX** [HabitRPG/habitrpg-ios#178]
Statuses for Quest Participants (pending/accepted etc.) often are not displayed. 
Interestingly enough: 
- when you pull up and down on this view - **some** statuses will become visible
- when you tap on a party member for whom status is not displayed yet - his/her status will become visible 

Reproduced with app v1.0.2 on iOS v8.4.1.  

![party_quest status - bug](https://cloud.githubusercontent.com/assets/916215/9565129/30da3da6-4e72-11e5-8fc4-c0237277de26.png)

**Comment by Shadallark** [comment]
On the iPad the statuses become visible if the device is rotated.

**Comment by dmitryUX** [comment]
This _duplicate_  and is fixed by #169.
