### ISSUE TITLE
Suggestion: Compatibility with iPhone's "push" notifications

### ISSUE THREAD

**Issue by gigantera** [HabitRPG/habitrpg-ios#185]
Hey, habitica staff,
I've been trying to merge all my to-dos to the habitica app, but as we all know, some things need to be done at a certain date, and a certain hour. It would be really nice if we could have habitica "push" reminders of this special to-dos, programmed to specific hours! It would be easier to remember and we would finally be able to get rid of the calendar native app. 
Thanks for reading,
-Luiza Dornelles

**Comment by vIiRuS** [comment]
This is planned and mentioned in #174
