### ISSUE TITLE
[v 1.1 (68)] Checklist Issues

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#189]
I noticed several issues with checklists in this new version. Some of these may need separate tickets; just let me know.

1) When I try to check off an item in a checklist, it appears that nothing has happened. Refreshing the website reveals that it did in fact successfully check the item.

2) After syncing the app, the Dailies with checklists that I had tried to check off lost their left-side checklist indicators:
![img_3493](https://cloud.githubusercontent.com/assets/3494081/9870369/3078e5d0-5b40-11e5-8007-45b1bd3cc034.png)
![img_3494](https://cloud.githubusercontent.com/assets/3494081/9870372/3334a020-5b40-11e5-92d3-d93f949d374b.png)

 After syncing again, some checklist indicators returned, but others did not:

![img_3496](https://cloud.githubusercontent.com/assets/3494081/9870422/8bd7b9d8-5b40-11e5-8875-243783708d5a.png)

3) At one point a checklist item that I had not checked on the mobile app or the website displayed as checked off. Refreshing the website confirmed that it was not really checked off.

![img_3497](https://cloud.githubusercontent.com/assets/3494081/9870448/bd464c6e-5b40-11e5-98da-ad713ab446a5.png)

**Comment by lemoness** [comment]
(Note before you panic - I removed the names of my Dailies manually. They display normally in the app.)

**Comment by vIiRuS** [comment]
The way it currently works (at least that is what i believe happens.) is that the header either snaps back down or slides away depending on the position jt has when you stop scrolling. I thought it was a good/fine idea whe. Implementing but i'm not so convinced after using it a bit. Will probably change it to something that takes the scroll direction into account (so slowly scrolling it away would cause it to hide and slowly scrolling it in would cause it to show after the scroll end). Does that sound like a better option?
