### ISSUE TITLE
 [v 1.1 (68)] Scrolling Inconsistent

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#190]
Sometimes when scrolling up and down very slowly and then releasing, the header will "stick" in a new location rather than scrolling off the screen. In the screenshot below (Habit names removed for privacy), the yellow task is second from the top, but the first task is hidden by the header:

![img_3500](https://cloud.githubusercontent.com/assets/3494081/9870536/aea756b6-5b41-11e5-89f0-fa8c8254e9ce.png)

**Comment by vIiRuS** [comment]
The way it currently works (at least that is what i believe happens.) is that the header either snaps back down or slides away depending on the position jt has when you stop scrolling. I thought it was a good/fine idea whe. Implementing but i'm not so convinced after using it a bit. Will probably change it to something that takes the scroll direction into account (so slowly scrolling it away would cause it to hide and slowly scrolling it in would cause it to show after the scroll end). Does that sound like a better option?

**Comment by lemoness** [comment]
Yes, I think so! Several times it got trapped somewhere in the middle, so that there was an empty gap where the tasks were scrolled down but the header was not displayed.

**Comment by lemoness** [comment]
SO, unfortunately the header behavior is still quite choppy in the newest version (86). Now when it gets stuck, however, it is in random positions, often with inconsistent spacing:
![img_3752](https://cloud.githubusercontent.com/assets/3494081/10624089/2b4e17da-774a-11e5-8eec-13c6b9d9e81c.jpg)
![img_3753](https://cloud.githubusercontent.com/assets/3494081/10624090/2b587b6c-774a-11e5-85c2-584630ad161d.jpg)
![img_3754](https://cloud.githubusercontent.com/assets/3494081/10624091/2b5ae2b2-774a-11e5-8c1b-e9aea6ac202d.jpg)
![img_3755](https://cloud.githubusercontent.com/assets/3494081/10624092/2b6d1ffe-774a-11e5-92f4-e69fa062acc3.jpg)
![img_3758](https://cloud.githubusercontent.com/assets/3494081/10624087/2b4bc688-774a-11e5-9004-359cc3835e6c.jpg)
![img_3759](https://cloud.githubusercontent.com/assets/3494081/10624088/2b4df0b6-774a-11e5-894d-2629364dbae9.jpg)
 Also, one time the header got stuck as a light purple, no matter where I was in the scrolling:
![img_3757](https://cloud.githubusercontent.com/assets/3494081/10624106/4558ce2c-774a-11e5-9726-e06e2ec1a4b4.jpg)

**Comment by vIiRuS** [comment]
The light purple is fixed and I believe the stuck in between too. The latter only affected ios 7. My current fix might cause the header to jump open/close instead of animating (although it didn't in my testing), but I don't have that much control over that, as it's iOS 7 doing strange things.
