### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by revolter** [HabitRPG/habitrpg-ios#212]
I forked and cloned this repository, ran `pod install`, opened `Habitica.xcworkspace` and when building the project I get these errors:

    .../Pods/FontAwesomeIconFactory/FontAwesomeIconFactory/iOS/NIKFontAwesomeImageView.m:166:21: Unknown type name 'NSColor'
    .../Pods/FontAwesomeIconFactory/FontAwesomeIconFactory/iOS/NIKFontAwesomeImageView.m:170:37: Unknown type name 'NSColor'

_The `...` replaces my computer's related part of the absolute paths_

**Comment by vIiRuS** [comment]
This probably was because of old dependencies. I updated the Podfile.lock to include a version of FontAwesomeIconFactory that includes a fix for this. if you pull again and use `Pod update` it should work.

**Comment by revolter** [comment]
Thanks! I'll try this as soon as I have some time, most probably tonight. I'll close this if the build works.
