### ISSUE TITLE
Issues with time.

### ISSUE THREAD

**Issue by Wenonah007** [HabitRPG/habitrpg-ios#215]
I checked myself out of the Tavern yesterday morning. Then had a phenomenal day. I finished all 25 of my daily tasks. I was excited to see how I had done on my solo quest. The program had check me back into the Tavern overnight. When I checked out, every single one of my dailies for today was checked. It is almost as if parts of Habitica lost a day. In addition, all of the drops from yesterday appeared this morning.

**Comment by vIiRuS** [comment]
did you check yourself out of the tavern from the website or the iOS app? Is it possible the network request failed and it never actuallly checked you out of the tavern?
