### ISSUE TITLE
[v 1.1 (78) iPhone] Incorrect Name Colors in Party Chat

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#218]
In Party Chat, the name colors are incorrect. (I am orange instead of purple, for example.) In Tavern Chat, the name colors display correctly.
![img_3644](https://cloud.githubusercontent.com/assets/3494081/10448294/a9c09a1c-7140-11e5-9fab-26b4dd938210.PNG)

**Comment by vIiRuS** [comment]
The colors in the party chat are the class colors. But it does seem confusing, so I'll change it.
