### ISSUE TITLE
[v 1.1 (78) iPhone] Strange tutorial behavior

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#220]
The non-Justin parts of the tutorial appear at seemingly-random times while navigating through the app. It's not clear to me what triggers them, especially since they appear on multiple screens. Additionally, some of them don't quite highlight or match up properly.
![img_3646](https://cloud.githubusercontent.com/assets/3494081/10448496/0a15eb46-7142-11e5-9741-1b6a7adad374.PNG)
![img_3647](https://cloud.githubusercontent.com/assets/3494081/10448498/0a1863ee-7142-11e5-9c77-06a29753df63.PNG)
![img_3648](https://cloud.githubusercontent.com/assets/3494081/10448495/0a13322a-7142-11e5-884b-22db7ea3be12.PNG)
![img_3649](https://cloud.githubusercontent.com/assets/3494081/10448502/0a26fe86-7142-11e5-859e-220db95c2698.PNG)
![img_3650](https://cloud.githubusercontent.com/assets/3494081/10448500/0a214e1e-7142-11e5-9671-c8991eab7662.PNG)
![img_3651](https://cloud.githubusercontent.com/assets/3494081/10448497/0a1748a6-7142-11e5-90bb-7bdcee601f1d.PNG)

**Comment by lemoness** [comment]
I think they feel a little better in Justin's speech bubble, but we're not quite there yet. I'm going to try demoing it with some other people to get feedback. As a side note -- in the speed bubbles, they need periods at the ends of the sentences.

**Comment by lemoness** [comment]
Okay, after doing some demoing and playing around with it a bit more, here are my thoughts.

The reason that the tab-based Justins are so successful is the same reason that the coach marks feel jarring. 

The tab-based Justins pop up based on a specific action that the player takes. There's a 1:1 relationship between tapping on something and getting information about it. When I tap on the Rewards tab, Justin pops up and tells me about Rewards. It's very intuitive and, since I was curious about Rewards when I tapped on that tab, it feels satisfying.

On the other hand, the coach marks have no clear reason that they pop up. It's not triggered by the user tapping on something related to the coach marks, so it just feels like information is being randomly and suddenly thrown at you, disrupting your experience.

I think the way to fix this will be by having some sort of visual indicator (a pulsing glow or something) around all the interactive items that will bring up the prompts.

So, when you first get shuffled to the To-Do Screen, you then see a glow around the other tabs, around the +, on the sample task, etc. When the user taps it, they get the info. 

Does that seem feasible?

**Comment by vIiRuS** [comment]
It is feasible. I'm not 100% sure how to make it work, but it should be doable.

**Comment by lemoness** [comment]
Went through the tutorial, and the customized tasks page is quite bland. Perhaps if the options were centered it would look better. Also is there a way to add some images to make it more appealing, like maybe the avatar at the top?
![img_3734](https://cloud.githubusercontent.com/assets/3494081/10574051/6540ad06-7608-11e5-9bb6-35a1f2dde3b9.jpg)

**Comment by lemoness** [comment]
Another thing that I noticed - although the sample Habits and Dailies are added, the Sample To-Dos are not. Regardless of which they choose, the top of the list should still be "Joined Habitica (Check me off!)"
![img_3735](https://cloud.githubusercontent.com/assets/3494081/10574113/d01d4710-7608-11e5-956f-5cad199d7ebf.jpg)

Additionally, the previous sample Habits remain, but they should not, because they may not be relevant (and in some cases, like with Health + Wellness, certain Habits like "Junk Food" are duplicated).

**Comment by vIiRuS** [comment]
Is it possible the "dated" filter is active for todos? 
The old sample tasks are set by the server, so we would have to change them there.
