### ISSUE TITLE
[v 1.1 (77) iPad] Cannot Log out

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#227]
On the iPad, the logout button is hidden by the header, and when you try to pull down to make it visible, it bounces back under the header, making it impossible to log out.
![img_3665](https://cloud.githubusercontent.com/assets/3494081/10450614/51147248-7150-11e5-9423-1f81b035c8e4.jpg)

**Comment by vIiRuS** [comment]
This is caused by #219
