### ISSUE TITLE
[v 1.1 (77) iPad] Improve Spacing

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#228]
The iPad could definitely use an improved layout to reduce the odd spacing. Notice, for example, all the white space under the Login screen, and how tiny the header/avatar looks (especially without a background). The tabs on the bottom are clustered strangely in the center, too. 
![img_3664](https://cloud.githubusercontent.com/assets/3494081/10450771/431d221a-7151-11e5-81ca-20e5a0ee6fc7.jpg)
![img_3662](https://cloud.githubusercontent.com/assets/3494081/10450770/4319fa86-7151-11e5-9b34-cd16d5479e9e.jpg)

**Comment by vIiRuS** [comment]
as of https://github.com/HabitRPG/habitrpg-ios/commit/0569afba286a22fddbdecce8df38d764a36e8b84 also has slightly bigger header for ipad.

**Comment by lemoness** [comment]
This is much better now!
