### ISSUE TITLE
[v 1.1 (80) iPhone] Tags sometimes uncheck

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#240]
Sometimes when I select multiple tags, one or more of the tags uncheck themselves when I go back to the task screen. It happens most of the time, but unfortunately not consistently - on one instance, both tags stayed selected.

**Comment by lemoness** [comment]
Unfortunately, in version 84 this has been happening again for me, especially for To-Dos.

**Comment by lemoness** [comment]
A quick summary of how this has been behaving for me in the most recent version (85):


Marked tag 1: “Habitica”
Displayed: 1 Filter
Showed only tasks in the “Habitica” tag
Marked tag 2: “Priority”
Displayed: 1 Filter
Showed all tasks in the “Habitica” tag, NOT just the ones that were also in Priority
Back to tags – “Priority” was unselected
Marked tag 2: “Life”
Displayed: 1 Filter
Showed all tasks in the “Habitica” tag, NOT just the ones that were also in “Life”
Unmarked “Habitica”
Displayed 0 Filter
Displayed all tasks, as expected.
Marked tag 1: “Priority”
Displayed: 1 filter
BUT did not show the correct tasks in the “Priority” tag
When navigating back to the task page, the tag “Habitica” was the only tag selected (the first tag in the list)
Unselected “Habitica” and selected “Writing” and “Life.” As soon as I went to the tasks page, “Writing” and “Life” were unselected and “Habitica” was reselected.
Deselected all tags. 
Confirmed on To-Do page that all tasks were visible, and no filters were selected. Refreshed.
Went to the tag page and selected two at once ("Habitica" and "Priority"). When I went to the task page, only "Habitica" was selected.

I hope this helps!

**Comment by vIiRuS** [comment]
So the only tag you can ever select is “Habitica”? Is this also your first tag?



On 20 October 2015 at 10:32:19, lemoness (notifications@github.com) wrote:

A quick summary of how this has been behaving for me in the most recent version (85):

Marked tag 1: “Habitica”
Displayed: 1 Filter
Showed only tasks in the “Habitica” tag
Marked tag 2: “Priority”
Displayed: 1 Filter
Showed all tasks in the “Habitica” tag, NOT just the ones that were also in Priority
Back to tags – “Priority” was unselected
Marked tag 2: “Life”
Displayed: 1 Filter
Showed all tasks in the “Habitica” tag, NOT just the ones that were also in “Life”
Unmarked “Habitica”
Displayed 0 Filter
Displayed all tasks, as expected.
Marked tag 1: “Priority”
Displayed: 1 filter
BUT did not show the correct tasks in the “Priority” tag
When navigating back to the task page, the tag “Habitica” was the only tag selected (the first tag in the list)
Unselected “Habitica” and selected “Writing” and “Life.” As soon as I went to the tasks page, “Writing” and “Life” were unselected and “Habitica” was reselected.
Deselected all tags.
Confirmed on To-Do page that all tasks were visible, and no filters were selected. Refreshed.
Went to the tag page and selected two at once ("Habitica" and "Priority"). When I went to the task page, only "Habitica" was selected.

I hope this helps!

**Comment by lemoness** [comment]
I could select tags that were not my first tag ("Habitica") but only one at
a time.

**Comment by vIiRuS** [comment]
What happened when you tried to check more than one?
