### ISSUE TITLE
Filter should indicate when checked

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#242]
(This can be after 1.1.1)

There should be some indication that a tag or filter is indicated. Maybe a counter in the corner?

**Comment by lemoness** [comment]
In version 84, there's an issue with the Filters for To-Dos (it has not happened yet for Dailies or Habits) where the number of filters listed is always 1 more than the number of filters actually selected.
![img_3727](https://cloud.githubusercontent.com/assets/3494081/10573519/cce0f2b2-7604-11e5-96d8-b32ab2c1e2df.jpg)
![img_3728](https://cloud.githubusercontent.com/assets/3494081/10573534/e15a8a28-7604-11e5-9dea-a4aed4f22a43.jpg)

**Comment by lemoness** [comment]
Also, if it is possible to have plurals with the number of filters selected, that would be great ("2 Filter" seems odd), but that's low priority if it's difficult.

**Comment by vIiRuS** [comment]
It already is supported but smart me went "2 filter is totally the plural". Will fix it.

**Comment by vIiRuS** [comment]
The "dated" is counted as active filter. (As with due/grey and positive/negative for dailies and habits.)
