### ISSUE TITLE
TUTORIAL [1.1 (80)] - Justin's image does not load at the beginning

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#243]
Justin's image does not load at the beginning of the tutorial. Also, the "Enter" is below the fold, so it's hidden. It should be on the same screen. 
![img_3686](https://cloud.githubusercontent.com/assets/3494081/10530756/8d615b42-735f-11e5-9904-5aaa2ff4d589.jpg)
![img_3687](https://cloud.githubusercontent.com/assets/3494081/10530755/8d5d08e4-735f-11e5-82fc-7e09542b517e.jpg)

**Comment by lemoness** [comment]
The only version of Justin that displays is a very large version of him that is a little blurry (probably because of the resizing) and lacks his equipment:
![img_3732](https://cloud.githubusercontent.com/assets/3494081/10573789/e498752c-7606-11e5-85fa-22d99ab2603d.jpg)

It would be nice to have the standard Justin if possible, rather than the edited one.

**Comment by vIiRuS** [comment]
Ok. With or without the question mark?
