### ISSUE TITLE
TUTORIAL [1.1 (80)] Avatar Customization Comments

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#244]
Right now, the Avatar Customization is better, but it's still not fully clear that you need to scroll down. Some possible solutions:

1. Include a gradient so that the bottom of the screen is fading, indicating that you should scroll.

2. Have some sort of arrow or visual indicator to scroll.

3. Make each section into tabs.

Also, we need to either include the flower in the selection, or remove it from the starting character.

**Comment by lemoness** [comment]
Some additional comments from the user test:

"It's weird the way the text disappears when you scroll."
"I feel like each section should have borders of some kind."

**Comment by lemoness** [comment]
So, unfortunately the gradient option looks too subtle over the images - I think if we could get the text at the bottom in the gradient, it would be more obvious. Is there a way you can move the text a little higher so that it will not just end on the images, or should I shorten the opening text?

![img_3733](https://cloud.githubusercontent.com/assets/3494081/10573909/aaa37302-7607-11e5-8bd8-4488f1c860bd.jpg)

**Comment by vIiRuS** [comment]
Unfortunately not an option. We have 6 device sizes with 8 text sizes each. So the fold will always be diferent and adjusting the text so that it fits on one device won't help much.
We could move the next and back buttons to the bottom of the scrollview so that the user has to scroll to continue. That should make it more obvious

**Comment by lemoness** [comment]
That may work, but I'd like to be even more obvious if we can. Is there a way to do an arrow or a scrollbar or something like that?

If not, let's add the line "Scroll down to select your skin color, hair, and shirt." above "Choose your skin color!" At least it's better than nothing.

People often don't read, though, so if we can possibly do a visual solution, that would be best, especially since we don't have that line localized, which may cause trouble.

**Comment by vIiRuS** [comment]
![simulator screen shot 21 oct 2015 17 04 46](https://cloud.githubusercontent.com/assets/298062/10640659/eadaed3c-7815-11e5-9077-4ad2218443e8.png)

it now also flashes the scrollbar when the view appears. (can't display it permanent, as the scrollview doesn't allow that)

**Comment by lemoness** [comment]
The arrow is great! Will do a user test today.

**Comment by lemoness** [comment]
The arrow works well - would actually also like the gradient + arrow on the part when you select the parts of your life that you want to improve, too.

**Comment by lemoness** [comment]
At the base of this slide, we definitely also need the gradient and arrow:

![img_3791](https://cloud.githubusercontent.com/assets/3494081/10674809/c4f34a96-78b1-11e5-9315-b6225d039abf.jpg)

**Comment by lemoness** [comment]
Found a bug with this arrow - it prevents you from selecting Creativity (the final type), presumably because it is at the bottom of the list and the gradient is preventing that.

**Comment by lemoness** [comment]
![slack for ios upload png-3](https://cloud.githubusercontent.com/assets/3494081/10687365/76994e02-7921-11e5-9709-f6ff8859160c.jpeg)
