### ISSUE TITLE
[v 1.1. (84) iPhone] Earned 0 Experience and Gold

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#250]
I've encountered a notification telling me that I've earned 0.00 Experience and 0.00 Gold during two types of event:

1) Checking off a blue negative Habit. (Note that it happened each time I checked off that Habit, but has not happened with other negative Habits, including blue ones.)

2) Checking off the new sample Dailies from the customization.

**Comment by vIiRuS** [comment]
1) this could potentially mean that the task has a difficulty of 0. do you know what created it? And does this also happen from the website?

2) in this case the sample items did have a difficulty of 0. fixed that though.

**Comment by lemoness** [comment]
1) I created the task on the website, but I have never experienced the 0.00 bug on the website.

**Comment by lemoness** [comment]
This has now happened with every sample task on the newest iPad build (90) for an account that was created on the iPad, albeit in the last version. The website sample tasks behave normally. I'm going to create a new account and see if it still happens.

Note that although 0.00 is displayed, gold and XP are actually awarded.

**Comment by lemoness** [comment]
Working successfully in an account created in the latest build! I'm going to close this unless I encounter it again.
