### ISSUE TITLE
[1.1 (89) iPhone] Wrong Rewards Available

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#257]
Even though this is a brand new character, the only rewards available are the top-level Warrior armor and 1 of the four Festival warrior items.

![slack for ios upload png](https://cloud.githubusercontent.com/assets/3494081/10652684/711d7166-780d-11e5-8ee7-43b7bb7a6ca4.jpeg)

![slack for ios upload png-2](https://cloud.githubusercontent.com/assets/3494081/10652728/d0b088c0-780d-11e5-910d-9da49f2d6098.jpeg)

**Comment by lemoness** [comment]
This happened again with a user's new test account.

Settings > Logout of Lemoness account > Register for a new account (without killing the app in the middle)

First, no equipment was available, probably due to caching issues:
![img_3795](https://cloud.githubusercontent.com/assets/3494081/10674524/39b5e4d0-78b0-11e5-8087-8c2986fed60c.jpg)

Then, after clearing the cache several times, items were available, but they were too advanced:

![img_3806](https://cloud.githubusercontent.com/assets/3494081/10674565/7a9f1eda-78b0-11e5-85e1-57275e5fe35f.jpg)


This bug should definitely be fixed before submission, because it strongly affects the experience of ew users.

**Comment by carroux** [comment]
I've also encountered this bug, but on the old iOS app. As shown below, I was able to purchase and equip Chain Mail and Sapphire Blade without having first purchased Leather Armor and Morning Star, respectively.

Every time I completely closed the app (swiping up to close the app from the multitasking view in iOS) and reopened it, the items available in the store changed. It never showed items I had already purchased, but it would show items that I hadn't purchased the prerequisites for.

![img_8808](https://cloud.githubusercontent.com/assets/5157761/10992931/c74d85f8-841f-11e5-8bb8-5baab73f2dc3.PNG)
![img_8811](https://cloud.githubusercontent.com/assets/5157761/10992932/c74ebba8-841f-11e5-8007-eb2026a83592.PNG)
![img_8809](https://cloud.githubusercontent.com/assets/5157761/10992933/c74f9ea6-841f-11e5-897e-832864e19ab1.PNG)

**Comment by carroux** [comment]
To clarify, it never showed more than one item from a category (e.g. only one weapon at a time), excluding special holiday items. Whenever I completely closed then reopened the app, it would display a seemingly random item from each category that I hadn't purchased yet. The items in rewards remained constant when I minimized the app and returned to it later--it was only after completely restarting the app that the items would shuffle.

I've experienced this behavior in the new version of the iOS app in addition to the old one.

**Comment by vIiRuS** [comment]
Does this bug also occur on the most recent app version? ( 1.1.1 )

**Comment by carroux** [comment]
@vIiRuS Yep, I'm still getting the bug in the latest version (1.1.1) running iOS 9.1

**Comment by lemoness** [comment]
Another report of this:

iOS Version: 9.2
Device: iPad2,5
App Version: 1.1.2
User UUID: 347de967-8df4-457f-a6f3-05a7483f3399

"I'm trying to buy level one equipment for my avatar, the basic leather and wooden gear, but it's only showing high level things. Plate armor and things. I'm only level one, and I can see the armor that I should be able to buy on my husband's account. But I don't have that. I bought the practice sword and then everything went high level."

**Comment by lemoness** [comment]
Another report for this: 

"iOS Version: 9.2
Device: iPhone4,1
App Version: 1.1.2"
