### ISSUE TITLE
Center tutorial text on first slide

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#262]
A small tweak - it would look better on the first slide (the first impression that a new user gets) if the text was centered:

![img_3789](https://cloud.githubusercontent.com/assets/3494081/10675202/baaa43b2-78b3-11e5-98be-59f1e0b136b4.jpg)

**Comment by vIiRuS** [comment]
In theory an easy fix, but the readability while the text animates suffers a lot. It's very hard to read the line that is currently being displayed (as it is constantly getting wider causing everything to shift if it is centered) that I found it more annoying than the better looks was worth it.

**Comment by lemoness** [comment]
Fair enough!
