### ISSUE TITLE
Coachmark Highlights Wrong Thing

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#269]
This was not a new account. I logged into a preexisting account and it popped up the tutorial, including an incorrect coach mark.

![img_3809](https://cloud.githubusercontent.com/assets/3494081/10680769/8e9773de-78d7-11e5-95c7-52c034e071fd.jpg)
![img_3810](https://cloud.githubusercontent.com/assets/3494081/10680773/90e55b2e-78d7-11e5-9a3b-1e3a03b456bf.jpg)

**Comment by vIiRuS** [comment]
Was eat junk food the first habit or are there others above that?

**Comment by lemoness** [comment]
Aha! There were four other Habits on top of it. It's probably highlighting the top Habit.
