### ISSUE TITLE
Friend Finding Issues 

### ISSUE THREAD

**Issue by TheDarkling** [HabitRPG/habitrpg-ios#276]
I have been trying to invite friends who have created accounts already to my party and whenever I type in their username it says they are not found. I even have personal messages with them and it still says they are none existent. I have copied and pasted the username in and it still says they can't be found. This has happened with three of my friends. Please fix this soon.

**Comment by vIiRuS** [comment]
Hey,

Can you specify where you typed in there name?

**Comment by TheDarkling** [comment]
I was on the party page and had the invite friends pop-up open. On the invite existing user tab I type their name into the text box there.

**Comment by TheDarkling** [comment]
Nevermind, I did not know about the user ID not being the Username
