### ISSUE TITLE
Pets are Incorrectly Labeled as "Spooky"

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#280]
When you click on pets, they are incorrectly labeled as "Spooky."

![slack for ios upload png-4](https://cloud.githubusercontent.com/assets/3494081/10961054/3d2cdf80-833f-11e5-81fe-e009774675ef.jpeg)

**Comment by nivl4** [comment]
@lemoness what should be the expected behaviour/label? "Rat" instead of "Spooky"?

**Comment by lemoness** [comment]
Yes, it should say "Rats" instead!
