### ISSUE TITLE
iOS Update 1.1 shows as "${PRODUC..."

### ISSUE THREAD

**Issue by Shirk** [HabitRPG/habitrpg-ios#284]
After Updating the Habitica app to the 1.1 release it now shows on my SpringBoard as "${PRODUC...".

For me that looks like something went wrong in the Xcode-Build but in that case: how did it pass Apples review process that way?

**Comment by Shirk** [comment]
Here's a Screenshot:
![wrong App Name](http://i.imgur.com/bvOfw2r.jpg)

**Comment by vIiRuS** [comment]
What language is your device set to?

**Comment by Shirk** [comment]
German

**Comment by vIiRuS** [comment]
reproduced it and fixed it. It only happens in translations. Will upload a fixed version to apple today and it's hopefully available tomorrow

**Comment by Shirk** [comment]
Thanks for the quick action - I wasn't aware that app names could be localized too..
Otherwise great job on 1.1 :+1:

**Comment by Shirk** [comment]
Sorry to bother but notifications (i.e. the daily reminders) still use ${PRODUCT_NAME}.

**Comment by vIiRuS** [comment]
Can you try to disable and re-enable the notifications? I'm not sure at what point ios stores the name of the app for notifications. Maybe it had the name cached from version 1.1

**Comment by Shirk** [comment]
Yes, that worked but I had to go all the way of removing and reinstalling the app. 

* disable / enable in app :-1:
* disable / enable in preferences :-1:
* reinstall Habitica :+1:
