### ISSUE TITLE
Kickstarter backers: gear missing from store and pet is invisible

### ISSUE THREAD

**Issue by Olathe** [HabitRPG/habitrpg-ios#290]
On Habitica version 1.1.1 (96):

* The [Kickstarter backer gear](https://habitica.wikia.com/wiki/Kickstarter#Backer_items) isn't listed in the rewards and so cannot be purchased.

* The Cerberus Pup Pet is available and can be equipped, but it's invisible.

* The Ethereal Lion Mount works fine.

# Rewards on desktop browser
![Desktop browser rewards](https://cloud.githubusercontent.com/assets/412242/11027792/b8848486-8686-11e5-8ac5-c8e85d7b6405.png)

# Rewards on iOS app
![iOS rewards](https://cloud.githubusercontent.com/assets/412242/11027785/b150d5ca-8686-11e5-9de3-754378ff5fc8.png)

---
# Rare pets on desktop browser
![Desktop rare pets](https://cloud.githubusercontent.com/assets/412242/11044489/343559de-86f0-11e5-9660-bab57d03efad.png)

# Wolf pets on iOS app
![ios wolf pets](https://cloud.githubusercontent.com/assets/412242/11044514/521813f6-86f0-11e5-975e-1ab9f452e3f7.png)

**Comment by lemoness** [comment]
Thanks very much for reporting this! We'll investigate it.

**Comment by crookedneighbor** [comment]
The Kickstarter gear might be gifs.

**Comment by lemoness** [comment]
I believe they are in fact gifs.

**Comment by nivl4** [comment]
@lemoness gif support for pets added in https://github.com/HabitRPG/habitrpg-ios/pull/347.

however, I couldn't figure out any info on how image assets are synced to s3.
so a properly sized "Pet-Wolf-Cerberus.gif" file will need to be uploaded to
https://habitica-assets.s3.amazonaws.com/mobileApp/images/ by Habitica staff manually to resolve this issue.

**Comment by crookedneighbor** [comment]
The Pet-Wolf-Cerberus.gif is uploaded to s3.
