### ISSUE TITLE
To-Do list loading circle never disappears, tested on iPhone 5s, iOS 8.4

### ISSUE THREAD

**Issue by gp2015** [HabitRPG/habitrpg-ios#297]
When selecting To-Dos the loading circle appears and never goes away. Screenshot attached.

![habitica_issue](https://cloud.githubusercontent.com/assets/12938113/11604830/b93fd82e-9abf-11e5-91ab-ac9ebd56de92.PNG)

**Comment by vIiRuS** [comment]
This isn't a loading circle. These circles indicate interactive tutorials and are meant to be tapped.

**Comment by gp2015** [comment]
Ah, I thought it was a loading circle because I would see it spin for a bit then become static. Thanks!
