### ISSUE TITLE
Party Member's Stats Reversed

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#325]
(reported via email)

"When checking the stats of a party member, the current/max stats are reversed. 268/140, 34/0
![image1](https://cloud.githubusercontent.com/assets/3494081/12545621/c8f06430-c2f8-11e5-9a23-06eac08a27e0.PNG)

iOS Version: 9.2
Device: iPhone6,2
App Version: 1.1.2
User UUID: 50e5c08f-7315-4bed-b882-1ddb735865b3"

**Comment by vIiRuS** [comment]
See #133
