### ISSUE TITLE
feed pet displays duplicate items

### ISSUE THREAD

**Issue by mbillimoria** [HabitRPG/habitrpg-ios#369]
When feeding a pet, sometimes multiple food items appears that actually do not exist - they often lack a description (e.g. "Meat" or "Chocolate")

When feeding your pet an item that doesnt exist the status bar produces "Your pet eats the (null) but doesn't seem to enjoy it."

Steps to reproduce
1.) Have some food items in your inventory
2.) Tap Menu -> Pets
3.) Choose a Pet to feed and Tap Feed
4.) Select and item to Feed (normally one without a description)
<img src="https://cloud.githubusercontent.com/assets/19197143/15033306/a7a066f0-12ac-11e6-8ddb-16d710b5b8d3.png" width="350" height="667" />

Actual Result:
Status bar displays "Your pet eats the (null) but doesn't seem to enjoy it."
<img src="https://cloud.githubusercontent.com/assets/19197143/15033307/a7a33c22-12ac-11e6-9743-c26e7014a20e.png" width="350" height="667" />

Expected Result:
Food items that are not in inventory should not be displayed at all

Using iOS App 1.2.2
Tested on iPhone and iPad with same result

**Comment by vIiRuS** [comment]
Do your iPhone and iPad both have the same duplicate items?
What is your Habitica user ID?

**Comment by mbillimoria** [comment]
User ID is
872ce1cd-cc92-4f3c-abaa-f037744a8317
Not sure if I get the same duplicate items on iphone and ipad - will check next time I get a food drop and reply

**Comment by mbillimoria** [comment]
ok - looks like it affects iphone and not ipad - see attached images.
iphone behaviour
![2016-05-13 09 21 36](https://cloud.githubusercontent.com/assets/19197143/15233476/44b197bc-18ec-11e6-92e4-8f550f0670e7.png)
ipad behaviour
![2016-05-13 09 21 04](https://cloud.githubusercontent.com/assets/19197143/15233481/4f63de86-18ec-11e6-977a-60f0e729eef2.png)
