### ISSUE TITLE
Un-checking dailies doesn't remove item drops from inventory

### ISSUE THREAD

**Issue by sbrumb** [HabitRPG/habitrpg-ios#370]
If you check and un-check a daily, your experience and mana return to the previous amounts as expected. If an item dropped, however, it remains in your inventory even after you un-check the daily. As a result, you can repeatedly check and un-check a daily to obtain large amounts of duplicate items, limited only by your daily drop-cap.

Version: Habitica 1.2.3 (124), iOS 9.3.1 (13E238)

Steps to reproduce:
1) Check a daily which drops an item.
2) Un-check the daily.
3) Check the daily a second time.
3) Navigate to Menu > Items 

Expected result: One dropped item appears in the inventory.
Actual result: Two dropped items appear in inventory.

I also tested that that the duplicate items work just like regularly obtained items: using the website, I was able to view the duplicates in my inventory and use them to feed a pet.

**Comment by vIiRuS** [comment]
This is an issue with the server side code and can't be fixed through the client.
