### ISSUE TITLE
Quests are not up to date on party page 

### ISSUE THREAD

**Issue by mbillimoria** [HabitRPG/habitrpg-ios#389]
When visiting the Party Page on iPhone or iPad for the first time each day, the In progress quest is not up to date, often showing the previous quest (esp if the quest had just changed over), or showing the same quest but damage has not been updated. 

A workaround is to leave the party page and then go back to it will update.

Steps to reproduce:
1.) Select Menu -> Party on iPad or iPhone 
2.) Observe that quest details are not up to date
3.) Leave the party section by selecting Habits
4.) Repeat step 1
5.) Observe that the quest detail has now updated.

Expected behavior:
When selecting the Party page, quest data should update straight away. 

My habitica user Id is 
872ce1cd-cc92-4f3c-abaa-f037744a8317

**Comment by vIiRuS** [comment]
Hi,

This issue was resolved with 549756bcf2cc67e21b294a4e404cd1cd5ecf3f09. The next update will include these changes.
