### ISSUE TITLE
add confirmation step to "begin" button for quests

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-ios#487]
Quest owners sometimes click the "Begin" button on a quest before party members have had a chance to accept/reject the invitation because they don't understand what the button is for.

We want to add a confirmation screen that displays this text:
**"Are you sure? Only X of your Y party members have joined this quest! Quests start automatically when all players have joined or rejected the invitation."**
where X and Y are replaced by appropriate numbers.

The buttons on the confirmation screen should be **"Not yet"** and **"Start Now"**

_The website and Android versions of this issue are https://github.com/HabitRPG/habitica/issues/9083 and https://github.com/HabitRPG/habitica-android/issues/804_

**Comment by ashleyng** [comment]
Is it ok if I take this?
