### ISSUE TITLE
Candlestick maker outfit is invisible on avatar and equipment list

### ISSUE THREAD

**Issue by mareinna** [HabitRPG/habitrpg-ios#489]
Posting this here because the "Report a bug" link in the ios app does not work (I do not use the native ios email app.)

Found the candlestick maker outfit in the armoire yesterday. On the ios app it is listed in the equipment list but without the accompanying image. When I equip the outfit, the avatar in the app looks like it is not wearing any armor. The outfit shows up on the avatar and equipment list in the browser, but seems to be invisible in the app.

I have tried deleting the cache and reloading the content. Also tried uninstalling and reinstalling the app. Problem persists.

I am using the most recent version of the app, on ios 10.3.2.

**Comment by SabreCat** [comment]
Hi! I believe I've got this corrected, both for the latest images and for new images going forward. Can you close out of the app, then try again?

**Comment by mareinna** [comment]
I did, and it's there now! Thank you for fixing this so swiftly!
