### ISSUE TITLE
Incorrect feedback when user attempts to purchase off-class seasonal gear

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitrpg-ios#491]
According to a report in admin email, when a user attempts to purchase a Gold-buy seasonal gear item for a different class, they receive an error that they don't have enough Gold--even if they do. It should instead say that they need to change to the class in question before they can buy that item.

**Comment by saraolson** [comment]
Adding this to 1.12 since we're workin on market stuff

**Comment by fiuzaB** [comment]
Can I take this one ?

**Comment by phillipthelen** [comment]
Yes!

Let me know if you need any assistance with it.

-- 
Phillip Thelen
Sent with Airmail
