### ISSUE TITLE
app closes immediately in iOS 11.0.3

### ISSUE THREAD

**Issue by sarahaziziyan** [HabitRPG/habitrpg-ios#495]
Hi there. I recently updated my iOS to v11.0.3(iPhone 5s) and also updated Habitica to v 1.11.3. I'm no longer able to open the app. cause it closes immediately.

**Comment by phillipthelen** [comment]
This iss due to a migration error with the apps local database. Do you know
which version you had before this? Uninstalling the app and reinstalling
again makes it launch correctly again

-- 
Phillip Thelen
Sent with Airmail
