### ISSUE TITLE
Can't clear purple dot by Rewards section (Tutorial related)

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#514]
Rewards tutorial won't trigger, leaving a purple dot on the Rewards section that you can't get rid of... ever :) . 

Saw another report of it in the socialites guild:
"someone in the help guild is being tormented by a purple rewards notification on his rewards tab in the iOS app. "

**Comment by RJ-Clegg** [comment]
Can confirm this bug. Just experienced it now. I can take a look at it, if no one else is busy on it?

**Comment by saraolson** [comment]
@TanderZA @vIiRuS i believe it's open to be claimed! Viirus can confirm when he's back online

**Comment by RJ-Clegg** [comment]
Cool, I'll create a PR this weekend for it and start working on it.
