### ISSUE TITLE
Reordering tasks is glitchy

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitrpg-ios#516]
Reordering tasks causes the items in the list to shift around incorrectly

**Comment by saraolson** [comment]
Optimistically moved this to 1.12 in case we can get it fixed sooner

**Comment by saraolson** [comment]
I was testing this and started moving tasks up and down and after a few reorders i moved one of my tasks up and it turned all the tasks it touched into duplicates of the task i was moving that didnt go away on refresh but after i scrolled down they did change back. I repeated it again by grabbing a negative habit, dragging it up, and it duplicated the habit at the bottom of the list up across all the other habits as i dragged the negative habit over them without releasing. they changed back to normal when i dragged the negative habit down, then changed again when i dragged over again. releasing the negative habit saved the duplicates until i scrolled down then back up

**Comment by saraolson** [comment]
Sometimes when i grab a task to reorder it, it jumps about 1 inch above where my finger actually is

**Comment by saraolson** [comment]
when dragging a task up and down the screen so it scrolls, eventually when i dragged it to the top, around the header where it cant be dropped, my list of tasks got weird. some tasks disappeared leaving blank spaces, while the task i was dragged reappeared in the list faded out

**Comment by saraolson** [comment]
i dragged a task to the left side of the search field and it got a little (+) indicator. when i dropped it, it entered a line of chinese or japanese kanji or something into the search bar

**Comment by saraolson** [comment]
when dragging a task up and down the screen, eventually the task it showed me dragging changed. 

ex: i grabbed 'stop smoking', dragged it up and down a few times, eventually 'give dog medicine' turned faded and would hide itself from the screen. Then when i placed the 'stop smoking' habit, it wouldnt appear, the 'give dog medicine' would reappear where i dropped it. scrolling down then back up showed stop smoking above give dog medicine, like it should (i think? its hard to keep track of where it should have been)
