### ISSUE TITLE
Health potion and armoire have unpin button

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitrpg-ios#519]
In the rewards list, health potion and armoire have the unpin button although they can't be unpinned.

**Comment by saraolson** [comment]
i can still see the unpin button when only the health potion and armoire show before a rewards refresh. we really need to make it so we dont need the user to refresh rewards for items to show. the first time an account goes to rewards all they see is hp potion/armoire, no gear, and its not obvious at all that somethings missing so they could go days without knowing they could buy a training sword?
