### ISSUE TITLE
gold balance should have two decimal places rounded down

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-ios#533]
As described in https://github.com/HabitRPG/habitica/issues/8368, we're trying to make rounding of stats consistent across all platforms.

Currently, the iOS app displays gold as an integer. It should display it with two decimal places, rounded **down**. For example, if your exact gold balance is 79.289, the balance you see on the app should be 79.28.

**Comment by saraolson** [comment]
Regarding inconsistencies, iOS shows the gold count as a truncated '1.34k' when over 999, while the recent discussion on web has that only happening over 9999. However, if we make this change and iOS doesn't truncate like that, people could have gold counts as long at 2362.56 which is a lot of space so hopefully we're okay with this difference for space reasons?
