### ISSUE TITLE
Training sword not removed when resetting account

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#540]
Reset account, training sword stayed equipped to my character. refreshed rewards and saw training sword showed there to purchase but it was constantly grayed out (no way to buy it despite me having enough gold). Other equipment i had bought/equipped was removed.

**Comment by phillipthelen** [comment]
This isn't something happening in the app. Either this is the intended behaviour or the issue should be opened in the server repository.
