### ISSUE TITLE
Equipment from one account showing in the equipment view of another

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#541]
equipment from my main test account (piyorii) was showing in a clear test account, so i had a bunch of armoire items and stuff. when trying to equip one it says 'you do not own this item'. Refreshing doesn't make the items go away.

**Comment by phillipthelen** [comment]
Moved this to 1.14 since this is a very rare bug, that can't really be fixed with the current system but will be fixed when we replace RestKit
