### ISSUE TITLE
[v 1.1 (79) iPad] Tavern Chat Occasionally Cut Off

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#55]
Sometimes, longer Tavern messages are cut off instead of wrapping. (I cross-referenced the website to make sure that they were indeed being cut off.)

![img_2972](https://cloud.githubusercontent.com/assets/3494081/7782149/64539268-00bb-11e5-8501-468a0408633d.PNG)

**Comment by vIiRuS** [comment]
This bug seems to be back in the 1.0 release :/

**Comment by lemoness** [comment]
This has been occurring again on v 1.1 (7) on iPad.

**Comment by lemoness** [comment]
![img_0029](https://cloud.githubusercontent.com/assets/3494081/10507789/f3dc097c-72d7-11e5-85e4-e23d4da36648.jpg)
