### ISSUE TITLE
unable to set reminder for daily task

### ISSUE THREAD

**Issue by greay** [HabitRPG/habitrpg-ios#555]
Every time I try, I get "Daily validation failed" and then it clears.

**Comment by saraolson** [comment]
Just tested this and it appears to be fixed, so I'm going to close. If you're still having the issue, please reopen and comment with details :)

**Comment by greay** [comment]
Still doesn't work. I can set the reminder, but if I refresh my list or quit the app & reopen, the reminder is gone.  The "daily validation failed" doesn't appear to happen every time, but it does still happen.

I cannot reopen this issue, though
