### ISSUE TITLE
Delete account doesn't work

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#559]
When i try to delete my account, the first attempt gave me a 'missing password' error after submitting. After that, i tapped delete account again and typed my password in, each time the modal would just close with nothing happening (no error).

**Comment by phillipthelen** [comment]
Moved the issue, because this is due to the website not using the HTTP Delete protocol correctly, so we will have to work around that.

**Comment by saraolson** [comment]
@viirus are we taking out the 'delete account' button in the settings then?
