### ISSUE TITLE
Chat messages sized too small for markdown formatted version

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#562]
So when I load messages and pull up a conversation, all the body text will seem normal sized, then after a second, all body text will change to a smaller text in a wave before the screen flashes and leaves all text smaller. 

Is the final body text size accurate to what designs use? It looks small, so I'm assuming the size it leaves the text in isn't the right size but need some confirmation.

**Comment by phillipthelen** [comment]
The size that is shown before the shrinking is the correct/intended size. There seems to be a bug in the font size setting for the markdown formatted version (it gets swapped out once the markdown is parsed to an attributed string, at which point it shrinks)
