### ISSUE TITLE
Can't access task's checklist if task is at the bottom

### ISSUE THREAD

**Issue by TheHollidayInn** [HabitRPG/habitrpg-ios#575]
From the Report a Bug Guild

```
On the iOS app, you are unable to open a checklist daily (to see the checklist items) when it is at the bottom of the page. This also occurs with To-Dos with checklists. However, when you move the task somewhere above the bottom, you will become able to check its checklists.
```

**Comment by saraolson** [comment]
i still cant seem to do this. when i put a daily with a checklist at the bottom and try to expand it, it just wont expand. this only happens after rearranging. and after further rearranging, tapping one tasks checklist area expanded the checklist of the task that was just in its spot (now right above it)
