### ISSUE TITLE
Tavern: app bar seems to have extra space before the content starts

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#578]
Dropping in some screenshots to show a comparison between the tavern app bar and a normal sized one

![image uploaded from ios 3](https://user-images.githubusercontent.com/12453119/35772061-99893cda-0905-11e8-925d-e291b80643c0.png)
![image uploaded from ios 4](https://user-images.githubusercontent.com/12453119/35772062-9b90a9dc-0905-11e8-9be1-cdf25af77f7c.png)

**Comment by phillipthelen** [comment]
This is the same issue as #586
