### ISSUE TITLE
Challenges: Tasks not reflecting overall value through color

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#581]
When i view a challenge, the tasks are always yellow. The color should actually line up with the average health of the task for all participants. I checked a challenge im a part of on mobile vs the same view in my challenges on web and while mine are yellow, webs are blue and red.

**Comment by schrockblock** [comment]
@saraolson I think this may have been inadvertently fixed at some point. Can you double check? It appears to be working for me now.

**Comment by saraolson** [comment]
@schrockblock yup this seems to be fixed! thanks for the headsup, will close
