### ISSUE TITLE
Tavern: World Boss issue list

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#591]
1. The caret for the boss art bar isn't showing, though tapping the area does collapse the section.

2. Rules for displaying pending damage: round down to nearest 1 decimal place. so if someone has .346 damage pending we show ".3 dmg pending". if someone has 12.679 dmg pending we show "12.6 dmg pending"

3. Rage attack should be "Shattering Heartbreak"

4. Rage strikes say 0/0, they should be 0/3

5. The icons for pending rage strikes arent showing, though there's a space for them

6. When i expand the world boss description, only the top of the first line shows, so i cant read it.

**Comment by phillipthelen** [comment]
3. The name is displayed correctly. It's not the final version, because the server has temporary text
4/5. this might also be because the content isn't completely configured yet 
6. The description currently is only one line, so this is displayed correctly
