### ISSUE TITLE
Can't expand all chat bubbles

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-ios#603]
Currently, the only chat bubble that can be expanded is the most recent message that you typed; tapping the other chat bubbles only expands your most recent message. This is very high-priority because without the ability to expand chat messages, users will be unable to flag and report posts on iOS.

**Comment by phillipthelen** [comment]
Can anyone reproduce this? I can properly expand all cells by tapping on them

**Comment by saraolson** [comment]
I could not reproduce

**Comment by lemoness** [comment]
No longer happening for me in the latest test flight build :)

**Comment by lemoness** [comment]
This is happening to me again, but refreshing the app fixes it, so I don't think it should delay the World Boss update. It would be good to fix this in the update following that, though, so I've added it to 1.13.1


The steps: 
- Post a message in chat. 
- Tap the message directly above the message that you just posted. 
- Instead of the message that you tapped expanding, the message you just posted expands.
