### ISSUE TITLE
Challenges: Not all tasks shown

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#605]
I made a test challenge with one of each task type: habit, daily, todo, reward. when i went to view the challenge on mobile it only displayed the habit and todo. When i went to my tasks tho, they were all displayed correctly so they did exist and were added.

**Comment by schrockblock** [comment]
@saraolson can you tell me what the name of that test challenge is? I'd love to use it to verify my fixes.

**Comment by saraolson** [comment]
@schrockblock Ah its a guild challenge i made on delta, here's the guild with it:

Guild (test guild, olson1 leader)
https://habitrpg-delta.herokuapp.com/groups/guild/e4ebd578-2dd2-4269-9292-737bd1cf31e4

Challenge (just test this challenge)
https://habitrpg-delta.herokuapp.com/challenges/89f896da-4339-46ad-9be0-a4fc3e80aa8d
