### ISSUE TITLE
tier icons appear at inappropriate locations in party chat (and maybe other locations)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-ios#617]
In the Report a Bug guild, krumeluuri (267135db-e7f8-42d9-bed2-f84b4261b64e) reported this problem:

"iOS bug:  ... the little icons indicating tiers still appear all over the place if you were not aware of this. Mostly they seem to appear before random system notifications in the party chat, like before someone (who doesn't have a tier) casts a party skill." 
"Here is the screenshot showing how the tier icons are buggy and show up in random system notifications."
![screenshot_2018-02-12_08-33-32](https://user-images.githubusercontent.com/1495809/36079509-6979e078-0fcf-11e8-907f-e59033c147c9.png)

**Comment by saraolson** [comment]
probably an artifact of not getting the designs for the system messages in yet. @phillipthelen is there any easy way to fix this in time for the update? even if its a half measure?

**Comment by saraolson** [comment]
optimistically assigning to 1.13 but if it doesnt make it in, then i'll push to 1.13.1 since it doesnt technically break anything, just looks a little messy.
