### ISSUE TITLE
Equipment: there is a fake category called "body" below the normal "armor" category?

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#622]
If i tap it, nothing displays as equipable yet it always says absurd party robes are equipped. even before i had absurd party robes, and even when i equip my absurd party robes to my 'armor' slot where all my body armor is displayed as equipable.

**Comment by phillipthelen** [comment]
This is partially something with the server. The "Body" category is the "Body Accessory" category on the server side. The absurd party robes seem to have been equipped automatically on the delta server, but I'm not sure why. I updated the cateogry name to match the server one, but other than that there isn't anything I can do. We might want to make sure that setting absurd party robes on the body slot isn't something that happens for new accounts on the production server also
