### ISSUE TITLE
Challenges: Some weird issues

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#623]
I had created a challenge in a private guild, when i went back to view it in challenges a few things happened:

1. the private challenge i had created and was a part of was not displayed in 'my challenges' (when checking on web, it is)
2. the private challenge is listed in the public challenges section (discover)
3. when i view the details of the challenge, it shows a join button
4. when i tap the join button it shows an error saying that im already a part of it.
5. the icon for the reward looks super stretched out and messed up
6. it says the challenge was created publically when really it should say the guild i created it in

**Comment by phillipthelen** [comment]
I renamed the tab to "Discover" to be more consistent with web. The private challenges are still shown there, since you might have groups with private challenges that you are not yet a part of.
