### ISSUE TITLE
Menu: new account, menu shows normal, no WB styling

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#626]
i created a new account, went through the habits tutorial and immediately pressed menu, got the purple bar. refreshing doesnt change it but loading tavern for the first time does. would prefer new users not have to do that so the menu can prompt them into tavern?

**Comment by phillipthelen** [comment]
This will fix itself after the second app launch, when it syncs the world state then. Should I still fix this?

**Comment by saraolson** [comment]
@phillipthelen if its not too much, i would really like for them to be able to see it on first launch just cause new users can be so quick to drop, showing it upfront and maybe gettin them more interested could be beneficial. if its super annoying tho, its not the worst.
