### ISSUE TITLE
Reproducible crash on AvatarView after sign up with email 

### ISSUE THREAD

**Issue by drougojrom** [HabitRPG/habitrpg-ios#636]
Steps to reproduce on the master branch:
1. Sign up with email
2. Register
3. Crash on `avatarView.showBackground = false`

<img width="464" alt="screen shot 2018-02-27 at 3 28 30 pm" src="https://user-images.githubusercontent.com/16073082/36734158-f6d4ecba-1bd2-11e8-9423-1fc3a26423a5.png">

**Comment by phillipthelen** [comment]
I'll check it out. The problem probably is that I forgot to set avatarView to use the new AvatarView class in this case.

**Comment by drougojrom** [comment]
It crashes with 'EXC_BAD_ACCESS (code=2, address=0x1074df490)', so, probably, it's some @objc related issue, but I can be wrong.
