### ISSUE TITLE
Time Travelers: images shift/move for equipment sets

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-ios#642]
Reported in the Report a Bug guild by Kent the Ravaged (b82b7aa8-161f-4b02-aef9-4a319e47f7b2) using his friend's iOS phone:

"When loading the time travelers, the image of item sets keep shifting and changing position with each other (for a while, like 5 seconds, every 0.5 to 1s interval), making me confused on which set is which."

We don't have information about which device or app version this happens in since it's a friend's device but we can try to hunt it down if it's not easily reproducable.

**Comment by saraolson** [comment]
tested on my device while testing a lot of time traveler stuff this past update and could never get this to happen.
