### ISSUE TITLE
Hide Mana bar in profile if user has opted out of class system.

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitrpg-ios#657]
Should be completely hidden and not just grayed out, since there's no point in hinting to the existance of mana if the user is viewing another users profile.

**Comment by shanaqui** [comment]
Sounds like this issue has recurred:

> Hi Habitica folks,
>   I experienced some strange behavior in the iOS app in the Tavern just now.  I clicked on a the avatar of a level-10 Habitican who had not yet chosen a class.  The user is @EvergreenCheese.  The profile (incorrectly I think) showed a Mana bar (at 48/50).
> 
> But when I do the same thing in a web browser on my iPhone, the profile did not show a Mana bar.  (It seems to me that this is the correct behavior.)
> 
> In contrast, the iOS app seems to display the profiles of users below level 10 correctly.  For example, at the time I checked this @Red-Rogue01 was below level 10, and the iOS app (correctly) did *not* show me a Mana bar for this user’s profile.
> 
> This led me to give incorrect advice n response to a question from @EvergreenCheese.  What I have learned from this is to always check the profile on the web, if I’m trying to see if a user has selected a class yet.
> 
> Sincerely,
> —Sharon Pedersen (@gyrfalcon17)
> 
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 14.4.2
> Device: iPhone X
> App Version: 3.2.2 (577)
> User ID: 809b7bbc-a562-4818-84ec-5e839426bf01
> Level: 16
> Class: warrior
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 7
