### ISSUE TITLE
TimeTravelers: Pets & Mount section not showing correctly

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#658]
the pets and mounts sections seem to be showing as blank entries in the time traveler gear section. at first i thought some gear sets were just missing but lookin at the website, theres no missing gear. tapping the blank cards shows a blank modal that says 'pets' and 'mounts'

**Comment by Alys** [comment]
That's been reported at https://github.com/HabitRPG/habitica-ios/issues/641 with additional information that indicates it might be a problem with the images rather than the app (I'm not sure about that though).

**Comment by saraolson** [comment]
its a slightly different issue than whats on android. on android you see the pets and mount categories and cards for each that show the name of the pet theyre for. on ios those dont even show. theres just a blank card hidden in the equipment section that has the same name as the section label
