### ISSUE TITLE
Shops: Modal for seasonal items that has the time limit icon should have banners

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#666]
The banner should be the same purple as the time limit icon with white text that says "Available until April 31" or whatever day we say the season ends.

**Comment by saraolson** [comment]
The banner shows in market, but when i tap on the same item from rewards theres no banner? 

Also the banner says May 1, 2018 but the bailey says April 30, 2018?

**Comment by phillipthelen** [comment]
the date displayed is from the API. it should be may 2. (should be fixes in the next update). Items are usually available a day or two longer than announced because of timezones and all.

**Comment by saraolson** [comment]
welp okay we should really just say 'items will be available til may 2nd 3pm PST' or something like most time limited events do

**Comment by phillipthelen** [comment]
The API isn't that specific. it only has a date. I also don't think it matters too much if the exact time is included or not.
