### ISSUE TITLE
 player should not be automatically removed from Challenges when leaving a Guild or Party

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-ios#673]
Currently on the iOS app, when a player leaves a Guild, they are automatically removed from any challenges they have joined that are hosted in that Guild. This should not happen - they should remain as participants of the challenges, even for those hosted in private guilds.

The same applies when the player is removed from a Guild - that should not remove them from challenges.

The same applies to leaving or being removed from a Party.

This was reported for the iOS app [in this website repo comment](https://github.com/HabitRPG/habitica/issues/7764#issuecomment-374587308). It has also been reported for the Android app [here](https://github.com/HabitRPG/habitica-android/issues/906), with a discussion of how to fix it. In brief,  the iOS app could be modified to specify `keepChallenges = remain-in-challenges` when it calls the API's route for leaving a group.

**Comment by phillipthelen** [comment]
If we want this to be the default behaviour, shouldn‘t this be reflected by
the api?

-- 
Phillip Thelen
Sent with Airmail

**Comment by Alys** [comment]
There's a discussion about that in the Android issue (https://github.com/HabitRPG/habitica-android/issues/906).
