### ISSUE TITLE
Error messages always say "Not enough Gold" when purchasing fails, regardless of reason

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitrpg-ios#683]
Various admin support emails / Report a Bug Guild conversations have expressed confusion about being unable to buy Gold-purchase items. Whenever a Gold buy fails, the app reports that the user doesn't have enough Gold, even if the buy failed for some other reason, such as:

* They were trying to buy Gems but have hit their Gold:Gems cap for the month
* They were trying to buy a limited-availability item like seasonal gear, and that gear's availability has elapsed
* They were trying to buy an item that belongs to a different class

**Comment by fiuzaB** [comment]
Analyzing the code, this issue shouldn't happen anymore.

**Comment by saraolson** [comment]
yup, this doesn't happen anymore. closing the issue
