### ISSUE TITLE
recreating ongoing subscriptions as new ones causes failure in cron's monthly subscription benefits

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-ios#684]
Mershmella (6c8e2dc6-d78a-4774-b33c-bda79d88192d) reported in the Report a Bug guild that their `gemsBought` value had not reset during cron at the beginning of this month (i.e., they couldn't buy gems with gold this month). I've confirmed that from Amplitude data and I've reset it manually. This also happened to them last month and at that time I suspected it was caused by them having too much history in some tasks (which can cause cron to time out part way through). I cleared all their history last month. This month they still have small history arrays, so I don't think that can be the cause of their gems not resetting this time.

I think the problem was caused by their subscription being recreated from scratch at the start of each month and that seems to be happening only for Apple subscriptions.

Mershmella has an Apple subscription:
```
{
    "_id": "6c8e2dc6-d78a-4774-b33c-bda79d88192d",
    "profile": {
        "name": "Mershmella"
    },
    "purchased": {
        "plan": {
            "consecutive": {
                "count": 8,
                "offset": 0,
                "gemCapExtra": 10,
                "trinkets": 0
            },
            "quantity": 1,
            "extraMonths": 0,
            "gemsBought": 35,
            "mysteryItems": [],
            "additionalData": "MIIhww...GYUA==",
            "customerId": "32...73",
            "dateCreated": "2017-07-01T17:38:21.482Z",
            "dateTerminated": null,
            "dateUpdated": "2018-04-01T16:14:01.847Z",
            "nextPaymentProcessing": "2018-04-10T18:02:51.592Z",
            "owner": "6c8e2dc6-d78a-4774-b33c-bda79d88192d",
            "paymentMethod": "Apple",
            "planId": "basic_earned"
        }
    },
}
```

Whenever a new subscription is created (not when an ongoing subscription renews), a message is posted to the moderators' Slack to help us troubleshoot subscription data, and we have multiple such records for Mershmella this year:
```
Mershmella 6c8e2dc6-d78a-4774-b33c-bda79d88192d undefined bought a 1-month recurring subscription using Apple on Thu Feb 15 2018 04:16:43 GMT+0000 (UTC)
Mershmella 6c8e2dc6-d78a-4774-b33c-bda79d88192d undefined bought a 1-month recurring subscription using Apple on Thu Feb 15 2018 04:16:43 GMT+0000 (UTC)
Mershmella 6c8e2dc6-d78a-4774-b33c-bda79d88192d undefined bought a 1-month recurring subscription using Apple on Thu Feb 15 2018 04:16:43 GMT+0000 (UTC)
Mershmella 6c8e2dc6-d78a-4774-b33c-bda79d88192d undefined bought a 1-month recurring subscription using Apple on Thu Mar 01 2018 19:16:37 GMT+0000 (UTC)
Mershmella 6c8e2dc6-d78a-4774-b33c-bda79d88192d undefined bought a 1-month recurring subscription using Apple on Thu Mar 01 2018 19:16:37 GMT+0000 (UTC)
Mershmella 6c8e2dc6-d78a-4774-b33c-bda79d88192d undefined bought a 1-month recurring subscription using Apple on Thu Mar 01 2018 19:16:38 GMT+0000 (UTC)
Mershmella 6c8e2dc6-d78a-4774-b33c-bda79d88192d undefined bought a 1-month recurring subscription using Apple on Sun Apr 01 2018 16:14:01 GMT+0000 (UTC)
```
There's supposed to be just one of those records each time a subscription is created, so seeing seven makes it look as if the subscription was created from scratch seven times this year. I asked Mershmella if they've been manually cancelled and recreating their subscription each month, but they said "I have automatically renewed since I started my subscription (through the Apple store)".

So it looks like something in Habitica's code is causing an ongoing subscription to be recreated as if it's a new subscription. Looking through our Slack records, I can see similarly duplicated records for about 40 users in March, all for Apple subscriptions (none for any other payment method). This is a problem because when an ongoing subscription is recreated as if it were a new subscription at the beginning of the month, it causes a faiure in the process that adjusts the user's monthly subscription benefits. In detail:

From the above data, you can see that the new subscription was created for Mershmella at Apr 01 2018 16:14:01, and this resulted in their subscription's `dateUpdated` value being set to "2018-04-01T16:14:01.847Z" - that value is always set when a new subscription is created, by this code: https://github.com/HabitRPG/habitica/blob/fa945c768949bf00adba2281483677cb66dc2c8c/website/server/libs/payments/payments.js#L331

Mershmella's cron on 1 April ran a few minutes after their subscription was recreated: 2018-04-01T16:21 ("April 1, 2018 4:21:16 pm UTC" in Amplitude). Part of cron's processing is to check the `dateUpdated` value for a subscription - if it is in a previous month, then cron runs the code that resets the user's monthly gem cap and increases their consecutive month benefits:
https://github.com/HabitRPG/habitica/blob/fa945c768949bf00adba2281483677cb66dc2c8c/website/server/libs/cron.js#L65-L68

Because `dateUpdated` had already been set to a date in April before cron ran, cron couldn't tell that it needed to reset their gem cap.

I.e., having Apple subscriptions recreated from scratch each month is damaging if it happens before the user's first cron of the month. Users affected by this will never have their monthly gem caps reset and won't earn consecutive month benefits. So ideally we'd either work out what is causing Apple subscriptions to be recreated from scratch, or we'd need to adjust how cron assesses subscriptions so that it stops using the dateUpdated value.

Until this is fixed, admins will need to find all affected users each month and manually:
- reset their `purchased.plan.gemsBought` value (set to 0)
- increase their `purchased.plan.consecutive.count` by 1
- decrease their `purchased.plan.consecutive.offset` by 1 if it's not 0
- increase `purchased.plan.consecutive.gemCapExtra` by 5 if `count` is now at a multiple of 3 and `offset` is 0 and the value is not already 25 (never let it be higher!)
- increase `purchased.plan.consecutive.trinkets` (Hourglasses) by 1 if `count` is now at a multiple of 3 and `offset` is 0

By the way, Mershmella is being affected by the "RECEIPT_ALREADY_USED" problem. I don't know if that's related. Here's one example from Loggly:
```
message:NotAuthorized: RECEIPT_ALREADY_USED
    at Object.subscribe (/usr/src/habitrpg/website/transpiled-babel/libs/applePayments.js:143:29)
    at <anonymous>
method:POST
originalUrl:/api/v3/iap/ios/subscribe
```
and screenshots of others from around 1 April:
![6c8e2dc6-d78a-4774-b33c-bda79d88192d](https://user-images.githubusercontent.com/1495809/38650047-22c0815e-3e3d-11e8-8268-93843e617365.png)

**Comment by Alys** [comment]
Sorry, I phrased this part badly: "So ideally we'd either work out what is causing Apple subscriptions to be recreated from scratch, or we'd need to adjust how cron assesses subscriptions so that it stops using the dateUpdated value."

The main purpose of the dateUpdated value is to allow cron to do its start-of-month subscription benefit updates, so that would be better written as 
"... or we'd need to adjust how cron assesses subscriptions so that it can cope with the dateUpdated value being reset before the first cron of the month."

I believe that stopping the subscriptions being recreated would be the neatest fix, if that's possible.

**Comment by phillipthelen** [comment]
This might be caused by something in the habitica-email-server code, since that goes through the user data. Although I’m not sure right now that it actually updates anything on the subscription, since it should mostly just check with apple if the subscription is still active and cancel it on our side if not.
Since this is not an issue happening in the app, this should probably be tracked in the email server or main server repo instead?

**Comment by Alys** [comment]
Sure. If it's not app code that's doing it, I'll open this in the main repo.
