### ISSUE TITLE
text inconsistencies between app and website

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-ios#687]
In the Stable, there are subsections for "Base" and "Premium" pets and mounts. Can those be renamed to "Standard" and "Magic Potion" for consistency with the website and Android app?

This would make it easier for us to answer users' questions and bug reports since we could then use the same terminology regardless of their platform, and it would avoid user confusion if a user sees information written for a different platform than theirs.

**Comment by saraolson** [comment]
this will be fixed when stable redesigns are out in the restkit update
