### ISSUE TITLE
Attempting to buy gems with gold crashes the app

### ISSUE THREAD

**Issue by amwelles** [HabitRPG/habitrpg-ios#694]
Stuff I've tried that hasn't worked to fix the issue:

- Clearing cache
- Reloading content
- Force-quitting the app
- Restarting the phone

As a workaround, I've just been going to the web app and buying gems there. 🙃 

I'm running iOS 11.3.1 on an iPhone 7+. I have Habitica version 1.14.

**Comment by ashleyng** [comment]
Does the google analytics pod have crash reporting set up (I'm more familiar with crashlytics/fabric)? but might be helpful to post the stacktrace for whoever has access to the account.

**Comment by phillipthelen** [comment]
We use Crashlytics for crash reports.
The underlying code (as is the case for a lot of parts of the app) has been completely reworked for the next update, so this crash is actually already fixed!
