### ISSUE TITLE
Reinstalling app can cause it to show error about missing authentication headers

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitrpg-ios#708]

**Comment by RogoTe** [comment]
I have this issue after switching iPhones with the latest version.
iOS-App does not start up after changing from iPhone 6s Plus to 7 Plus. The only thing I see is the start screen with the spinning circle and a red message 'Missing Authentication headers.' pops up twice.

**Comment by phillipthelen** [comment]
Can you also try uninstalling the app from your phone and then installing it again?

--  
Phillip Thelen
Sent with Airmail

**Comment by RogoTe** [comment]
@phillipthelen > Can you also try uninstalling the app from your phone and then installing it again?
Okay, did that and this solved the issue. Thanks.
