### ISSUE TITLE
tasks being scheduled on wrong dates

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-ios#742]
I've been seeing reports that tasks aren't being scheduled correctly in the iOS app. I am thinking it might be related to the user's Custom Day Start time or time zone not being taken into account when working out if a task should be due and whether the bug occurs might depend on the time portion of the To-Do's `date` field (the due date) or the Dailies `startDate`.

Here's an example from the-woman-who-read-everything (afe90c0a-3aab-4b91-988a-7f4cefb7394e)

_"One of my To-Dos has a due date mismatch between my phone (iOS app) and the website. It's supposed to be due July 30, but my phone shows that it is due July 31. If I correct the date on my phone to the 30th, it shows the due date as the 29th on my computer. Other tasks due on this day are fine, and both devices are set to the same date and time zone. I have marked it with "thisone""_

Her time-related preferences are:
```
"preferences": {
	"dayStart": 3,
	"timezoneOffset": 300,
	"timezoneOffsetAtLastCron": 300
},
```

This is the To-Do that's not being scheduled correctly in the app (I've removed the task's title and checklist items for privacy):
```
{
    "_id": "45d0f1ce-16af-432a-bc87-d0bca42612fb",
    "challenge": {},
    "group": { "approval": { "required": false, "approved": false, "requested": false }, "assignedUsers": [], "sharedCompletion": "recurringCompletion" },
    "completed": false,
    "collapseChecklist": false,
    "type": "todo",
    "notes": "thisone",
    "tags": [],
    "value": -5.273878399739519,
    "priority": 1,
    "attribute": "str",
    "reminders": [],
    "checklist": [ ],
    "createdAt": "2018-07-24T04:34:17.300Z",
    "updatedAt": "2018-07-28T18:12:50.665Z",
    "userId": "afe90c0a-3aab-4b91-988a-7f4cefb7394e",
    "__v": 6,
    "date": "2018-07-31T04:34:00.000Z"
}
```

There are two To-Dos that are being scheduled correctly:
```
{
    "_id": "34dcc89f-f20d-42b5-83e5-0565232bd446",
    "challenge": {},
    "group": { "approval": { "required": false, "approved": false, "requested": false }, "assignedUsers": [], "sharedCompletion": "recurringCompletion" },
    "completed": false,
    "collapseChecklist": false,
    "type": "todo",
    "notes": "",
    "tags": [],
    "value": -121.1499693189606,
    "priority": 2,
    "attribute": "str",
    "reminders": [],
    "checklist": [ ],
    "createdAt": "2018-06-04T16:27:21.954Z",
    "updatedAt": "2018-07-28T15:52:07.629Z",
    "userId": "afe90c0a-3aab-4b91-988a-7f4cefb7394e",
    "__v": 1,
    "date": "2018-07-30T16:27:00.000Z"
}
 
{
    "_id": "2278d039-47be-42d0-b99b-a9de9ae9d412",
    "challenge": {},
    "group": { "approval": { "required": false, "approved": false, "requested": false }, "assignedUsers": [], "sharedCompletion": "recurringCompletion" },
    "completed": false,
    "collapseChecklist": false,
    "type": "todo",
    "notes": "",
    "tags": [],
    "value": -121.1499693189606,
    "priority": 1,
    "attribute": "str",
    "reminders": [],
    "checklist": [ ],
    "createdAt": "2018-06-04T16:48:28.786Z",
    "updatedAt": "2018-07-28T15:52:07.629Z",
    "userId": "afe90c0a-3aab-4b91-988a-7f4cefb7394e",
    "__v": 1,
    "date": "2018-07-31T20:06:00.000Z"
}
```

**Comment by phillipthelen** [comment]
The app does not do any calculations about task duedates itswlf anymore. It’s only using the `isDue` and `nextDue` fields from the website. So I’m not really sure why this is happening.

--  
Phillip Thelen
Sent with Airmail

**Comment by Alys** [comment]
Could this be related to the problem with the wrong Dailies appearing in the iOS app's RYA screen?
