### ISSUE TITLE
"pm" (and "am"?) in Daily's startDate causes ValidationErrors - Daily never gets created

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-ios#750]
There's an error in creating Dailies although it might occur for only people with certain date-related locale settings maybe.

The user below reports that when they create Dailies, the tasks disappear after a sync.

Loggly shows this error:
**message:ValidationError: daily validation failed: startDate: Cast to Date failed for value "2018-09-07T11:19:00.788 pmZ" at path "startDate"**

Note the " pm" portion in the date.

iOS Version: 11.4.1
Device: iPad5,3
App Version: 2.0.6
User UUID: 0681ca59-4ab7-4f32-8298-4440a244c27f

Loggly error message:
https://habitica.loggly.com/search#terms=0681ca59-4ab7-4f32-8298-4440a244c27f&from=2018-07-20T00:00:00.000Z&until=2018-09-09T03:11:05.011Z&source_group=

Link to email:
https://mail.google.com/mail/u/0/#inbox/16586fe70470fd5c

**Comment by imanqahtan** [comment]
I do not set up any time and it still wont create any dailies!!! It is so frustrating this app use to help me so much and now i cant use it ever since the update was made!!!!!!!!! And the support system just stopped replied to me i am so frustrated

**Comment by phillipthelen** [comment]
This is not something a user sets, but instead an issue where the app is not formatting the date correctly. I am still investigating this, and now that I know what exactly the formatting issue is, I should be able to fix it soon.
I'm sorry that the email support apparently didn't reply to you anymore. However, there is currently no other suggestion than to wait until I am able to push a fix with this and maybe use the website in the meantime, to create those dailies.

**Comment by phillipthelen** [comment]
I pushed some changes that should fix this issue, that will be tested over the next days on testflight. If a user affected by this wants to help testing to see if the fix works for them, see the [instructions on how to join testflight](https://habitica.wikia.com/wiki/IOS_Beta)
