### ISSUE TITLE
MOBILE [Oct 12] Implement modal that forces users to change username

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitrpg-ios#753]
Once we release the username feature, users have to set/confirm their username

**Comment by saraolson** [comment]
[Forced modal design](https://zpl.io/aX4qXdl)
[Keyboard up](https://zpl.io/bevGW8m)
[Error typing](https://zpl.io/aRPKXgv)
[Errors and confirmation](https://zpl.io/2pBNPmo)

App link
zpl://screen?sid=5baa7fc5fc85293fd372b2fe&pid=58a30e626340743338ed20c3
