### ISSUE TITLE
Add spacing to background purchase page to improve clarity

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#754]
We've had a few people request refunds because they purchased the wrong background set with gems due to the labels+purchase all buttons being unclear which they're associated with. 

Proposed solution: make each label and 'buy all' button appear above a set, and add extra spacing between sets. 

Example mockup of solution:
<img width="188" alt="backgrounds_spacing" src="https://user-images.githubusercontent.com/12453119/46114821-52193500-c1c2-11e8-9583-50e193a05586.png">

Existing problem (the labels are below their set, and proximity makes it hard to tell which its for):
<img width="188" alt="image from ios" src="https://user-images.githubusercontent.com/12453119/46114919-cfdd4080-c1c2-11e8-9f71-1a38c42af8ed.png">

**Comment by ashleyng** [comment]
I think I can take a stab at this one. Is there any specific spacing we're looking to use? Otherwise I'll just come up with one that I think looks good.
