### ISSUE TITLE
Party: formatting can get messed up when opening the page

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#774]
Occasionally when opening the quest page, the formatting on the page gets all messed up (in the same way each time). Pictures attached.

![image from ios 17](https://user-images.githubusercontent.com/12453119/48497799-dc653900-e802-11e8-8fbe-02fd3e6a8be1.png)
![image from ios 18](https://user-images.githubusercontent.com/12453119/48497800-dc653900-e802-11e8-881f-0b175a0a893e.png)

**Comment by GiacomoLaw** [comment]
I’m constantly getting this issue. Is there any work going on on the iOS app? Three branches are stale :/

**Comment by saraolson** [comment]
@GiacomoLaw there is work going on in the iOS app but due to holidays and having one mobile dev that has to work on both android and iOS, sometimes one of the apps goes longer without an update.

**Comment by GiacomoLaw** [comment]
@saraolson Ok, makes sense. Thanks!
