### ISSUE TITLE
Cannot delete tags

### ISSUE THREAD

**Issue by IgorChernyshov** [HabitRPG/habitrpg-ios#780]
I wasn't able to delete a tag in iOS app.
Steps:
- Joined a challenge - tag was automatically created
- Left a challenge - tag stayed
- Opened Filter menu
- Pressed Edit
- Pressed a red icon on the row that I wanted to delete
- Pressed delete
- Nothing happens

**Comment by saraolson** [comment]
this was fixed in the latest build
