### ISSUE TITLE
Cannot see quest rewards

### ISSUE THREAD

**Issue by rggjan** [HabitRPG/habitrpg-ios#782]
It is not possible to see quest rewards, either before, during or after a quest, on iOS

**Comment by saraolson** [comment]
Right now, the only place it's possible to see rewards is in the modal shown while buying the quest.

**Comment by rggjan** [comment]
Good to know. Doesn't help for quests you get automatically, or quest follow ups, unfortunately...

**Comment by saraolson** [comment]
We'll change this so when you tap on a quest to start it from your inventory, it shows the full modal rather than just the start button.
