### ISSUE TITLE
Cannot see quest description before starting quest

### ISSUE THREAD

**Issue by rggjan** [HabitRPG/habitrpg-ios#783]
On iOS, the quest description is only visible after a quest is started. It is not possible to see it beforehand.

**Comment by saraolson** [comment]
You should be able to see the quest description after inviting the party to the quest but before starting it by tapping the scroll while inviting. This would only effect a single-person party.

**Comment by rggjan** [comment]
I see. But then you cannot see the description of any quests you have while a quest is already going on, correct?
