### ISSUE TITLE
iOS phone notifications duplicate 3 times.

### ISSUE THREAD

**Issue by lilacstella** [HabitRPG/habitrpg-ios#786]
Whenever a notification appears, it appears as three duplicate notifications.

**Comment by phillipthelen** [comment]
Can you confirm if this is still happening with the most recent 2.2.1 version?

**Comment by lilacstella** [comment]
Yes, this is still occurring in the 2.2.1 version.

**Comment by saraolson** [comment]
Continuing to get reports of 4-6 duplications of notifs from users.

Here's one in particular for a quest invite notif, her party member has the same experience:
iOS Version: 12.3.1
Device: iPhone 6s Plus
App Version: 2.3.4 (394)
User ID: 3ead4269-2b5b-4d9b-8c6c-29babaf9f446
Level: 75
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 5

**Comment by BioSina** [comment]
I can add that on an up to date IPhone I have duplicated notifications, on my up to date IPad they are triplicate.  If there is any information I can provide to help, please feel free to ask. My username is @skymninge

**Comment by Alys** [comment]
@BioSina I've adjusted your skymninge account to remove the config that's causing the duplicated notifications. The problem might reoccur so if it does, tell us again.

**Comment by kyrasantae** [comment]
Hello, I have the same issue of notifications appearing three times on my up to date iPad. My Habitica username is @tiikerikani.

**Comment by Alys** [comment]
@kyrasantae I've fixed that for you.
