### ISSUE TITLE
Clicking back after clicking hatch egg goes back one screen too much

### ISSUE THREAD

**Issue by rggjan** [HabitRPG/habitrpg-ios#794]
Instead of going back to the items menu, it goes back to the main menu.

There is no way to go back one screen from the potion selection to the items menu currently.

**Comment by xanenv** [comment]
I can confirm that this happens. Specifically, after you click on an egg and depress “Hatch Egg,” but then select “Back” option, it goes all the way out to Menu, so that “Items” needs selecting again to get back to where it should have gone.

**Comment by ashleyng** [comment]
This might need some design work, as the current implementation just refreshing the tableview to show the hatching potions after selecting an egg. 
I'd say the existing back button does what it's supposed to do, but for the workflow, there needs to be a way to cancel out of the hatching egg process (i.e refresh the tableview again to cancel out of hatching and show all the items again).

![giphy](https://user-images.githubusercontent.com/5355231/66262672-5e0ede00-e7aa-11e9-9364-595623e145e6.gif)
