### ISSUE TITLE
Openning Markdown Links

### ISSUE THREAD

**Issue by bigredjoe** [HabitRPG/habitrpg-ios#808]
Right now markdown links render correctly in Habitica iOS but there is no way that I know of to click them (dailies, habits, todos, rewards).

A possible solution is to make long pressing an item open the link (if there is more than one link then a simple selection prompt would let the user select which link they would like to open).

**Comment by phillipthelen** [comment]
Are you referring to markdown links in the task list?

**Comment by bigredjoe** [comment]
Yes, the task list and the dailies, habits, and rewards as well.

**Comment by Alys** [comment]
@bigredjoe Just for reference in case it helps to clarify anything you see here or in the code, "tasks" is a generic term that refers to Habits, Dailies, and To-Dos, and also Rewards in most technical contexts (Rewards are stored and handled similarly to the other task types). :)

**Comment by bigredjoe** [comment]
Good to know, thanks for the clarification 👍
