### ISSUE TITLE
Bigger Tap area for checklist indicator

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitrpg-ios#81]
The checklist indicator for dailies and todos should have a tappable area that consists of the entire right part of the cell (currently there is a gap at the top, bottom and to the right

**Comment by Shadallark** [comment]
I would like to take a crack at solving this issue.  I figure I can place a transparent button over the whole right end of the cell (including the Checklist indicator) that has the same functionality as the Checklist indicator.

**Comment by vIiRuS** [comment]
This sounds like my plan too. I'm not sure if you planned this anyway, but I would like the button to also display the indicator itself. So a subclass of UIButton is probably needed.

Thanks in advance and let me know if you need further assistance!
