### ISSUE TITLE
To-Do's: Order by date due when filtered to 'Scheduled'

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#810]
Right now when you filter to scheduled it just hides any todos that dont have a due date. Ideally we could also then sort those todos so that the ones due soonest are at the top of the list.

**Comment by IgorChernyshov** [comment]
I tried to reproduce the issue:
1. Opened To-Do's screen.
2. Activated filter "Dated".
3. All to-do's were automatically sorted by date: to-do's with earlier due date appear higher in the list than the others.

So either I didn't understand the task correctly or this has already been fixed. Can you please clarify?
