### ISSUE TITLE
Enabling class system: set class flags at a consistent time with the website

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#815]
From a report by Alys:
When you opt out of the class system, your account is changed to have these settings (this is working correctly on website and app):

"flags.classSelected": true
"preferences.disableClasses": true

After that, when you click/tap on "Enable Class System", your settings are meant to change immediately (before you select a class). This is what they should be as soon as you've clicked/tapped that button - i.e., at the moment that the class selection screen appears:

"flags.classSelected": false
"preferences.disableClasses": false

That works correctly on the website.
It doesn't work on the app. As soon as you tap on the "Enable Class System" button, your settings are not changed (both are still set to `true`).

**Comment by mikesanderson** [comment]
Hi I opened a pull request for this about 2 weeks ago and didn’t get any feedback.
