### ISSUE TITLE
App won't start in iOS 13

### ISSUE THREAD

**Issue by Sanjot01** [HabitRPG/habitrpg-ios#822]
I just downloaded the app but when I start it crashes directly

**Comment by phillipthelen** [comment]
Can you try joining the testflight beta? I'm using that version with iOS 13 and it works. https://habitica.fandom.com/wiki/Mobile_Beta_Test_App_for_iOS:_Habitica

**Comment by Daedren** [comment]
Crashes for me too, on Testflight's 2.4 (394). It has worked before, I don't recall if updating to the latest beta was the trigger. Downgrading back to 2.3.4 didn't help.

On iPad Pro 11", iOS 13 b3 (17A5522g)

**Comment by RogoTe** [comment]
I am not (yet) on testflight but the latest published version. This crashes. Was working before.

Crash report attached
[Habitica-2019-07-16-090446.txt](https://github.com/HabitRPG/habitica-ios/files/3395780/Habitica-2019-07-16-090446.txt)
