### ISSUE TITLE
Rewards page and market doesn't work

### ISSUE THREAD

**Issue by FlameLightFleeNight** [HabitRPG/habitrpg-ios#830]
Can't select items from the market or from the rewards page. When I try, the app hangs and then crashes.

**Comment by phillipthelen** [comment]
Are you using the app store version of the app or testflight? And can you tell me your habitica userID?

**Comment by FlameLightFleeNight** [comment]
App Store version. My user ID is 23526cff-8494-47d0-862b-980bc28c7dbb.
