### ISSUE TITLE
feeding pets has issues

### ISSUE THREAD

**Issue by jcmoore65** [HabitRPG/habitrpg-ios#84]
steps:
- navigate Menu | Pets | Tiger Cub | Base Tiger Cub
- click Feed
- click Meat
- observe Server error of some variety
- observe Meat is removed from inventory
- (I think) observe Pet's food gauge doesn't change

iOS 8.4 / iPhone 6+

**Comment by vIiRuS** [comment]
This sounds like an issue that occurs with the API. the action is successfull. After refreshing the app the pet's food gauge is also changed. But I'll look into why this displays the error again.

**Comment by jcmoore65** [comment]
Just verified on app refresh it did change the gauge.
