### ISSUE TITLE
Option to Hide habits/dailies/to-dos/rewards in navigation bar

### ISSUE THREAD

**Issue by Maijin** [HabitRPG/habitrpg-ios#843]
**Is your feature request related to a problem? Please describe.**

Hi Team, 

I only use the Dailies but none of the other Habits/To-Dos and Rewards in navigation bar. Unfortunately everytime I open the app, it default on Habits which is empty. It would be great to be able to disable those and only have the button you need in the navigation bar.

**Describe the solution you'd like**

Settings to hide/show given information in navigation bar (maybe also the ordering could be nice)

**Comment by saraolson** [comment]
We have a feature request form now, so we're trying to clear out our github of features. if we implement something that changes the bottom nav bar, it would be a full edit mode where you can add other sections of the app to the bar. but, that is a project for the future.
