### ISSUE TITLE
Monthly repeat inputs seem confusing

### ISSUE THREAD

**Issue by kevincoleman** [HabitRPG/habitrpg-ios#855]
The inputs used to make a daily task recur on a monthly basis seem confusing and poorly labeled.

![](https://i.imgur.com/PceSGbg_d.jpg?maxwidth=640&shape=thumb&fidelity=medium)

The start date makes sense.  
Repeats “Monthly” makes sense.  
  
“Every (number)” is a bit ambiguous. Is it every this many months that the item will recur? If so, could this be reworded to “Every (number) months” so we at least know what the unit is?

Or is this number being used in conjunction with the next setting to say “every (number)th day of the (week/month)” is when the item will recur? If so we might want to add the suffixes on the numbers so the sentence reads more naturally, and the scale should never exceed 31 or 7 depending on the next field’s selection.

Selecting day of month or day of week doesn’t make sense when we already said we want to do a monthly recurrence. Can this be better explained?

I find the week indicator to be quite natural in the weekly recurrence options.

![](https://i.imgur.com/cdULdHL_d.jpg?maxwidth=640&shape=thumb&fidelity=medium)

Can we take this concept’s strengths to make the monthly one more comprehensible?

**Comment by saraolson** [comment]
This could be improved by re-implementing the summary line that goes over how a Daily is scheduled in plain text. ie below the ui it would say 'Will repeat every 42 months on the 30th' vs 'Will repeat every 1 month on the last Wednesday of the month.'

We also have some old designs that include a calendar to select from, but scheduling Monthlies is n't as advanced as that in the backend code yet. That's a slightly larger project that we'd like to take on, but don't have the resources for right now.

**Comment by kevincoleman** [comment]
I like this solution. when in doubt, spell it out! :)

I’m a web guy more naturally, so I’d PR this if I had the dev skills—alas, I do not.

Thanks for giving it attention!

**Comment by saraolson** [comment]
Thanks for the report! We have some work going into improving the string for the schedule summary going on for web right now, so hopefully when that's done we can carry it over to iOS soon.
