### ISSUE TITLE
Show/Hide header

### ISSUE THREAD

**Issue by 4brunu** [HabitRPG/habitrpg-ios#858]
**Is your feature request related to a problem? Please describe.**
In the tabs "Habits", "Dailies" and "To-Dos" the header occupies to much space, not letting me see what I want, the content of that screen.
I have an iPhone SE and only half of the screen has the actual content of the screen.

**Describe the solution you'd like**
It would be nice to have and option in the setting menu to show or hide the header in those screen.
By being an option in the settings menu, the users could choose how they would like to see it.

**Additional context**

| | | | |
|:-------------------------:|:-------------------------:|:-------------------------:|:-------------------------:|
| Habits <img width="531" alt="Screenshot 2019-10-24 at 11 41 11" src="https://user-images.githubusercontent.com/784666/67479091-326a6f80-f655-11e9-82fb-5166a35cf348.png"> | Dailies <img width="525" alt="Screenshot 2019-10-24 at 11 41 27" src="https://user-images.githubusercontent.com/784666/67479092-33030600-f655-11e9-82b2-2b15d52c8e52.png"> | To-Dos <img width="523" alt="Screenshot 2019-10-24 at 11 41 50" src="https://user-images.githubusercontent.com/784666/67479100-34ccc980-f655-11e9-9365-b69d54c68273.png"> | How I would like to see it <img width="525" alt="Screenshot 2019-10-24 at 11 41 38" src="https://user-images.githubusercontent.com/784666/67479098-34ccc980-f655-11e9-93e1-a577230429c2.png">

**Comment by phillipthelen** [comment]
Currently these screens are the only place where you can actually see your current health, experience, level and so on. So implementing a setting like this would require more thought into where that information would move to (and make this more complicated than it might initially seem).

Personally I think the current solution of having the header slide away to give you more space for viewing your tasks works well.

**Comment by 4brunu** [comment]
Personally I don't use much the gamification part of the app, but I know it's a really important aspect for a lot of users, that's why I proposed a setting to let the users choose.
Mobile games usually have a profile page somewhere in the app that displays the sort of information that the header has, and from what I've seen, the Menu tab is the closest thing to a profile page.
So I suggest showing that information in the Menu's screen header where there is free space, as I show highlighted  in the screenshot.

![IMG_2121_1](https://user-images.githubusercontent.com/784666/67481817-80ce3d00-f65a-11e9-801d-9c6ff748d959.jpg)

**Comment by saraolson** [comment]
After taking a look at our current roadmap, we’ve decided to close this issue in favor of prioritizing other features and issues that help the majority of our player base and align more closely with the team's current goals.

We do have plans to optimize the header and show it in less places throughout the app in the future.
