### ISSUE TITLE
Make weekdays in task form translated

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitrpg-ios#865]
Currently the weekdays are not translated and are always "M", "T", "W"... It would be better if they were translatable.
iOS might already provide a way for us to access translated names of the weekdays for this.

**Comment by juanj** [comment]
I would like to work on this.

[Calendar.veryShortWeekdaySymbols](https://developer.apple.com/documentation/foundation/calendar/2292956-veryshortweekdaysymbols) provides an array of very short names for the day of the week based on the locale. I think it's perfect for this.

I have two questions.

1. These names are only used on the task form?
2. It's ok to implement this directly on `WeekdayFormCell` or there is a better place for translation related code?

**Comment by juanj** [comment]
Also, a change that may be related is that the first day of the week changes depending on the locale (this does not affect the order of `Calendar.veryShortWeekdaySymbols`), the order of the cells should change to reflect this?

**Comment by phillipthelen** [comment]
Hi,

My only concern with this is the order the days are in when they are returned from `veryShortWeekdaySymbols`. Right now we wouldn't want the order of the days in the UI to change.

**Comment by juanj** [comment]
I did some testing, and the array returned by `veryShortWeekdaySymbols` always starts at Sunday not matter what the first day of the week is for that locale. Can't find any documentation that corroborates this, but I think we are safe.
