### ISSUE TITLE
RYA shows Dailies from a previous day

### ISSUE THREAD

**Issue by Yayef** [HabitRPG/habitrpg-ios#868]
**Describe the bug**
When I launch the app for the first time after my cron, the modal for yesterday's item show items from another day than yesterday. 

**To Reproduce**
Before the cron, use another device than the iPhone and let some dailies unchecked. After the cron, use iOS for the first check in. Dailies from another day than yesterday are shown. Completely close the app in iOS (swipe up). Reopen the app: the correct dailies are shown in the modal.   

**Expected behavior**
The modal should show the unchecked dailies of yesterday.

**Smartphone (please complete the following information):**
 - Device: iPhone Xs and iPhone SE
 - OS: iOS 13
 - App Version: 2.6.2 (and before, it's an old bug)
 - Habitica Username: Yayef

**Additional context**
* I think this happens if I use another device than my iPhone before the cron and use my iPhone after the cron but I'm not 100 % sure of that. I can check that during the following days. 
* Timezone: UTC+1 
* Custom cron time: 2 AM

**Comment by Yayef** [comment]
> I think this happens if I use another device than my iPhone before the cron and use my iPhone after the cron but I'm not 100 % sure of that. I can check that during the following days.

In fact, it happens even if I always use my iPhone.

**Comment by saraolson** [comment]
closing this issue in favor of #920 since they're the same
