### ISSUE TITLE
Content API: use Etag to reduce downloads from server

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitrpg-ios#877]
The content api call can't be entirely cached but it's served with an [ETAG header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) that if saved and used in the following requests with an [If None Match header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match) makes it possible to avoid downloading the resource again if it's not changed.

It's a standard HTTP caching mechanism so I don't know exactly how it works on iOS but it should be possible to implement

**Comment by saraolson** [comment]
Will assign this to late Q2 milestone. @paglias / @phillipthelen if you think this is more urgent or really easy, we can move it to early Q2 milestone.

**Comment by paglias** [comment]
Not sure about the difficulty of implementing it, regarding the priority this is not affecting server performances but it would help save some money on the GCP bill because the API call considering both Android and iOS results in about 100GB of data transfer per day so we could save ~200 $/mo

**Comment by paglias** [comment]
So not high priority in terms of server stability (not sure if faster load times would help with the user experience on the apps), would just help in terms of costs

**Comment by saraolson** [comment]
@paglias good to know! so definitely something that would be nice to have this quarter for sure. thanks for explaining. Will leave to phillips discretion if he'd like to bump it up.
