### ISSUE TITLE
Join: username and name are white text on white box in Dark Mode

### ISSUE THREAD

**Issue by BenjaminCCross** [HabitRPG/habitrpg-ios#881]
**Describe the bug**
When joining after registration, a login with username and '@' name is displayed. A text box says he created names for you, but any text in the box is written as white text so it's impossible to read unless you copy and paste.

**To Reproduce**
When in game -> logout -> back 
This also occurs when you first make an account

**Expected behavior**
Text should be black on white not white on white

**Screenshots**
![image](https://user-images.githubusercontent.com/21342404/80375687-af75dc00-8866-11ea-9a11-3b4b3a766ac8.png)

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: 13.4.1
 - App Version: 2.8.1
 - Habitica Username: fireflow20

**Additional Context**
I am in Dark mode

**Comment by saraolson** [comment]
we actually just fixed this in the latest test build, so it should be fixed next update! see issue #867
