### ISSUE TITLE
Sign-in with applie id creates new tasks and restarts set-up process

### ISSUE THREAD

**Issue by OneThatWalks** [HabitRPG/habitrpg-ios#885]
**Describe the bug**
Sign-in with apple prompts username/displayname and avatar creation each time

**To Reproduce**
1. Register with Apple ID (I did through browser)
2. Complete set-up steps
3. Sign in with Apple ID on iOS
4. See extra steps

**Expected behavior**
Expected to go to the task list

**Screenshots**
Video and screenshot coming

**Smartphone (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: 13.4.1
 - App Version: 2.8.1
 - Habitica Username: onethatwalks

**Comment by saraolson** [comment]
@OneThatWalks did this only happen once? it may be that the flag for finishing sign up wasn't set after you went through it on the website

**Comment by OneThatWalks** [comment]
@saraolson It happened twice that day. I did just try to logout from the app and re-log in like I had done before and now it seems set properly.
