### ISSUE TITLE
The Leader tag in the party members screen gets buried under class icons and buffed icons

### ISSUE THREAD

**Issue by AlexanderColen** [HabitRPG/habitrpg-ios#907]
**Describe the bug**
The `Leader` tag in the party members screen gets overlapped by the class icon and buffed icon for a user.

**To Reproduce**
1. Go to menu using bottom navigation bar by clicking the last button.
2. Go to your Party.
3. Click on the Details tab.
4. Scroll down to look at your party members, and spot the overlapping 

**Expected behavior**
The leader tag should not be overlapped by the class & buff UI elements in your party members.

**Screenshots**
![habitica_ios_party_members_overlay_bug](https://user-images.githubusercontent.com/25740945/90159135-f3311a80-dd5d-11ea-94a9-282c79ae0425.png)

**Smartphone:**
 - Device: iPhone SE (2016)
 - OS: iOS 10.3.3
 - App Version: 2.10.1 (483)
 - Habitica Username: Smelly Alex

**Additional context**
Most likely caused by the app being developed with bigger screens/resolutions in mind. Potentially would require fully scaling every elements to fix it.

**Comment by phillipthelen** [comment]
Make it so that the icons overflow to the next line if they wouldn't fit.
