### ISSUE TITLE
Windup hatching potion image not loading in app

### ISSUE THREAD

**Issue by jaingaurav** [HabitRPG/habitrpg-ios#910]
**Describe the bug**
It seems the windup hatching potion image is not loading in the app on the "Pets & Mounts" screen or quest pop-up. The app logs indicate when loading https://habitica-assets.s3.amazonaws.com/mobileApp/images/Pet_HatchingPotion_Windup.gif it receives a 400 and an invalid api error being reported.

**To Reproduce**
Open app and open "Pets & Mounts" screen

**Expected behavior**
Windup potion image should be visible.

**Additional context**
Should the image be a gif? All other images are pngs.

**Comment by saraolson** [comment]
this is known. the app has to be updated to display gifs, and its planned for the next update that will be out soon.
