### ISSUE TITLE
Entering password to confirm deletion of account isn't working

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#919]
iOS Version: 13.7
Device: iPhone SE
App Version: 3.0.2 (515)
User ID: 00660799-cd98-49ff-a5e1-dca2c1df1aab

"I am trying to delete my Habitica account. However when the “delete account” option prompts to input your password, it won’t go through. It’s like it’s only an empty text box that doesn’t actually work. I tried deleting and re-installing the app but it still doesn’t work."

Can't test this to try and replicate, so this is just the user's report. I believe there has been at least one other previous report.

**Comment by saraolson** [comment]
if it's local login, i can't replicate it but the delete modal is behaving strangely and collapsing tap areas so it's hard to actually press the delete button. do we know their login method? hopefully since its prompting for pword, it is local but you never know

**Comment by shanaqui** [comment]
They've deleted their account now, so impossible to tell...
