### ISSUE TITLE
RYA incorrectly shows dailies which were actually completed

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#920]
User report: "When I open the app and my cron runs for the day, it always asks what dailies I did yesterday showing them all as unmarked, even if I did do all my dailies. It also marks them for the current day instead of yesterday when I do check them off again in the popup."

iOS Version: 14.2
Device: iPhone 7
App Version: 3.0.2 (515)
User ID: 2eb203f5-1b1e-4e5d-84a4-22f130a1090e
Level: 16
Class: mage
Is in Inn: false
Uses Costume: false
Custom Day Start: 8

**Comment by saraolson** [comment]
same issue as in #868

**Comment by thewilloftheshadow** [comment]
I was the one who reported this bug, just wanted to note it happened again today on the newest version
