### ISSUE TITLE
App becomes unresponsive on adding a new To-Do

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#923]
User report: "App crashes (becomes unresponsive) when I try to add a new todo task, as soon as I press the + button everything halts."

I checked with the user and it only occurs with To-Dos. Only one report so far.

The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
iOS Version: 14.0.1
Device: iPhone 7 Plus
App Version: 3.0.3 (520)
User ID: ae5e5969-3d75-4c06-9078-7d82bf6bb488
Level: 11
Class: mage
Is in Inn: false
Uses Costume: false
Custom Day Start: 0

**Comment by shanaqui** [comment]
Opened the bug just to keep it on the radar, but still asking the user to try things like clearing the cache and uninstalling/reinstalling.

**Comment by saraolson** [comment]
unable to reproduce

**Comment by shanaqui** [comment]
New report of same, says it happens 8/10 times:

iOS Version: 14.0.1
Device: iPhone 11
App Version: 3.0.3 (520)
User ID: 3217a6ea-c623-46be-b819-898fd5664bd5
Level: 60
Class: rogue
Is in Inn: false
Uses Costume: false
Custom Day Start: 0

**Comment by shanaqui** [comment]
Another report of the same, but this person says it happens randomly and definitely not every time:

iOS Version: 14.0.1
Device: iPhone 11
App Version: 3.0.3 (520)
User ID: 7516c69c-8810-44ee-9a75-1ce6ffe88a3c
Level: 2
Class: warrior
Is in Inn: false
Uses Costume: false
Custom Day Start: 0

No one has yet got back to me about whether clearing the cache or reinstalling the app helps, but since it's been more than one person, it does seem like there's probably something happening here!

**Comment by shanaqui** [comment]
And another report:

iOS Version: 14.0.1
Device: iPhone SE (2nd generation)
App Version: 3.0.3 (520)
User ID: b33e17e6-bd2e-4ff6-935c-0e626f4229ed
Level: 4
Class: warrior
Is in Inn: false
Uses Costume: false
Custom Day Start: 0

They've tried deleting and reinstalling without effect and their report has a couple more details, so I'll include it:

"Every time I tried to add a to-do using the “+“ button or using the force touch from the iPhone Home Screen, the app completely freezes up. It does not allow me to navigate anywhere else or even scroll. This is not true of adding dailies or habits. I tried deleting and reinstalling the app and am getting the same problem."

**Comment by shanaqui** [comment]
10ed2ea2-a4b9-4627-9f31-1f0bfafdd05d has confirmed that neither clearing the cache nor reinstalling the app help at all.

**Comment by shanaqui** [comment]
This may be a separate issue, but since the other one about dailies was closed as being related to this thread, I'll put this here to start with:

> When I try to edit a habit, for example to set it from daily to weekly reset, the app freezes and I have to restart it to get it to do anything.
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 14.0.1
> Device: iPhone XS Max
> App Version: 3.0.3 (520)
> User ID: 94478765-1e86-4e16-8b56-513681b4c831
> Level: 25
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 6

**Comment by shanaqui** [comment]
Another report of it freezing on adding a to-do from this user:

iOS Version: 14.0.1
Device: iPhone 8 Plus
App Version: 3.0.3 (520)
User ID: 64b3d070-c6a8-4a98-891b-ef6f6dca5bf2
Level: 19
Class: healer
Is in Inn: false
Uses Costume: true
Custom Day Start: 0

**Comment by shanaqui** [comment]
Another report, again about adding a to-do:

iOS Version: 14.0.1
Device: iPhone XR
App Version: 3.0.3 (520)
User ID: 75dc3bb1-46c6-4e57-8a8c-c873dcc77936
Level: 23
Class: mage
Is in Inn: false
Uses Costume: false
Custom Day Start: 0

**Comment by shanaqui** [comment]
User report: "I cannot add a new To Do on my iPhone X. Each time I either click the plus icon or try from the Home Screen, the app freezes and I must restart. I can only add new To Dos on my iPhone 8."

I'll check in whether they're on the same version on both devices. 

iOS Version: 14.0.1
Device: iPhone X
App Version: 3.0.3 (520)
User ID: 37917d7f-f59a-4407-adae-323e5786105e
Level: 32
Class: mage
Is in Inn: false
Uses Costume: false
Custom Day Start: 0

**Comment by shanaqui** [comment]
> Hello, the app is freezing any time I tap the + to add a to-do. I have tried shutting down and restarting the app, clearing my cache and reloading, pulling down to reload the to-do page, and deleting and reinstalling the app.
> Thanks for your time!
> 
> 
> 
> 
> 
> 
> 
> 
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 14.0.1
> Device: iPhone XS Max
> App Version: 3.0.3 (520)
> User ID: a943d9e8-c6e0-47cb-a72e-314867e7a72f
> Level: 5
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0

**Comment by shanaqui** [comment]
Another user (who did not include the iOS version etc) who reported this issue states that if they turn their device horizontally, everything works fine.

Edited to add their device details: 3.0.3 (520), iOS version 14.0.1

**Comment by shanaqui** [comment]
There have been a few more new reports that didn't include device details, but this is one that does and mentioned that adding a to-do is not working:

> iOS Version: 14.0.1
> Device: iPhone 8
> App Version: 3.0.3 (520)
> User ID: 4cddf53c-7afb-4943-b4da-6e6c0ef0c39d
> Level: 54
> Class: mage
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0

This one states the entire dailies tab is not working:

> iOS Version: 14.0.1
> Device: iPhone XR
> App Version: 3.0.3 (520)
> User ID: 5fa675b0-d07f-4179-bfb1-d2682bc49808
> Level: 1
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0

This is an earlier report than the others, on 4th Oct, from a different version, which seems to have been accidentally archived without any information being captured. Luckily the user replied again! This one is a case of the whole To-Do section being unresponsive.

> iOS Version: 14.0.1
> Device: iPhone SE (2nd generation)
> App Version: 3.0.2 (515)
> User ID: 4e3c0dde-a16c-4bf3-afe0-0e38850c1a7b
> Level: 5
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0

This one states that adding a new habit crashes the app:

> iOS Version: 14.0.1
> Device: iPhone 7 Plus
> App Version: 3.0.3 (520)
> User ID: 4ea8a7bf-3e10-4462-98e4-e682a6d1743a
> Level: 5
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0

**Comment by saraolson** [comment]
that's enough reports for now, if there are any more on 3.1, then let us know
