### ISSUE TITLE
App freezes on dailies tab

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#925]
User report: "I tried clearing cache and reinstalling the app but it didn’t work.
I can use all tabs except for dailies.. whenever I touch a task it freezes"

iOS Version: 14.0.1
Device: iPhone X
App Version: 3.0.3 (520)
User ID: f7275dd4-5b65-4bdb-867c-fb54f328ffcd
Level: 10
Class: healer
Is in Inn: false
Uses Costume: false
Custom Day Start: 0

Only one report of this that I know of; out of suggestions to give them.

**Comment by phillipthelen** [comment]
This is very likely the same issue as #923
