### ISSUE TITLE
Class selection caused app to close and then wrong class was selected

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#930]
User report:

> I pressed to choose warrior as her class, but then the app closed, and
> when I opened it again it was chosen as rogue,
> Can you guys help me?

iOS Version: 14.0.1
Device: iPhone XR
App Version: 3.0.3 (520)
User ID: 2fd35ca9-b072-4693-8e1c-ff7d3ca38ecf
Level: 10
Class: rogue
Is in Inn: false
Uses Costume: false
Custom Day Start: 0

There is a [similar issue on Android](https://github.com/HabitRPG/habitica-android/issues/1378) where the selection goes wrong (but without app closure). I'll give the user three gems and ask them to try again.

**Comment by phillipthelen** [comment]
Do we have more than one report of this? I can't reproduce this issue and can't find anything in the crash reports that would match this.
