### ISSUE TITLE
Stats Points appear to be able to be allocated before Class is chosen

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-ios#932]
**Describe the bug**
The app lets players to see their Stat Points before they have chosen a class, and lets them think they can allocate Points (which then fails at the API level, as expected). 

I have no direct experience of this (no iOS device) but I've seen it reported often, such as this report from the Tavern today from @trishaong (5fc1be3a-e4d4-42df-8a0d-2769cac40620), a level 3 player on iOS:

_"when i try to allocate points it tells me to select a class 🤔"_

**To Reproduce**

I assume but have not tested:
1. Create a new account.
1. Level up to level 2.
1. Go to the Stats area.

**Expected behavior**
Same behaviour as on website.

Players should not see that they have points allocated, nor be able to allocate them until **after they have chosen a class**.

Note that hiding Stat Points until level 10 is not sufficient because a player at level 10 or above who has not chosen a class is not meant to see Stat Points.
Similarly, if they choose a class and then later opt out of the class system, they should stop seeing Stat Points. Allocating Points is a class system feature.

**Comment by saraolson** [comment]
so our solution to this is:
-before level 10: show stats in menu but it's disabled with text 'Unlocks at lvl 10'
-if opted out: hide stats in the menu

this primes the user for a new feature at level 10 while not overloading them with information they can't use yet, and cleans up the menu if they decide to opt out.
