### ISSUE TITLE
Group tasks with ‘need approval’ kill my party

### ISSUE THREAD

**Issue by sarahjean** [HabitRPG/habitrpg-ios#936]
I have set up a group, it seems like when I create a group task and set to ‘need approval’, and one of the members tries to click on it (both iOS) they immediately lose all their health and get the death screen. Also appear to be level 0. Then if they navigate around they get a message about leveling to their previous level and health reset. I have tried to reproduce the issue on my account but as the group manager I think it does not affect me.

It seems to happen on all three boards, habits, dailies, to do's. Tasks they made for themselves work fine.

Please let me know if more info is needed.

**Comment by saraolson** [comment]
so to replicate this, you need to have a team leader assign a task to you that needs approval, then try to complete that task from your taskboard on the ios app?

**Comment by sarahjean** [comment]
@saraolson yeah, or for a habit click the plus icon. I am not sure if it occurs on the web side or not because neither of the group members uses the website, only the app.

**Comment by SabreCat** [comment]
Users of the mobile apps are still seeing this behavior. Maybe it's regressed somehow?
