### ISSUE TITLE
Unable to join challenges via the app

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#951]
User report: "Ever since last update I am unable to join challenges via app."

I asked them to clarify and they replied: "Nothing goes wrong per se (more not right!) it just does the slight color change but doesn’t confirm etc. 
same with the other challenge in my group. I have been participating in all of them up to this point, I don’t know if it makes a difference but I exclusively use the app. I have refreshed cleared cache etc."

iOS Version: 14.1
Device: iPhone 11
App Version: 3.1 (524)
User ID: 67f8618b-3861-4838-8fc7-3943d7da1137
Level: 154
Class: mage
Is in Inn: false
Uses Costume: true
Custom Day Start: 0

They also re-tested it on 3.1.1 just to be sure.

**Comment by saraolson** [comment]
is this the only report of this issue? tryin to gauge how widespread it might be.

**Comment by saraolson** [comment]
im unable to reproduce, just joining public challenges. assuming this might be party challenges?

**Comment by phillipthelen** [comment]
I also tried with a party challenge and was able to join and leave that without a problem.
