### ISSUE TITLE
Issues with Facebook log-in

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#953]
User report:

> so I can login on the web (hooray).
> 
> Yesterday updated my iOS phone...  Everything was fine before, but now I can't log in there.  I am linked to facebook, and can log into facebook.  I'm on iOS 14.2 (updated from 13.7 yesterday).  When I log into habitica, I get the login screen and it flips to facebook, where fb says You previously logged in to habitica with fb.  Would you like to continue? I click continue.  Back to habitica and the log in with the facebook app...
> 
> https://habitica.fandom.com/wiki/Login_Problems - I tried deleting the app, restarting my phone, and reinstalling the app.  Same results as above. 
> 
> userid: f91a67a7-6f21-4613-9b30-fd8b0e3259aa
> 
> I appear to be running Habitica v3.1
> 
> I think that's all the info you requested...

They have now downloaded 3.1.1 and are seeing the same issue.

**Comment by phillipthelen** [comment]
I can't seem to reproduce this. Is this with the FB app?
