### ISSUE TITLE
Settings menu icons not working

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#956]
User report:

> I can't access the menu (settings etc). This also means I cant reset cache, log out and the like. Unistall, reboot and install again didn't work. The three buttons are just cramped together in the app, not working

I asked them to try reinstalling again and it still didn't help, but should ensure they're on 3.1.1.

**Comment by saraolson** [comment]
![Image(4)](https://user-images.githubusercontent.com/12453119/100638364-eed74000-3301-11eb-9df6-8bfb4c0454f4.png)

screenshot of the issue

**Comment by saraolson** [comment]
this may be a problem with this user's specific data? not sure

**Comment by phillipthelen** [comment]
See #961
