### ISSUE TITLE
Habitica ios app doesn't show TODOs properly

### ISSUE THREAD

**Issue by nwroblewski** [HabitRPG/habitrpg-ios#958]
In the tab TODO in the browser I can see all undone tasks, but ios app shows only done TODOs.
Iphone SE

**Comment by saraolson** [comment]
@nwroblewski is there a filter applied on your ios view? the filters don't carry over between web and ios, so could have different view settings.

**Comment by nwroblewski** [comment]
No, not even a single filter applied, checked it before raising issue here.

**Comment by phillipthelen** [comment]
To see completed Todos, you have to open the filters for todos and then select "Done" at the top. that should show you all completed todos. Is that list then empty for you?

**Comment by nwroblewski** [comment]
Yup, checked that out. I am closing the issue then. UI isn't really intuitive for me, that's all
