### ISSUE TITLE
Display streak for dailies

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitrpg-ios#96]
currently the streak for dailies is displayed when tapping a daily. but this also opens the edit form. We need a better solution

**Comment by Shadallark** [comment]
What about the idea of using a swipe right to display the streak?  Swiping left displays the Delete option as expected.  Or, if it makes more sense we could use touch and hold to display the streak.

**Comment by vIiRuS** [comment]
Swiping is always a bit tricky, as it often isn't intuitive. the right swipe for deleting (or in newer iOS versions also further actions) is an established pattern, that users are familiar with. But swiping right for more information isn't that established and most users would miss it.

My current idea would be to have an icon with the streak count in one of the corners that is always visible. (the icon of course should be the same or at least very similar to the one on the website ). But I'm not sure how good that would look in reality.

**Comment by Shadallark** [comment]
Okay.  That makes sense.  I am working on something else at the moment but if no one else takes this up over the weekend I will look into it next week.

**Comment by Shadallark** [comment]
I am starting to work on this issue tomorrow.

**Comment by Shadallark** [comment]
Hey @vIiRuS , can you provide some insight into how I can incorporate glyphicons into the iOS project?  I would like to use the same icon as is used on the website to indicate the streak counter but it comes from ` span class="glyphicon glyphicon-forward"></span.` on the website version and I am not sure how to get to it from the iOS code.

**Comment by kyle-fox** [comment]
You should be able to do it with `[iconFactory createImageForIcon:NIKFontAwesomeIconForward]` from the FontAwesomeIconFactory pod that's being used throughout the app - I think it should be close enough. Might have to instantiate a `NIKFontAwesomeIconFactory`, if one hasn't already been created in the class you're using.

**Comment by vIiRuS** [comment]
:+1: the forward icon from font awesome is basically the same.
