### ISSUE TITLE
Edit task screen is unresponsive for around a minute

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#960]
"Whenever I go to edit a task, the edit screen will pop up but I can’t interact with it for ~a minute. Please advise!"

The user has tried it and clearing the cache doesn't help. The app doesn't crash, just sticks for that minute.

iOS Version: 14.2
Device: iPhone 7 Plus
App Version: 3.1.1 (526)
User ID: 602cab3a-0d2d-4968-b960-089bf5c0ce2b
Level: 45
Class: healer
Is in Inn: false
Uses Costume: true
Custom Day Start: 4

**Comment by saraolson** [comment]
Hm i wonder if this is due to a particular task, or a particular way they make tasks that causes this since we don't really hear this from anyone else.

**Comment by shanaqui** [comment]
Another user has reported being unable to edit tasks at all; the app just crashes:

> iOS Version: 13.3
> Device: iPhone 6s Plus
> App Version: 3.1.3 (532)
> User ID: 8667b758-06ef-41aa-8ce8-bb20b264b538
> Level: 91
> Class: mage
> Is in Inn: true
> Uses Costume: true
> Custom Day Start: 2

**Comment by shanaqui** [comment]
"Hello! I can confirm that the bug preventing one from editing tasks on iOS is still occurring. From my experience, the app basically freezes when I try to edit the task."

> iOS Version: 14.6
> Device: iPhone 11
> App Version: 3.3.1 (600)
> User ID: c948b65d-c7e3-4538-b71a-594890b6a1bd
> Level: 77
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0

**Comment by saraolson** [comment]
is this for every task? a certain type of task (daily vs habit)? does everyone experience it across all tasks?

**Comment by saraolson** [comment]
this may have been fixed with the rewrite of the task screen. going to close until reported again.
