### ISSUE TITLE
Quest shop: Correctly label unlock conditions for Check-In quests

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#963]
The Lunar quest line currently says you have to finish previous quests in the line to unlock the next. ie 'Finish Quest 2' is under the locked quest 3.

It should instead say '40 Check-ins', as that is the actual unlock method for that quest. This caused some confusion for users that finished quest 2 but didn't see quest 3 and then went to the shop to see it locked.

**Comment by shanaqui** [comment]
This one causes confusion pretty regularly, often for very new users, so it'd be great if we could get it straightened out!

**Comment by saraolson** [comment]
will see how hard it might be to fix in next update
