### ISSUE TITLE
HTML displayed instead of it being formatted correctly in quest description popup, maybe other popups

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-ios#964]
Similar to Android issue https://github.com/HabitRPG/habitica-android/issues/1422, HTML tags are visible in the quest description popup, rather than being used to format the text.

It was reported by @gyrfalcon17 (details below), who says that the tags visible are the ones shown in the the Android screenshot at https://github.com/HabitRPG/habitica-android/issues/1422#issuecomment-739420692

iOS Version: 14.2
Device: iPhone X
App Version: 3.1.3 (532)
User ID: 809b7bbc-a562-4818-84ec-5e839426bf01
Level: 39
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 7

**Comment by saraolson** [comment]
this may be fixed, if another issue comes up, we can reopen. if reported again, include a screenshot of the new area its seen
