### ISSUE TITLE
Snowball/snowman effects not visible

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#965]
Users have observed the snowman 'buff' working on web but not appearing on mobile. I believe this has been a known issue for a long time -- it certainly happened last year at least -- but I couldn't find an issue for it.

**Comment by shanaqui** [comment]
Here are the details from someone seeing this issue:

iOS Version: 14.2
Device: iPad Pro (12.9-inch) (4th generation)
App Version: 3.1.3 (532)
User ID: 6a4deeb7-c44f-4111-9134-625f5fdd71e8
Level: 12
Class: warrior
Is in Inn: false
Uses Costume: false
Custom Day Start: 0

**Comment by thewilloftheshadow** [comment]
Can still repro

iOS Version: 14.3
Device: iPhone 7
App Version: 3.1.3 (532)
User ID: 2eb203f5-1b1e-4e5d-84a4-22f130a1090e
Level: 43
Class: mage
Is in Inn: true
Uses Costume: true
Custom Day Start: 8
