### ISSUE TITLE
App crashing (when trying to load images?)

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#968]
User report: "The app crashes constantly, on any page. This is the latest compatible update for iPhone 5, so I can't update the app, and I've tried restarting my phone, resetting the cache, force closing the app, etc. The app seems to crash on any page and I can't keep the app open for more than 30 seconds on one of the main tabs without it crashing. The easiest way to make it crash is trying to navigate the shops and scrolling down immediately since it seems that loading new content crashes it. Going to the customize avatar page similarly causes an instant crash when it tries to load the images."

> 
> iOS Version: 10.3.4
> Device: iPhone 5
> App Version: 3.1.3 (532)
> User ID: 957fe77c-54e7-4185-9359-7c71cfb35b70
> Level: 20
> Class: healer
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 5

**Comment by shanaqui** [comment]
This might be caused by the same issue: "it always crashes and shuts down when I use it. I can only use it for a few seconds or minutes until it crashes again."

iOS Version: 10.3.4
Device: iPhone 5
App Version: 3.1.3 (532)
User ID: 980c832b-4163-460d-8d97-cd599665ab86
Level: 29
Class: mage
Is in Inn: false
Uses Costume: false
Custom Day Start: 21

Clearing the cache helped a bit but didn't stop the issue.

**Comment by saraolson** [comment]
Will look into this in 3.3 to see if there's an easy fix if no one else takes it on before then

**Comment by deirdresm** [comment]
FWIW, I can't reproduce on iOS 14.4 (on a 6s). As a former Apple bug screener, hard to guess without seeing a crash log, but the most likely candidate for a repro crash like this on an older OS was missing an ifdef somewhere for a newer capability.

**Comment by saraolson** [comment]
@deirdresm thanks for the heads up, will check that out when we get around to this
