### ISSUE TITLE
Chat "jumping" so users need to scroll to find the right place again

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#971]
"I have this problem, when I’m scrolling in the guilds’ threads, I think on the party thread too, from time to time the screen would “jump” up, and I would need to scroll back to where I was. That’s quite annoying 🙊 I think it happens almost always and immediately when I “like” comments, and then sometimes it just happens by itself (maybe only after I’ve “liked” comments, I’m not sure). It is something that happened since I started using the app about a month ago, not a new bug."

iOS Version: 12.4.1
Device: iPhone 6s
App Version: 3.1.3 (532)
User ID: 7791a68b-cb6f-4004-9efe-f685623ecd80
Level: 37
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 0

**Comment by saraolson** [comment]
we've had this issue with chat for awhile, that when you're scrolled up deep in messages it will seem to jump around. if anyone can figure out a way to make it act a little cleaner, that'd be wonderful. we tried for a bit but it wasn't working and we had to move on.

**Comment by saraolson** [comment]
we're going to try to change the chat library and hope that it improves this unwanted behavior

**Comment by saraolson** [comment]
havent seen this behavior for awhile, the library fix may have actually helped. so gonna close unless it gets reported again.
