### ISSUE TITLE
Unable to join challenges from app

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#973]
User report:

> I am not able to join challenges from within the app. When I go to a challenge page, I see the green “Join challenge” button, but when I tap it there is no feedback and nothing happens. If I go to the “My Challenges” section, I can see that the new challenge is not there, and if I return to the challenge page, the green button is still there.
> 
> I have tried refreshing the page by pulling down, clearing the cache and reloading content, quitting the app and re-starting it, but nothing has worked. I can join challenges without problem from the website in my computer.
> 
> Thank you for your help.
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 14.3
> Device: iPad Pro (10.5-inch)
> App Version: 3.1.3 (532)
> User ID: 21255aec-62eb-4006-a9cb-5dee4edcb6f9
> Level: 81
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0

**Comment by saraolson** [comment]
this is fixed in 3.2 already, see closed issue #951
