### ISSUE TITLE
Gem package won't allow purchase

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#977]
User report:

> Hi, for the second month in a row I am unable to purchase the 4 gem pack. The others seem to work, but the 4 pack doesn’t respond. I do have a subscription but I usually buy several 4 packs a month. 
> 
> Thank you
> 
> -Onna
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 14.3
> Device: iPhone SE (2nd generation)
> App Version: 3.1.3 (532)
> User ID: 229bd18f-7194-4959-8387-e3af41473205
> Level: 159
> Class: warrior
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 6

Clearing the app's cache does not help.

**Comment by saraolson** [comment]
i think this happened with the android store as well, i wonder if its a similar reason.
