### ISSUE TITLE
Markdown that works in task titles and notes on web does not work in app

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#978]
A user has tried to embed this markdown in a task title:

`![progress](https://progress-bar.dev/10/?title=GENERAL)`
![progress](https://progress-bar.dev/10/?title=GENERAL)

It works on the web version, but not in either of the apps.

User details:

iOS Version: 14.3
Device: iPad mini 4
App Version: 3.1.3 (532)
User ID: 4d91c255-ab72-4a2a-8ed3-6a18a6f027e5
Level: 88
Class: mage
Is in Inn: false
Uses Costume: true
Custom Day Start: 0

Screenshot:

![image](https://user-images.githubusercontent.com/8144640/106599528-1e4c3800-6551-11eb-9249-6097e2a45787.png)

It works fine on web:

![image](https://user-images.githubusercontent.com/8144640/106599994-bb0ed580-6551-11eb-812f-b23cbd60e36e.png)

**Comment by saraolson** [comment]
@shanaqui this doesnt work bc the image the markdown shows is an svg, which the apps don't support. so just something where mobile will have a more limited markdown experience.
