### ISSUE TITLE
Siri shortcuts not quite working

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#979]
User report:

> Siri integration is difficult and inconsistent
> 
> Siri Prompt: “Add a task to Habitica”
> Siri: “which list should I add that to?”
> Siri Prompt: “To do.”
> Siri: “which list should I add that to?”
> Siri Prompt: “Which lists are there?”
> Siri: “Here are the lists”
> Siri Prompt: “To do”
> Siri: “Sorry, I’ve run into a problem. Please try again later.”
> 
> 
> The following lines help us find and squash the Bug you encountered. Please do not delete/change them.
> iOS Version: 14.3
> Device: iPhone 6s
> App Version: 3.1.3 (532)
> User ID: 6a5d21c6-ee83-4314-be3c-6fb6693e66fd
> Level: 37
> Class: rogue
> Is in Inn: true
> Uses Costume: true
> Custom Day Start: 0

**Comment by saraolson** [comment]
We took a look at this but couldn't find anything obvious to fix, sometimes siri just seems to be.. finicky? these shortcuts were a contributor project, and we don't have the resources right now ourselves to look into improving it or fixing bugs so I'll just leave this as help wanted if anyone comes along and wants to dig into it.

**Comment by saraolson** [comment]
We havent heard any issues reported about siri shortcuts recently, and they're a pretty small use case in the app now. So, we're going to close this unless more information comes up about them.
