### ISSUE TITLE
User is not able to cron on iOS

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#982]
A user describes not being able to cron in the app. It's not a crash in the cron process, because cron runs correctly if they open the web version... and pulling down to refresh doesn't help. Cron just doesn't seem to trigger at all.

iOS Version: 14.4
Device: iPhone XS
App Version: 3.2 (567)
User ID: ab47c942-de7e-4186-bd3e-9dc0766b4e84
Level: 2
Class: warrior
Is in Inn: false
Uses Costume: false
Custom Day Start: 4

They're a new user, but they first reported this 9 days ago, so I'd have expected any first-few-days issues to have shaken out by now.

**Comment by saraolson** [comment]
@shanaqui did you instruct them to cron on mobile browser? i see a bunch of those events. wondering if they're giving mobile a chance to cron or if thats just their routine now?

**Comment by shanaqui** [comment]
@saraolson I'm not entirely sure I understand the question, sorry! I asked them to check on the day before I opened the issue whether they could cron on the app now if they pulled down to force a sync, and they could not. Is that what you mean?

Excerpts from their emails in case this illuminates things any:

> If I log in with a browser, the daily begins. 
> However, the daily is not updated only with the app. 
> Is this normal?

I asked: "No, that shouldn't happen! The app should be able to cron (roll your day over) for you as well. When you log in via the app, does it work once you go to the web version? Or does logging in with the app first make it impossible all day?" (to rule out crashed crons).

They replied:

> The day starts and cron doesn't happen when I access it with the app.  There is no login bonus and it is the same as the end of yesterday.  
> 
> When I then log in to the web, I get a cron.
> There is no problem with cron occurring twice.

I asked, "Interesting! If you open the app and then pull down to force a sync up, does that help at all?" 

They replied:

> Nothing changes when I pull down and sync!  Of course, the circle mark is displayed.
> Even if I restart the app, cron does not occur.
> Furthermore, it doesn't change when I log out and log in.
