### ISSUE TITLE
Pending progress is not shown for collection quests

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#986]
"  When fighting a boss, the pending damage (which will be applied at the next cron) shows as an orange bar, and the actual damage that will remain after the pending damage is applied at the next cron shows as a red bar.

  When on a collection quest, the actual items collected so far (accumulated after each cron) show as a bar (blue or green?  I can’t remember).  But there is no indication of the number of items collected so far on the current day, which are going to be added to the total of actual items at the next cron.  These are what I called the “pending items collected.”

  The website shows the number of the pending items collected, when on a collection quest.  So it seems odd that the iOS app doesn’t."

> iOS Version: 14.4
> Device: iPhone X
> App Version: 3.2 (567)
> User ID: 809b7bbc-a562-4818-84ec-5e839426bf01
> Level: 86
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 7

**Comment by saraolson** [comment]
Adding the needs design label so i can take a look at it and see if we need any updates before putting in the count
