### ISSUE TITLE
Tasks randomly in wrong order

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#987]
"Dailies mix up their order from time to time.  Totally random then they seem to go back to their place after refresh."

> iOS Version: 14.4
> Device: iPhone 11
> App Version: 3.2 (567)
> User ID: 60798680-a993-4533-b54e-e55865bf2433
> Level: 6
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0

Not the first time this has been mentioned, but couldn't find an issue for it. Refreshing always seems to help (for a time), so it's not the usual task order issue.

**Comment by saraolson** [comment]
this should be fixed since our drag and drop improvements
