### ISSUE TITLE
Users with very high levels cause parties to crash

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#988]
"Some of the members in my party changed their level in the user settings to 999999999 and now the app crashes when I open the party. I am the party leader."

> iOS Version: 14.4
> Device: iPhone XR
> App Version: 3.2 (567)
> User ID: 55aa104f-423e-4b57-82cb-11850708e4fc
> Level: 7
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0

Obviously they're breaking the whole system, but either the app should be able to handle it, or we should cap the values possible via Fix Character Values to something the apps can handle.

**Comment by saraolson** [comment]
closing this bc its something we should fix server side rather than an ios issue
