### ISSUE TITLE
Tags not working to filter the task list

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#993]
User created a video showing the issue: in short, they give a task a tag, but no matter what tag they select, you see the same view. 

(NB: for some reason the video has a soundtrack, just in case you want to pre-emptively mute it!)

https://user-images.githubusercontent.com/8144640/112824132-1062f100-9082-11eb-80b6-a05b2bcfda24.mp4

> 
> iOS Version: 14.4.1
> Device: iPad (6th generation)
> App Version: 3.2.1 (572)
> User ID: 6e00b0b5-ec9a-4e4f-a517-d1a2e0ed6c0c
> Level: 5
> Class: mage
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 23

**Comment by saraolson** [comment]
pog catch me purposefully unmuting to hear the soundtrack. did they mention if this continues after closing and reoping the app, so the task isnt freshly created? ill do some testing to see if im able to reproduce
