### ISSUE TITLE
Implement drag and drop for rewards

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#995]
User reports that long-pressing on rewards is not allowing them to reorganise their rewards.

> iOS Version: 13.4.1
> Device: iPhone SE (2nd generation)
> App Version: 3.2.2 (577)
> User ID: 3c885f0f-6cbc-4262-b94a-d175942e822b
> Level: 2
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0

**Comment by saraolson** [comment]
this is expected. drag and drop has never worked on rewards because of the items on the screen making the logic funky. can convert this to an enhancement request if anyone wants to try to implement drag and drop in this section. pretty sure we've tried before and it just wasnt workin out.

**Comment by saraolson** [comment]
if anyone was to work on this, drag and drop should allow custom rewards to be reordered but they must stay above all item rewards. similarly, item rewards could be reordered but they must stay under custom rewards, no mixing sections.
