### ISSUE TITLE
Setting health to 50.0 in Fix Character Values then sets the value to 0

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#996]
> "when fixing your Character Values it might say Health: 47.0 but if you go to change that by saying 50.0 it will glitch and set it to 0, it’s because of the “.0” and is rather annoying."
> 
> iOS Version: 14.4.1
> Device: iPhone SE
> App Version: 3.2.2 (577)
> User ID: 0c416c9e-4c21-45b6-8b23-adbeff1ac95c
> Level: 10
> Class: mage
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0

**Comment by saraolson** [comment]
i cant reproduce this
