### ISSUE TITLE
Dailies not being displayed at all

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#999]
User contacted us saying their dailies weren't displaying. I asked them to try the usual stuff including clearing the filter, and it didn't help.

Alys checked their tasks for anything weird, at my request, and these were her thoughts:

> I can't see anything obviously wrong. Their Dailies repeat settings look normal (each Daily should appear every day). Their tags are normal (both in the tasks and in their User data).
> I can see from their history data that most of their Dailies were completed in RYA. There's a couple of cases that look like they did complete one or two tasks in the normal task list (OR they got RYA twice on one or two days and completed some Dailies in each of them). That tracks with their statement that occasionally they do see one or two tasks in the normal task screen.
> It feels like the app is just not showing their tasks when it should, assuming that the user did manage to clear their filters correctly.

Here are their details:

> iOS Version: 14.4.1
> Device: iPhone13,1
> App Version: 3.2.1 (572)
> User ID: 89050d2c-b5c6-4133-aad5-9b7a3e0b86cd
> Level: 2
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0

**Comment by saraolson** [comment]
gonna mark this minor unless we see a sudden wave of these. prolly falls under the usual 'hard to figure out why dailies arent acting as expected' bugs unfortunately :/
